[package]
name = "obc-network"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-only"
description = "OBCM network producer"

[dependencies]
obc-data = { workspace = true }
obc-pbf = { workspace = true }
obc-map-core = { workspace = true }
obc-places = { workspace = true }
obc-formats = { workspace = true }
obc-elevation = { workspace = true }
obc-map-scene = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
obc-tree-walk = { workspace = true }

[dev-dependencies]
