// One round of screenshots: node check/shots.js  → check/out/*.png, console errors printed.
const puppeteer = require('puppeteer-core');
const path = require('path');
const fs = require('fs');
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const URL = 'file://' + path.resolve(__dirname, '..', 'index.html');
const OUT = path.join(__dirname, 'out');
fs.rmSync(OUT, { recursive: true, force: true }); fs.mkdirSync(OUT, { recursive: true });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

(async () => {
  const browser = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ['--hide-scrollbars'] });
  const errors = [];
  async function shoot(name, { w, h, mobile, dark, before }) {
    const page = await browser.newPage();
    page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`${name}: console.${m.type()}: ${m.text()}`); });
    page.on('pageerror', (e) => errors.push(`${name}: pageerror: ${e.message}`));
    await page.emulateMediaFeatures([{ name: 'prefers-color-scheme', value: dark ? 'dark' : 'light' }]);
    await page.setViewport({ width: w, height: h, deviceScaleFactor: 2, isMobile: !!mobile, hasTouch: !!mobile });
    await page.goto(URL, { waitUntil: 'load' });
    await sleep(400);
    if (before) await before(page, !!mobile);
    await sleep(700);
    await page.screenshot({ path: path.join(OUT, name + '.png') });
    await page.close();
    console.log('shot', name);
  }
  const open = (id) => async (page) => { await page.evaluate((id) => { App.A.openPlan({ id }); App.render(); }, id); await sleep(300); };
  const alps = open('alps');
  const focus = async (page, mobile, text) => { if (mobile) await page.tap('#head .sbtn'); else await page.click('#qin'); await sleep(200); await page.type('#qin', text); };
  const tent = async (page, mobile) => { await alps(page); await focus(page, mobile, 'campsites end of day 4'); await page.keyboard.press('Enter'); await sleep(700); };
  const picker = async (page, mobile) => { await tent(page, mobile); await page.click('[data-chip="within"]'); };
  const middle = async (page) => { await alps(page); await page.evaluate(() => Sheet.setDetent('middle')); };
  const scrub = async (page) => { await alps(page); await page.evaluate(() => { App.A.selDay({ n: 4 }); App.render(); App.profileHandlers.onScrub(228); }); };
  const route = async (page, mobile) => { await open('new')(page); await focus(page, mobile, 'Titisee'); await page.keyboard.press('Enter'); };
  const build = async (page, mobile) => { await route(page, mobile); await sleep(400); await page.evaluate(() => { App.A.useRoute(); App.render(); }); await sleep(600); await page.evaluate(() => { const p = MapView.screenToMap(600, 300); App.S.callout = { kind: 'add', pos: p, name: 'Near St. Peter', meta: '722 m' }; App.render(); }); };
  const search = async (page, mobile) => { await alps(page); await focus(page, mobile, 'campsites end of day 4'); await sleep(400); };
  await shoot('plans-web-light', { w: 1440, h: 900 });
  await shoot('plans-web-dark', { w: 1440, h: 900, dark: true });
  await shoot('web-light-rest', { w: 1440, h: 900, before: async (page) => { await alps(page); await page.evaluate(() => { App.A.expandDay({ n: 4 }); App.A.selDay({ n: 4 }); App.render(); }); } });
  await shoot('web-dark-rest', { w: 1440, h: 900, dark: true, before: alps });
  await shoot('web-light-tent', { w: 1440, h: 900, before: picker });
  await shoot('web-light-build', { w: 1440, h: 900, before: build });
  await shoot('plans-phone-light', { w: 390, h: 844, mobile: true });
  await shoot('plans-phone-dark', { w: 390, h: 844, mobile: true, dark: true });
  await shoot('phone-light-rest', { w: 390, h: 844, mobile: true, before: alps });
  await shoot('phone-dark-rest', { w: 390, h: 844, mobile: true, dark: true, before: alps });
  await shoot('phone-light-middle', { w: 390, h: 844, mobile: true, before: middle });
  await shoot('phone-light-search', { w: 390, h: 844, mobile: true, before: search });
  await shoot('phone-light-answer', { w: 390, h: 844, mobile: true, before: tent });
  await shoot('phone-dark-answer', { w: 390, h: 844, mobile: true, dark: true, before: tent });
  await shoot('phone-light-picker', { w: 390, h: 844, mobile: true, before: picker });
  await shoot('phone-light-profile', { w: 390, h: 844, mobile: true, before: scrub });
  await shoot('phone-light-route', { w: 390, h: 844, mobile: true, before: route });
  await shoot('phone-light-build', { w: 390, h: 844, mobile: true, before: build });
  await shoot('phone-light-more', { w: 390, h: 844, mobile: true, before: async (page) => { await alps(page); await page.tap('#nav [data-menu="more"]'); } });
  await shoot('land-light', { w: 844, h: 390, mobile: true, before: scrub });
  await shoot('land-dark', { w: 844, h: 390, mobile: true, dark: true, before: scrub });
  await browser.close();
  console.log(errors.length ? 'ERRORS:\n' + errors.join('\n') : 'no console errors');
})();
