//! Compile-time i18n codegen (epic #602, L2).
//!
//! Parses the four per-language catalogs `i18n/{en,de,fr,es}.toml` and writes
//! `$OUT_DIR/i18n_gen.rs`, which `src/i18n.rs` `include!`s. The generated file holds:
//!   * `enum Msg` — one variant per key in `en.toml` (the canonical key set), and
//!   * `const TABLE: [[&str; 4]; N]` — indexed `[Msg as usize][Language as usize]`, so it
//!     lands in flash `.rodata`, not the device's tight RAM budget.
//!
//! `en.toml` defines the universe of keys; the build **fails with a clear, actionable
//! error** if any of de/fr/es is missing a key or carries an extra one.
//!
//! Zero build-dependencies on purpose: the catalog TOML is a trivial `[section]` +
//! `key = "string"` subset, so a ~80-line hand-rolled parser (below) sidesteps adding a
//! crate to *both* Cargo.lock files (the workspace's and the standalone board crate's) and
//! the cargo-deny license/advisory gate. It fits the crate's no_std, minimal-dep house style.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

/// The four catalogs in `Language` discriminant order (En=0, De=1, Fr=2, Es=3) — the
/// TABLE column order and the completeness-check labels both derive from this.
const LANGS: [&str; 4] = ["en", "de", "fr", "es"];

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let i18n_dir = Path::new(&manifest).join("i18n");

    // Re-run codegen whenever any catalog changes.
    for lang in LANGS {
        println!("cargo:rerun-if-changed=i18n/{lang}.toml");
    }
    println!("cargo:rerun-if-changed=build.rs");

    // Parse each catalog. English keeps insertion order (it fixes the `Msg`/TABLE row
    // order); the others only need key -> value lookup, so a map is enough.
    let en_path = i18n_dir.join("en.toml");
    let en = parse_catalog(&en_path);
    let en_keys: Vec<String> = en.iter().map(|(k, _)| k.clone()).collect();
    let en_set: BTreeMap<&str, &str> = en.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();

    let others: Vec<BTreeMap<String, String>> = LANGS[1..]
        .iter()
        .map(|lang| parse_catalog(&i18n_dir.join(format!("{lang}.toml"))).into_iter().collect())
        .collect();

    // Completeness check: en.toml is the universe. Collect *every* problem across all three
    // languages, then fail once with the full list, so a `cargo build` names all offenders.
    let mut problems: Vec<String> = Vec::new();
    for (lang, map) in LANGS[1..].iter().zip(others.iter()) {
        for key in &en_keys {
            if !map.contains_key(key) {
                problems.push(format!("  {lang}.toml: MISSING key `{key}` (present in en.toml)"));
            }
        }
        for key in map.keys() {
            if !en_set.contains_key(key.as_str()) {
                problems
                    .push(format!("  {lang}.toml: EXTRA key `{key}` (not in en.toml — en.toml defines the key set)"));
            }
        }
    }
    if !problems.is_empty() {
        problems.sort();
        panic!(
            "\n\ni18n catalog is incomplete — every key in en.toml must appear in en/de/fr/es, and nowhere else:\n{}\n\n\
             Fix the offending {}.toml file(s) (add the missing keys / remove the extra ones), then rebuild.\n",
            problems.join("\n"),
            LANGS[1..].join("/"),
        );
    }

    // Codegen. One `Msg` variant per English key (in file order), and one TABLE row per
    // variant with the four languages as columns (En, De, Fr, Es).
    let mut out = String::new();
    out.push_str("// @generated by obc-app/build.rs from i18n/*.toml — do not edit by hand.\n");
    out.push_str("// Regenerate by editing the catalogs; cargo re-runs the build script on any change.\n\n");

    // The Msg enum.
    out.push_str("/// A user-facing message key. One variant per key in `i18n/en.toml`; the\n");
    out.push_str("/// discriminant is the row index into [`TABLE`]. Generated — see `build.rs`.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum Msg {\n");
    for key in &en_keys {
        let variant = variant_name(key);
        let en_val = en_set[key.as_str()];
        writeln!(out, "    /// `{key}` = {en_val:?}", en_val = en_val).unwrap();
        writeln!(out, "    {variant},").unwrap();
    }
    out.push_str("}\n\n");

    // The TABLE: [[&str; 4]; N] in flash, indexed [Msg as usize][Language as usize].
    writeln!(
        out,
        "/// Translation table in flash `.rodata`: `TABLE[msg as usize][lang as usize]`,\n\
         /// columns ordered En, De, Fr, Es (the `Language` discriminants). Generated.\n\
         // Only ever indexed (a place expression), never copied by value, so it isn't duplicated\n\
         // per use — the const-vs-static lint is a false positive; kept `const` for the `const fn` lookup.\n\
         #[allow(clippy::large_const_arrays)]\n\
         pub const TABLE: [[&str; 4]; {n}] = [",
        n = en_keys.len()
    )
    .unwrap();
    for key in &en_keys {
        let row: Vec<String> = LANGS
            .iter()
            .enumerate()
            .map(|(i, _)| {
                let v = if i == 0 { en_set[key.as_str()] } else { others[i - 1][key].as_str() };
                format!("{v:?}")
            })
            .collect();
        writeln!(out, "    [{}], // {}", row.join(", "), variant_name(key)).unwrap();
    }
    out.push_str("];\n");

    let out_path = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("i18n_gen.rs");
    std::fs::write(&out_path, out).expect("write i18n_gen.rs");
}

/// `menu` + `off_route` -> `MenuOffRoute`. Splits a dotted `section.key` and each key's
/// `_`-separated words, PascalCasing every piece.
fn variant_name(dotted_key: &str) -> String {
    let mut name = String::new();
    for word in dotted_key.split(['.', '_']) {
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            name.extend(first.to_uppercase());
            name.push_str(chars.as_str());
        }
    }
    name
}

/// Parse one catalog file into ordered `(dotted_key, value)` pairs. Panics with the file +
/// line on any syntax it doesn't accept — the catalog is authored by hand, so a loud, located
/// failure beats silently dropping a key.
fn parse_catalog(path: &Path) -> Vec<(String, String)> {
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| panic!("i18n: cannot read {}: {e}", path.display()));
    let file = path.file_name().and_then(|s| s.to_str()).unwrap_or("<catalog>");

    let mut out: Vec<(String, String)> = Vec::new();
    let mut section: Option<String> = None;

    for (lineno, raw) in text.lines().enumerate() {
        let line = strip_comment(raw).trim();
        if line.is_empty() {
            continue;
        }
        let loc = || format!("{file}:{}", lineno + 1);

        if let Some(inner) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            let name = inner.trim();
            assert!(is_bare_key(name), "i18n: {}: bad section header `[{name}]` (expected `[bare_key]`)", loc());
            section = Some(name.to_string());
            continue;
        }

        let (key, value) =
            line.split_once('=').unwrap_or_else(|| panic!("i18n: {}: expected `key = \"value\"`, got `{line}`", loc()));
        let key = key.trim();
        assert!(is_bare_key(key), "i18n: {}: bad key `{key}` (expected a bare key)", loc());
        let value = parse_basic_string(value.trim(), &loc);

        let dotted = match &section {
            Some(s) => format!("{s}.{key}"),
            None => key.to_string(),
        };
        assert!(!out.iter().any(|(k, _)| *k == dotted), "i18n: {}: duplicate key `{dotted}`", loc());
        out.push((dotted, value));
    }
    out
}

/// Drop a `#` comment, respecting `#` inside a double-quoted string.
fn strip_comment(line: &str) -> &str {
    let mut in_str = false;
    let mut prev_backslash = false;
    for (i, c) in line.char_indices() {
        match c {
            '"' if !prev_backslash => in_str = !in_str,
            '#' if !in_str => return &line[..i],
            _ => {}
        }
        prev_backslash = c == '\\' && !prev_backslash;
    }
    line
}

/// A TOML bare key: ASCII letters/digits/`_`/`-`, non-empty.
fn is_bare_key(s: &str) -> bool {
    !s.is_empty() && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// Parse a TOML basic string: `"..."` with `\" \\ \n \t \r \0` escapes. The catalog values
/// are plain UI copy, so this covers what we author without pulling in a TOML crate.
fn parse_basic_string(s: &str, loc: &impl Fn() -> String) -> String {
    let bytes = s.as_bytes();
    assert!(
        bytes.len() >= 2 && bytes[0] == b'"' && bytes[bytes.len() - 1] == b'"',
        "i18n: {}: value must be a double-quoted string, got `{s}`",
        loc()
    );
    let inner = &s[1..s.len() - 1];
    let mut out = String::with_capacity(inner.len());
    let mut chars = inner.chars();
    while let Some(c) = chars.next() {
        if c != '\\' {
            assert!(c != '"', "i18n: {}: unescaped `\"` inside string", loc());
            out.push(c);
            continue;
        }
        match chars.next() {
            Some('"') => out.push('"'),
            Some('\\') => out.push('\\'),
            Some('n') => out.push('\n'),
            Some('t') => out.push('\t'),
            Some('r') => out.push('\r'),
            Some('0') => out.push('\0'),
            other => panic!("i18n: {}: unsupported escape `\\{}`", loc(), other.unwrap_or(' ')),
        }
    }
    out
}
