import Foundation

// Device Object System v2 identity model — `specs/Device_Object_System_v2.md` §identities and
// `specs/Device_Object_Protocol_v3.md` §1.
//
// Every identity below is a distinct nominal type. None of them is `ExpressibleByIntegerLiteral`,
// none shares a protocol that would let two of them meet in the same generic slot, and none offers
// an initializer taking another identity: mixing a `Revision` with a `LogicalObjectId`, or a
// `SessionId` with a `RequestId`, is a compile error rather than a runtime surprise.
//
// **GenerationId is deliberately absent.** It is the storage-private physical payload identity and
// it has no wire representation at all: §10 says the parent's committed ObjectResult exposes "no
// physical GenerationId", the registries (§2) say a draft part has "no … public physical
// identifier", and no byte table in the protocol contract carries one. Modelling it here would
// invent a field the contract does not have.

/// A 16-byte opaque identity. Copied verbatim; never reordered as UUID fields (§1).
///
/// The only public way to build one is the failable `init?(bytes:)`, so a value of any of these
/// types is 16 bytes by construction. The unchecked initializer is deliberately internal: this
/// module ships inside the companion app, and a public entry point that trapped — or that let a
/// short array through to be re-encoded as an under-length field — would be a defect reachable from
/// application code.
public protocol OpaqueIdentity16: Hashable, Sendable, CustomStringConvertible {
    var bytes: [UInt8] { get }
    /// Fails unless exactly 16 bytes are supplied.
    init?(bytes: [UInt8])
}

/// Internal refinement giving every identity the same checked initializer for free.
protocol UncheckedOpaqueIdentity16: OpaqueIdentity16 {
    init(unchecked bytes: [UInt8])
}

extension UncheckedOpaqueIdentity16 {
    public init?(bytes: [UInt8]) {
        guard bytes.count == 16 else { return nil }
        self.init(unchecked: bytes)
    }
}

extension OpaqueIdentity16 {
    public var isZero: Bool { bytes.allSatisfy { $0 == 0 } }
    public var description: String { bytes.map { String(format: "%02x", $0) }.joined() }
}

/// 128-bit identity minted when an OBC2 store is initialized. A replaced or reformatted card gets a
/// new one; `ResetStore` is the wire form of that transition.
public struct StoreId: UncheckedOpaqueIdentity16 {
    public let bytes: [UInt8]
    init(unchecked bytes: [UInt8]) { self.bytes = bytes }
    public static let zero = StoreId(unchecked: [UInt8](repeating: 0, count: 16))
}

/// 128-bit idempotency key generated by the caller before any mutating operation and persisted in
/// its durable result (§11).
public struct OperationId: UncheckedOpaqueIdentity16 {
    public let bytes: [UInt8]
    init(unchecked bytes: [UInt8]) { self.bytes = bytes }
    public static let zero = OperationId(unchecked: [UInt8](repeating: 0, count: 16))
}

/// 16 opaque bytes the device draws when it seals a draft part. Not an identity of an object, not a
/// digest, and carries no decodable structure (§1, registries §2).
public struct DraftPartRef: UncheckedOpaqueIdentity16 {
    public let bytes: [UInt8]
    init(unchecked bytes: [UInt8]) { self.bytes = bytes }
    public static let zero = DraftPartRef(unchecked: [UInt8](repeating: 0, count: 16))
}

/// The 16 opaque bytes GetDeviceStatus reports. Explicitly *not* a StoreId: replacing the card
/// changes the StoreId and never the serial (§16).
public struct DeviceSerial: UncheckedOpaqueIdentity16 {
    public let bytes: [UInt8]
    init(unchecked bytes: [UInt8]) { self.bytes = bytes }
}

/// Opaque unsigned 64-bit identity inside one object kind and StoreId. **No sentinel values** —
/// zero is an ordinary identity (§6.1, registries §3).
public struct LogicalObjectId: Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt64
    public init(_ rawValue: UInt64) { self.rawValue = rawValue }
    public var description: String { String(rawValue) }
}

/// Unsigned 64-bit monotonically increasing repository revision; the compare-and-swap token.
public struct Revision: Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt64
    public init(_ rawValue: UInt64) { self.rawValue = rawValue }
    public var description: String { String(rawValue) }
}

/// The draft parent's own monotonic snapshot counter (registries §2.1). A different counter from
/// `Revision`, and the two are not interchangeable.
public struct DraftRevision: Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt64
    public init(_ rawValue: UInt64) { self.rawValue = rawValue }
    public var description: String { String(rawValue) }
}

/// Monotonic weather-domain request identity. "never a control RequestId", and never the weather
/// singleton's LogicalObjectId (registries §3).
public struct WeatherRequestId: Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt64
    public init(_ rawValue: UInt64) { self.rawValue = rawValue }
    public var description: String { String(rawValue) }
}

/// `(DraftPartKind, partKey)` is unique within one parent (registries §2.1).
public struct PartKey: Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt64
    public init(_ rawValue: UInt64) { self.rawValue = rawValue }
    public var description: String { String(rawValue) }
}

/// Nonzero unsigned 32-bit ephemeral stream capability scoped to one BLE or USB owner (§3).
public struct SessionId: Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt32
    /// Nil for zero: a zero SessionId is never a capability.
    public init?(_ rawValue: UInt32) {
        guard rawValue != 0 else { return nil }
        self.rawValue = rawValue
    }
    public var description: String { String(rawValue) }
}

/// Nonzero unsigned 32-bit control-request correlation. Neither a SessionId nor an OperationId (§2).
public struct RequestId: Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt32
    /// Nil for zero: a zero RequestId is unanswerable (§2).
    public init?(_ rawValue: UInt32) {
        guard rawValue != 0 else { return nil }
        self.rawValue = rawValue
    }
    public var description: String { String(rawValue) }
}
