// @vitest-environment happy-dom
import { mount, tick, unmount } from 'svelte';
import { writable, fromStore } from 'svelte/store';
import { afterEach, describe, expect, it, vi } from 'vitest';
import Query from './PlannerQuery.svelte';
import type { SearchContext, QueryRequest } from '../../lib/planner/search/types';

const context: SearchContext = {view:[7.8,47.9,8,48.1],plan:{coordinates:[[7.8,48],[7.9,48]],km:[0,7.44],days:[{number:1,from:0,to:7,rest:false}],points:[]}};
const reply = (request: QueryRequest) => ({ok:true,json:async()=>({type:'places',request,results:[]})}) as Response;
const mounted: ReturnType<typeof mount>[] = [];
afterEach(async()=>{ for(const component of mounted.splice(0))await unmount(component); vi.unstubAllGlobals(); vi.useRealTimers(); document.body.replaceChildren(); });
async function setup(extra: Record<string, unknown> = {}) {
    vi.useFakeTimers({toFake:['setTimeout','clearTimeout','setInterval','clearInterval']});
    const target=document.createElement('div');document.body.append(target);
    const component=mount(Query,{target,props:{context,onSearch:()=>{},onClear:()=>{},onLocation:()=>{},onSample:()=>{},onDate:()=>{},onPointing:()=>{},...extra}});
    mounted.push(component);await tick();
    const input=target.querySelector('input')!;
    const type=async(text:string)=>{input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));await tick();await vi.advanceTimersByTimeAsync(351);};
    return {target,type,component};
}
describe('planner query requests',()=>{
    it('defaults to the map and uses the selected point only after an explicit area edit', async () => {
        const fetch = vi.fn(async (_url: string, init: RequestInit) => reply(JSON.parse(String(init.body)).request ?? { type: 'places', what: ['hotel'] }));
        vi.stubGlobal('fetch', fetch);
        const { target, type } = await setup({ selection: { anchor: [7.9, 48] } });
        await type('hotels'); await tick();
        expect(JSON.parse(String(fetch.mock.lastCall![1].body)).pointing).toBeUndefined();
        const chip = [...target.querySelectorAll<HTMLButtonElement>('.chip')].find(b => b.textContent?.includes('In this map view'))!;
        chip.click(); await tick();
        const selected = [...target.querySelectorAll<HTMLButtonElement>('.scopes button')].find(b => b.textContent?.includes('Selected point'))!;
        selected.click(); await tick();
        target.querySelector<HTMLButtonElement>('.apply')!.click(); await vi.advanceTimersByTimeAsync(0); await tick();
        expect(JSON.parse(String(fetch.mock.lastCall![1].body)).request.where).toEqual({ anchor: [7.9, 48] });
    });
    it('shows and edits a route endpoint without losing its scope', async()=>{
        const fetch=vi.fn(async(_url:string,init:RequestInit)=>reply(JSON.parse(String(init.body)).request??{type:'places',what:['restaurant'],where:{scope:'route',part:'end'}}));
        vi.stubGlobal('fetch',fetch);
        const {target,type}=await setup();await type('restaurant at the end of the route');await tick();
        const chip=[...target.querySelectorAll<HTMLButtonElement>('.chip')].find(b=>b.textContent?.includes('Near route end'))!;
        expect(chip).toBeDefined();chip.click();await tick();
        const part=[...target.querySelectorAll('label')].find(l=>l.textContent?.startsWith('Part of route'))!.querySelector('select')!;
        expect(part.value).toBe('end');
        part.value='start';part.dispatchEvent(new Event('change',{bubbles:true}));await tick();
        (target.querySelector('.apply') as HTMLButtonElement).click();await vi.advanceTimersByTimeAsync(0);await tick();
        expect(JSON.parse(String(fetch.mock.lastCall![1].body)).request.where).toEqual({scope:'route',part:'start'});
    });
    it('discards stale responses and keeps a cleared search empty',async()=>{
        const pending: ((response:Response)=>void)[]=[];
        const fetch=vi.fn(()=>new Promise<Response>(resolve=>pending.push(resolve)));
        vi.stubGlobal('fetch',fetch);
        const {target,type}=await setup();
        await type('first sentence');await type('second sentence');
        pending[1](reply({type:'places',what:['hotel']}));await vi.advanceTimersByTimeAsync(0);await tick();
        pending[0](reply({type:'places',what:['campsite']}));await vi.advanceTimersByTimeAsync(0);await tick();
        expect(target.querySelector('.meaning')?.textContent).toContain('hotel');
        expect(target.querySelector('.meaning')?.textContent).not.toContain('campsite');
        await type('third sentence');await type('');
        pending[2](reply({type:'places',what:['campsite']}));await vi.advanceTimersByTimeAsync(0);await tick();
        expect(target.querySelector('.meaning-label')).toBeNull();
        expect(target.querySelector('.chip')?.textContent).toContain('In this map view');
    });
    it('retries interpretation after a temporary model failure instead of keeping the fallback',async()=>{
        const fetch=vi.fn(async()=>reply({type:'place',name:'hotels near day two'}));
        vi.stubGlobal('fetch',fetch);
        const {type,component}=await setup();await type('hotels near day two');await tick();
        component.retry();await vi.advanceTimersByTimeAsync(0);await tick();
        const options=(fetch.mock.lastCall as unknown as [string,RequestInit])[1];
        expect(JSON.parse(String(options.body)).request).toBeUndefined();
    });
    it('sends chip edits as typed requests and keeps the rider’s sentence intact',async()=>{
        const fetch=vi.fn(async(_url:string,init:RequestInit)=>reply(JSON.parse(String(init.body)).request??{type:'places',what:['hotel']}));
        vi.stubGlobal('fetch',fetch);
        const {target,type}=await setup();await type('hotels nearby');await tick();
        (target.querySelector('.chip') as HTMLButtonElement).click();await tick();
        const button=(text:string)=>[...target.querySelectorAll<HTMLButtonElement>('.choices button')].find(b=>b.textContent?.trim()===text)!;
        button('hotel').click();await tick();
        expect((target.querySelector('.apply') as HTMLButtonElement).disabled).toBe(true);
        button('campsite').click();await tick();
        expect(fetch).toHaveBeenCalledTimes(1);
        (target.querySelector('.apply') as HTMLButtonElement).click();
        await vi.advanceTimersByTimeAsync(0);await tick();
        const input=JSON.parse(String(fetch.mock.lastCall![1].body));
        expect(input.request.what).toEqual(['campsite']);expect(input.q).toBe('hotels nearby');
        expect(target.textContent).toContain('Edited request');
        expect(target.querySelector('.picker')).toBeNull();
    });
    it('keeps one editor open and discards an unapplied area edit on Escape', async()=>{
        const fetch=vi.fn(async()=>reply({type:'places',what:['pharmacy'],where:{near:[{name:'Teningen'}]}}));
        vi.stubGlobal('fetch',fetch);
        const {target,type}=await setup();await type('pharmacies in Teningen');await tick();
        const chips=target.querySelectorAll<HTMLButtonElement>('.chip');
        chips[0].click();await tick();chips[1].click();await tick();
        expect(target.querySelectorAll('.picker')).toHaveLength(1);
        const input=target.querySelector<HTMLInputElement>('.picker input')!;
        input.value='Bad ';input.dispatchEvent(new Event('input',{bubbles:true}));await tick();
        expect(input.value).toBe('Bad ');
        input.value='Bad Krozingen';input.dispatchEvent(new Event('input',{bubbles:true}));await tick();
        input.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));await tick();
        expect(fetch).toHaveBeenCalledTimes(1);
        expect(chips[1].textContent).toContain('Teningen');
        expect(document.activeElement).toBe(chips[1]);
        expect(target.querySelector('.picker')).toBeNull();
    });
    it('keeps pagination and retries in the searched area until the rider pans',async()=>{
        const view=fromStore(writable(context)), revision=fromStore(writable(0));
        const onResults=vi.fn();
        const fetch=vi.fn(async()=>({ok:true,json:async()=>({type:'places',request:{type:'places',what:['pharmacy']},results:[{lon:7.81,lat:48.12},{lon:7.85,lat:48.14}]})}));
        vi.stubGlobal('fetch',fetch);
        vi.useFakeTimers({toFake:['setTimeout','clearTimeout','setInterval','clearInterval']});
        const target=document.createElement('div');document.body.append(target);
        const component=mount(Query,{target,props:{get context(){return view.current;},get revision(){return revision.current;},onResults,onSearch:()=>{},onClear:()=>{},onLocation:()=>{},onSample:()=>{},onDate:()=>{},onPointing:()=>{}}});
        mounted.push(component);await tick();
        const input=target.querySelector('input')!;input.value='pharmacies';input.dispatchEvent(new Event('input',{bubbles:true}));await tick();await vi.advanceTimersByTimeAsync(351);
        expect(onResults).toHaveBeenCalledExactlyOnceWith([[7.81,48.12],[7.85,48.14]]);
        const fitted: SearchContext={...context,view:[7.8,48.1,7.9,48.2]};
        view.current=fitted;await tick();await vi.advanceTimersByTimeAsync(250);
        expect(fetch).toHaveBeenCalledTimes(1);
        const sent = () => JSON.parse(String((fetch.mock.lastCall as unknown as [string,RequestInit])[1].body));
        fetch.mockRejectedValueOnce(new TypeError('Offline'));
        component.more();await vi.advanceTimersByTimeAsync(0);await tick();
        expect(sent().view).toEqual(context.view);
        expect(sent().limit).toBe(26);
        component.retry();await vi.advanceTimersByTimeAsync(0);await tick();
        expect(sent().view).toEqual(context.view);
        expect(fetch).toHaveBeenCalledTimes(3);
        expect(onResults).toHaveBeenCalledTimes(2);
        const panned: SearchContext={...context,view:[7.9,48.1,8,48.2]};
        view.current=panned;revision.current=1;await tick();await vi.advanceTimersByTimeAsync(250);
        expect(fetch).toHaveBeenCalledTimes(4);
        expect(onResults).toHaveBeenCalledTimes(2);
        expect(sent().view).toEqual(panned.view);
        view.current=fitted;await tick();
        component.more();await vi.advanceTimersByTimeAsync(0);await tick();
        expect(sent().view).toEqual(panned.view);
        expect(sent().limit).toBe(46);
    });
    it('preserves pending result framing when initial map bounds interrupt the first request',async()=>{
        const view=fromStore(writable(context)), revision=fromStore(writable(0));
        const onResults=vi.fn();
        const fetch=vi.fn().mockImplementationOnce(()=>new Promise(()=>{})).mockResolvedValue({ok:true,json:async()=>({type:'places',request:{type:'places',what:['pharmacy']},results:[{lon:7.81,lat:48.12}]})});
        vi.stubGlobal('fetch',fetch);vi.useFakeTimers({toFake:['setTimeout','clearTimeout','setInterval','clearInterval']});
        const target=document.createElement('div');document.body.append(target);
        const component=mount(Query,{target,props:{get context(){return view.current;},get revision(){return revision.current;},onResults,onSearch:()=>{},onClear:()=>{},onLocation:()=>{},onSample:()=>{},onDate:()=>{},onPointing:()=>{}}});
        mounted.push(component);await tick();
        const input=target.querySelector('input')!;input.value='pharmacies';input.dispatchEvent(new Event('input',{bubbles:true}));await tick();await vi.advanceTimersByTimeAsync(351);
        view.current={...context,view:[7,47,9,49]};revision.current=1;await tick();await vi.advanceTimersByTimeAsync(250);
        expect(fetch).toHaveBeenCalledTimes(2);
        expect(onResults).toHaveBeenCalledExactlyOnceWith([[7.81,48.12]]);
    });
});
