//! Catalog JSON Schema generation and checked-in wire examples.
//!
//! The serde/schemars DTOs live in `model`; this module owns the extra constraints
//! Rust types cannot express and the stable pretty-printed schema artifact.

use serde_json::{Map, Value};

use obc_formats::obct;

use crate::grid::{MAX_CELL_LOG2, MIN_CELL_LOG2};

use super::model::{
    Catalog, CellIndexDocument, RegionCellsDocument, TerrainIndexDocument, GRID_ORIGIN_UDEG, WORLD_SIDE_UDEG,
};
use super::CATALOG_SCHEMA_VERSION;

/// The generated JSON Schema for the catalog documents, checked in so a consumer can
/// validate a fetched catalog — root *and* satellites — without a Rust toolchain.
pub const CATALOG_SCHEMA_JSON: &str = include_str!("../../schema/catalog.schema.json");

/// Worked example of the catalog **root**, regenerated by this module's tests from the
/// synthetic tree in `tests::example_tree`.
pub const CATALOG_EXAMPLE_JSON: &str = include_str!("../../schema/catalog.example.json");

/// Worked example of a **cell index** satellite (§8).
pub const CELL_INDEX_EXAMPLE_JSON: &str = include_str!("../../schema/cell-index.example.json");

/// Worked example of a **region cell list** satellite (§6).
pub const REGION_CELLS_EXAMPLE_JSON: &str = include_str!("../../schema/region-cells.example.json");

/// Worked example of the **terrain cell index** satellite (§13).
pub const TERRAIN_INDEX_EXAMPLE_JSON: &str = include_str!("../../schema/terrain-index.example.json");

fn flatten_descriptions(value: &mut Value) {
    match value {
        Value::Object(map) => {
            if let Some(Value::String(description)) = map.get_mut("description") {
                *description = description.split_whitespace().collect::<Vec<_>>().join(" ");
            }
            for nested in map.values_mut() {
                flatten_descriptions(nested);
            }
        }
        Value::Array(items) => items.iter_mut().for_each(flatten_descriptions),
        _ => {}
    }
}

// --- schema -------------------------------------------------------------------------------

pub(super) const CELL_ID_PATTERN: &str = r"^\d{1,2}/\d{4,}/\d{4,}$";
pub(super) const SHA256_PATTERN: &str = "^[0-9a-f]{64}$";
pub(super) const PINNED_URL_PATTERN: &str = r"^(https?://|/).+\.[0-9a-f]{64}\.[^/?#]+$";
const DATE_PATTERN: &str = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$";
pub(super) const TIMESTAMP_PATTERN: &str = "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$";
pub(super) const ID_PATTERN: &str = "^[a-z0-9]+(-[a-z0-9]+)*$";
const REGION_ID_PATTERN: &str = "^[a-z0-9]+(-[a-z0-9]+)*(/[a-z0-9]+(-[a-z0-9]+)*)*$";

const CATALOG_DESCRIPTION: &str =
    "The schema_version 2 map catalog: one schema, a set of skins, named cell-set regions with drawable \
     boundaries, and digest-pinned per-band cell indices. A consumer prices a selection from this document \
     alone — total bytes and bytes per band, which is the per-file projection a volume set needs — and \
     verifies each satellite against the `bytes` + `sha256` pinned here. The satellite documents are \
     `$defs/CellIndexDocument`, `$defs/RegionCellsDocument` and `$defs/TerrainIndexDocument`. The optional \
     `terrain` block is a second artifact class on its own revision track (§13). Normative contract: \
     OBCC_Spec.md, with OBCA_Spec.md for the grid, bands, and assembly and OBCT_Spec.md for the raster.";

const BOUNDARY_DESCRIPTION: &str =
    "A region's simplified outline, in integer microdegrees, `[lat, lon]` per point. Presentation only: it \
     MUST NOT be used to compute a cell set (that is stored, §6), to price a selection, or as a packer \
     input bbox. The coverage outline a builder draws for a live selection is a different object — the union \
     of the selected cells' squares, computed client-side — and is deliberately not in the catalog.";

const TERRAIN_DESCRIPTION: &str =
    "The terrain artifact class (OBCC_Spec.md §13): an OBCT raster on the same OBCA grid, published with its \
     OWN revision track. `dataset_version`, `posting_log2`, `cell_log2` and `terrain_revision` are terrain's \
     entire lockstep rule — no OBCM version or schema revision appears here, and an OBCM or schema bump \
     invalidates none of these objects. The single reverse coupling is the root's `network_terrain_revision`, \
     which records the terrain revision the nav graph's ascents were integrated from.";

const CELL_DESCRIPTION: &str =
    "One published cell. There is deliberately no bbox: a cell's coverage is exactly its grid square, which \
     the `id` determines to the microdegree (OBCA_Spec.md §1.3), and the generator verifies the artifact's own \
     OBCM header bbox against it at bake time. A stored copy could only agree (redundant) or disagree (a lie).";

/// Generate the catalog documents' JSON Schema from the same serde model the generator
/// writes and consumers deserialize, then add the constraints Rust types cannot
/// express, and fold the two satellite documents into `$defs` so one checked-in file
/// validates all three shapes.
pub fn catalog_schema() -> Value {
    let mut schema = serde_json::to_value(schemars::schema_for!(Catalog)).expect("catalog schema serializes");
    let root = schema.as_object_mut().expect("root schema is an object");
    root.insert("$schema".into(), Value::String("https://json-schema.org/draft/2020-12/schema".into()));
    root.insert("title".into(), Value::String("OpenBikeComputer map catalog (schema_version 2)".into()));
    root.insert("description".into(), Value::String(CATALOG_DESCRIPTION.into()));
    // The satellites are separate documents, so their models are not reachable from
    // `Catalog`; generate each and merge, which also brings `CellEntry`/`CellSource`
    // into `$defs` where the root's own definitions live.
    let mut extra_defs = Map::new();
    for (name, mut doc) in [
        ("CellIndexDocument", serde_json::to_value(schemars::schema_for!(CellIndexDocument)).expect("cell index")),
        (
            "RegionCellsDocument",
            serde_json::to_value(schemars::schema_for!(RegionCellsDocument)).expect("region cells"),
        ),
        (
            "TerrainIndexDocument",
            serde_json::to_value(schemars::schema_for!(TerrainIndexDocument)).expect("terrain index"),
        ),
    ] {
        let obj = doc.as_object_mut().expect("satellite schema is an object");
        obj.remove("$schema");
        obj.remove("title");
        if let Some(Value::Object(defs)) = obj.remove("$defs") {
            for (k, v) in defs {
                extra_defs.insert(k, v);
            }
        }
        extra_defs.insert(name.to_string(), doc);
    }

    let props = root.get_mut("properties").and_then(Value::as_object_mut).expect("catalog properties");
    props["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
    props["generated_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let defs = root.get_mut("$defs").and_then(Value::as_object_mut).expect("catalog definitions");
    for (k, v) in extra_defs {
        defs.insert(k, v);
    }
    for (doc, field) in [("CellIndexDocument", "schema_revision"), ("RegionCellsDocument", "schema_revision")] {
        defs[doc]["properties"]["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
        // A satellite states the revision it belongs to; a consumer that has the root
        // compares it and rejects a mismatch rather than mixing revisions.
        defs[doc]["properties"][field]["minimum"] = Value::from(1);
    }
    defs["RegionCellsDocument"]["properties"]["region_id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    band_keyed_map(&mut defs["RegionCellsDocument"]["properties"]["cells"]);
    defs["RegionCellsDocument"]["properties"]["terrain"]["items"]["pattern"] = Value::from(CELL_ID_PATTERN);

    // The terrain artifact class (§13). Its index is the third satellite shape, in the
    // same checked-in file, and it carries no `schema_revision` at all — which is the
    // independence stated in the schema rather than only in the prose.
    let terrain_doc = defs["TerrainIndexDocument"]["properties"].as_object_mut().expect("terrain index properties");
    terrain_doc["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
    terrain_doc["terrain_revision"]["minimum"] = Value::from(1);
    terrain_doc["dataset_id"]["pattern"] = Value::from(ID_PATTERN);
    terrain_doc["dataset_version"]["minLength"] = Value::from(1);
    terrain_log2_bounds(terrain_doc);

    defs["TerrainEntry"]["description"] = Value::from(TERRAIN_DESCRIPTION);
    let terrain = defs["TerrainEntry"]["properties"].as_object_mut().expect("terrain properties");
    terrain["dataset_id"]["pattern"] = Value::from(ID_PATTERN);
    terrain["dataset_version"]["minLength"] = Value::from(1);
    terrain["attribution"]["minLength"] = Value::from(1);
    terrain["terrain_revision"]["minimum"] = Value::from(1);
    terrain_log2_bounds(terrain);

    let terrain_ref = defs["TerrainIndexRef"]["properties"].as_object_mut().expect("terrain ref properties");
    terrain_ref["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    terrain_ref["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);

    let terrain_cell = defs["TerrainCellEntry"]["properties"].as_object_mut().expect("terrain cell properties");
    terrain_cell["id"]["pattern"] = Value::from(CELL_ID_PATTERN);
    terrain_cell["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    terrain_cell["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    terrain_cell["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let terrain_empty = defs["TerrainEmptyRun"]["properties"].as_object_mut().expect("terrain empty properties");
    terrain_empty["start"]["pattern"] = Value::from(CELL_ID_PATTERN);
    terrain_empty["end"]["pattern"] = Value::from(CELL_ID_PATTERN);
    terrain_empty["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let schema_entry = defs["SchemaEntry"]["properties"].as_object_mut().expect("schema properties");
    schema_entry["id"]["pattern"] = Value::from(ID_PATTERN);
    schema_entry["name"]["minLength"] = Value::from(1);
    schema_entry["description"]["minLength"] = Value::from(1);
    schema_entry["revision"]["minimum"] = Value::from(1);
    schema_entry["lods"]["minItems"] = Value::from(1);
    schema_entry["bands"]["minItems"] = Value::from(1);
    schema_entry["styles"]["minItems"] = Value::from(1);

    defs["GridEntry"]["properties"]["origin_udeg"]["const"] = Value::from(GRID_ORIGIN_UDEG);
    defs["GridEntry"]["properties"]["world_side_udeg"]["const"] = Value::from(WORLD_SIDE_UDEG);

    let band = defs["BandEntry"]["properties"].as_object_mut().expect("band properties");
    band["id"]["pattern"] = Value::from(ID_PATTERN);
    band["cell_log2"]["minimum"] = Value::from(MIN_CELL_LOG2);
    band["cell_log2"]["maximum"] = Value::from(MAX_CELL_LOG2);

    defs["LodEntry"]["properties"]["band"]["pattern"] = Value::from(ID_PATTERN);
    defs["StyleAssignment"]["properties"]["feature_type"]["minLength"] = Value::from(1);
    defs["StyleAssignment"]["properties"]["id"]["minimum"] = Value::from(1);

    let skin = defs["SkinEntry"]["properties"].as_object_mut().expect("skin properties");
    skin["id"]["pattern"] = Value::from(ID_PATTERN);
    skin["name"]["minLength"] = Value::from(1);
    skin["description"]["minLength"] = Value::from(1);
    skin["styles"]["minItems"] = Value::from(1);
    let preview = defs["SkinPreview"]["properties"].as_object_mut().expect("preview properties");
    preview["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    preview["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    defs["SkinStyle"]["properties"]["feature_type"]["minLength"] = Value::from(1);
    defs["SkinStyle"]["properties"]["priority"]["minimum"] = Value::from(1);
    defs["SkinStyle"]["properties"]["priority"]["maximum"] = Value::from(4);

    let region = defs["RegionEntry"]["properties"].as_object_mut().expect("region properties");
    region["id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    region["name"]["minLength"] = Value::from(1);
    region["cells_sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    region["cells_url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["bytes_by_band"]);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["cell_count"]);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["partial_cell_count_by_band"]);

    defs["Boundary"]["description"] = Value::from(BOUNDARY_DESCRIPTION);
    defs["Boundary"]["properties"]["rings"]["minItems"] = Value::from(1);
    // A closed ring: 3 distinct points plus the repeat of the first.
    defs["Boundary"]["properties"]["rings"]["items"]["minItems"] = Value::from(4);

    let cell_ref = defs["CellIndexRef"]["properties"].as_object_mut().expect("cell index ref properties");
    cell_ref["band"]["pattern"] = Value::from(ID_PATTERN);
    cell_ref["cell_log2"]["minimum"] = Value::from(MIN_CELL_LOG2);
    cell_ref["cell_log2"]["maximum"] = Value::from(MAX_CELL_LOG2);
    cell_ref["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    cell_ref["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);

    let empty = defs["KnownEmptyRun"]["properties"].as_object_mut().expect("known-empty properties");
    empty["start"]["pattern"] = Value::from(CELL_ID_PATTERN);
    empty["end"]["pattern"] = Value::from(CELL_ID_PATTERN);
    empty["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);
    empty["sources"]["minItems"] = Value::from(1);

    defs["CellEntry"]["description"] = Value::from(CELL_DESCRIPTION);
    let cell = defs["CellEntry"]["properties"].as_object_mut().expect("cell properties");
    cell["id"]["pattern"] = Value::from(CELL_ID_PATTERN);
    cell["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    cell["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    cell["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);
    cell["sources"]["minItems"] = Value::from(1);

    defs["CellSource"]["properties"]["extract_id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    defs["CellSource"]["properties"]["snapshot"]["pattern"] = Value::from(DATE_PATTERN);

    flatten_descriptions(&mut schema);
    schema
}

/// Band-keyed object: the keys are band ids, so give them the id grammar rather than
/// letting any string through.
fn band_keyed_map(value: &mut Value) {
    value["propertyNames"] = serde_json::json!({ "pattern": ID_PATTERN });
}

/// The OBCT lattice bounds (`OBCT_Spec.md` §1.1, §3.1), applied wherever the pairing
/// is published. They are the format's, not the OBCM grid's, which is why they come
/// from `obc_formats::obct` rather than from this module's `MIN_CELL_LOG2`.
fn terrain_log2_bounds(properties: &mut Map<String, Value>) {
    properties["posting_log2"]["minimum"] = Value::from(obct::MIN_POSTING_LOG2);
    properties["posting_log2"]["maximum"] = Value::from(obct::MAX_POSTING_LOG2);
    properties["cell_log2"]["minimum"] = Value::from(obct::MIN_CELL_LOG2);
    properties["cell_log2"]["maximum"] = Value::from(obct::MAX_CELL_LOG2);
}

/// Stable pretty representation used to regenerate the checked-in schema:
/// `obc-pack schema --catalog > host/obc-pack/schema/catalog.schema.json`.
pub fn catalog_schema_json() -> String {
    let mut text = serde_json::to_string_pretty(&catalog_schema()).expect("catalog schema serializes");
    text.push('\n');
    text
}
