//! Catalog tree schema/skin validation, JSON Schema generation, and wire examples.
//!
//! The serde/schemars DTOs live in `model`; this module owns the producer's schema
//! and skin inputs plus the extra wire constraints Rust types cannot express.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use serde::Deserialize;
use serde_json::{Map, Value};

use obc_formats::obct;

use crate::config::{Config, LineStyle};
use crate::grid::{MAX_CELL_LOG2, MIN_CELL_LOG2};

use super::model::{
    BandEntry, BandRole, BandSection, Catalog, CellIndexDocument, LodEntry, RegionCellsDocument, RoutingEntry,
    SkinEntry, SkinPreview, SkinStyle, StyleAssignment, TerrainIndexDocument, GRID_ORIGIN_UDEG, WORLD_SIDE_UDEG,
};
use super::validate::validate_id;
use super::{
    content_addressed_rel_path, file_name, hash_file, sorted_entries, PinnedArtifact, CATALOG_SCHEMA_VERSION,
    PREVIEWS_DIR, SCHEMA_DOC, SKINS_DIR, TERRAIN_DIR,
};

/// The generated JSON Schema for the catalog documents, checked in so a consumer can
/// validate a fetched catalog — root *and* satellites — without a Rust toolchain.
pub const CATALOG_SCHEMA_JSON: &str = include_str!("../../schema/catalog.schema.json");

/// Worked example of the catalog **root**, regenerated by this module's tests from the
/// synthetic tree in `tests::example_tree`.
pub const CATALOG_EXAMPLE_JSON: &str = include_str!("../../schema/catalog.example.json");

/// Worked example of a **cell index** satellite (§8).
pub const CELL_INDEX_EXAMPLE_JSON: &str = include_str!("../../schema/cell-index.example.json");

/// Worked example of a **region cell list** satellite (§6).
pub const REGION_CELLS_EXAMPLE_JSON: &str = include_str!("../../schema/region-cells.example.json");

/// Worked example of the **terrain cell index** satellite (§13).
pub const TERRAIN_INDEX_EXAMPLE_JSON: &str = include_str!("../../schema/terrain-index.example.json");

fn flatten_descriptions(value: &mut Value) {
    match value {
        Value::Object(map) => {
            if let Some(Value::String(description)) = map.get_mut("description") {
                *description = description.split_whitespace().collect::<Vec<_>>().join(" ");
            }
            for nested in map.values_mut() {
                flatten_descriptions(nested);
            }
        }
        Value::Array(items) => items.iter_mut().for_each(flatten_descriptions),
        _ => {}
    }
}

// --- schema -------------------------------------------------------------------------------

pub(super) const CELL_ID_PATTERN: &str = r"^\d{1,2}/\d{4,}/\d{4,}$";
pub(super) const SHA256_PATTERN: &str = "^[0-9a-f]{64}$";
pub(super) const PINNED_URL_PATTERN: &str = r"^(https?://|/).+\.[0-9a-f]{64}\.[^/?#]+$";
const DATE_PATTERN: &str = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$";
pub(super) const TIMESTAMP_PATTERN: &str = "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$";
pub(super) const ID_PATTERN: &str = "^[a-z0-9]+(-[a-z0-9]+)*$";
const REGION_ID_PATTERN: &str = "^[a-z0-9]+(-[a-z0-9]+)*(/[a-z0-9]+(-[a-z0-9]+)*)*$";

const CATALOG_DESCRIPTION: &str =
    "The schema_version 2 map catalog: one schema, a set of skins, named cell-set regions with drawable \
     boundaries, and digest-pinned per-band cell indices. A consumer prices a selection from this document \
     alone — total bytes and bytes per band, which is the per-file projection a volume set needs — and \
     verifies each satellite against the `bytes` + `sha256` pinned here. The satellite documents are \
     `$defs/CellIndexDocument`, `$defs/RegionCellsDocument` and `$defs/TerrainIndexDocument`. The optional \
     `terrain` block is a second artifact class on its own revision track (§13). Normative contract: \
     OBCC_Spec.md, with OBCA_Spec.md for the grid, bands, and assembly and OBCT_Spec.md for the raster.";

const BOUNDARY_DESCRIPTION: &str =
    "A region's simplified outline, in integer microdegrees, `[lat, lon]` per point. Presentation only: it \
     MUST NOT be used to compute a cell set (that is stored, §6), to price a selection, or as a packer \
     input bbox. The coverage outline a builder draws for a live selection is a different object — the union \
     of the selected cells' squares, computed client-side — and is deliberately not in the catalog.";

const TERRAIN_DESCRIPTION: &str =
    "The terrain artifact class (OBCC_Spec.md §13): an OBCT raster on the same OBCA grid, published with its \
     OWN revision track. `dataset_version`, `posting_log2`, `cell_log2` and `terrain_revision` are terrain's \
     entire lockstep rule — no OBCM version or schema revision appears here, and an OBCM or schema bump \
     invalidates none of these objects. The single reverse coupling is the root's `network_terrain_revision`, \
     which records the terrain revision the nav graph's ascents were integrated from.";

const CELL_DESCRIPTION: &str =
    "One published cell. There is deliberately no bbox: a cell's coverage is exactly its grid square, which \
     the `id` determines to the microdegree (OBCA_Spec.md §1.3), and the generator verifies the artifact's own \
     OBCM header bbox against it at bake time. A stored copy could only agree (redundant) or disagree (a lie).";

/// Generate the catalog documents' JSON Schema from the same serde model the generator
/// writes and consumers deserialize, then add the constraints Rust types cannot
/// express, and fold the two satellite documents into `$defs` so one checked-in file
/// validates all three shapes.
pub fn catalog_schema() -> Value {
    let mut schema = serde_json::to_value(schemars::schema_for!(Catalog)).expect("catalog schema serializes");
    let root = schema.as_object_mut().expect("root schema is an object");
    root.insert("$schema".into(), Value::String("https://json-schema.org/draft/2020-12/schema".into()));
    root.insert("title".into(), Value::String("OpenBikeComputer map catalog (schema_version 2)".into()));
    root.insert("description".into(), Value::String(CATALOG_DESCRIPTION.into()));
    // The satellites are separate documents, so their models are not reachable from
    // `Catalog`; generate each and merge, which also brings `CellEntry`/`CellSource`
    // into `$defs` where the root's own definitions live.
    let mut extra_defs = Map::new();
    for (name, mut doc) in [
        ("CellIndexDocument", serde_json::to_value(schemars::schema_for!(CellIndexDocument)).expect("cell index")),
        (
            "RegionCellsDocument",
            serde_json::to_value(schemars::schema_for!(RegionCellsDocument)).expect("region cells"),
        ),
        (
            "TerrainIndexDocument",
            serde_json::to_value(schemars::schema_for!(TerrainIndexDocument)).expect("terrain index"),
        ),
    ] {
        let obj = doc.as_object_mut().expect("satellite schema is an object");
        obj.remove("$schema");
        obj.remove("title");
        if let Some(Value::Object(defs)) = obj.remove("$defs") {
            for (k, v) in defs {
                extra_defs.insert(k, v);
            }
        }
        extra_defs.insert(name.to_string(), doc);
    }

    let props = root.get_mut("properties").and_then(Value::as_object_mut).expect("catalog properties");
    props["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
    props["generated_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let defs = root.get_mut("$defs").and_then(Value::as_object_mut).expect("catalog definitions");
    for (k, v) in extra_defs {
        defs.insert(k, v);
    }
    for (doc, field) in [("CellIndexDocument", "schema_revision"), ("RegionCellsDocument", "schema_revision")] {
        defs[doc]["properties"]["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
        // A satellite states the revision it belongs to; a consumer that has the root
        // compares it and rejects a mismatch rather than mixing revisions.
        defs[doc]["properties"][field]["minimum"] = Value::from(1);
    }
    defs["RegionCellsDocument"]["properties"]["region_id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    band_keyed_map(&mut defs["RegionCellsDocument"]["properties"]["cells"]);
    defs["RegionCellsDocument"]["properties"]["terrain"]["items"]["pattern"] = Value::from(CELL_ID_PATTERN);

    // The terrain artifact class (§13). Its index is the third satellite shape, in the
    // same checked-in file, and it carries no `schema_revision` at all — which is the
    // independence stated in the schema rather than only in the prose.
    let terrain_doc = defs["TerrainIndexDocument"]["properties"].as_object_mut().expect("terrain index properties");
    terrain_doc["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
    terrain_doc["terrain_revision"]["minimum"] = Value::from(1);
    terrain_doc["dataset_id"]["pattern"] = Value::from(ID_PATTERN);
    terrain_doc["dataset_version"]["minLength"] = Value::from(1);
    terrain_log2_bounds(terrain_doc);

    defs["TerrainEntry"]["description"] = Value::from(TERRAIN_DESCRIPTION);
    let terrain = defs["TerrainEntry"]["properties"].as_object_mut().expect("terrain properties");
    terrain["dataset_id"]["pattern"] = Value::from(ID_PATTERN);
    terrain["dataset_version"]["minLength"] = Value::from(1);
    terrain["attribution"]["minLength"] = Value::from(1);
    terrain["terrain_revision"]["minimum"] = Value::from(1);
    terrain_log2_bounds(terrain);

    let terrain_ref = defs["TerrainIndexRef"]["properties"].as_object_mut().expect("terrain ref properties");
    terrain_ref["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    terrain_ref["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);

    let terrain_cell = defs["TerrainCellEntry"]["properties"].as_object_mut().expect("terrain cell properties");
    terrain_cell["id"]["pattern"] = Value::from(CELL_ID_PATTERN);
    terrain_cell["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    terrain_cell["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    terrain_cell["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let terrain_empty = defs["TerrainEmptyRun"]["properties"].as_object_mut().expect("terrain empty properties");
    terrain_empty["start"]["pattern"] = Value::from(CELL_ID_PATTERN);
    terrain_empty["end"]["pattern"] = Value::from(CELL_ID_PATTERN);
    terrain_empty["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let schema_entry = defs["SchemaEntry"]["properties"].as_object_mut().expect("schema properties");
    schema_entry["id"]["pattern"] = Value::from(ID_PATTERN);
    schema_entry["name"]["minLength"] = Value::from(1);
    schema_entry["description"]["minLength"] = Value::from(1);
    schema_entry["revision"]["minimum"] = Value::from(1);
    schema_entry["lods"]["minItems"] = Value::from(1);
    schema_entry["bands"]["minItems"] = Value::from(1);
    schema_entry["styles"]["minItems"] = Value::from(1);

    defs["GridEntry"]["properties"]["origin_udeg"]["const"] = Value::from(GRID_ORIGIN_UDEG);
    defs["GridEntry"]["properties"]["world_side_udeg"]["const"] = Value::from(WORLD_SIDE_UDEG);

    let band = defs["BandEntry"]["properties"].as_object_mut().expect("band properties");
    band["id"]["pattern"] = Value::from(ID_PATTERN);
    band["cell_log2"]["minimum"] = Value::from(MIN_CELL_LOG2);
    band["cell_log2"]["maximum"] = Value::from(MAX_CELL_LOG2);

    defs["LodEntry"]["properties"]["band"]["pattern"] = Value::from(ID_PATTERN);
    defs["StyleAssignment"]["properties"]["feature_type"]["minLength"] = Value::from(1);
    defs["StyleAssignment"]["properties"]["id"]["minimum"] = Value::from(1);

    let skin = defs["SkinEntry"]["properties"].as_object_mut().expect("skin properties");
    skin["id"]["pattern"] = Value::from(ID_PATTERN);
    skin["name"]["minLength"] = Value::from(1);
    skin["description"]["minLength"] = Value::from(1);
    skin["styles"]["minItems"] = Value::from(1);
    let preview = defs["SkinPreview"]["properties"].as_object_mut().expect("preview properties");
    preview["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    preview["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    defs["SkinStyle"]["properties"]["feature_type"]["minLength"] = Value::from(1);
    defs["SkinStyle"]["properties"]["priority"]["minimum"] = Value::from(1);
    defs["SkinStyle"]["properties"]["priority"]["maximum"] = Value::from(4);

    let region = defs["RegionEntry"]["properties"].as_object_mut().expect("region properties");
    region["id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    region["name"]["minLength"] = Value::from(1);
    region["cells_sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    region["cells_url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["bytes_by_band"]);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["cell_count"]);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["partial_cell_count_by_band"]);

    defs["Boundary"]["description"] = Value::from(BOUNDARY_DESCRIPTION);
    defs["Boundary"]["properties"]["rings"]["minItems"] = Value::from(1);
    // A closed ring: 3 distinct points plus the repeat of the first.
    defs["Boundary"]["properties"]["rings"]["items"]["minItems"] = Value::from(4);

    let cell_ref = defs["CellIndexRef"]["properties"].as_object_mut().expect("cell index ref properties");
    cell_ref["band"]["pattern"] = Value::from(ID_PATTERN);
    cell_ref["cell_log2"]["minimum"] = Value::from(MIN_CELL_LOG2);
    cell_ref["cell_log2"]["maximum"] = Value::from(MAX_CELL_LOG2);
    cell_ref["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    cell_ref["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);

    let empty = defs["KnownEmptyRun"]["properties"].as_object_mut().expect("known-empty properties");
    empty["start"]["pattern"] = Value::from(CELL_ID_PATTERN);
    empty["end"]["pattern"] = Value::from(CELL_ID_PATTERN);
    empty["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);
    empty["sources"]["minItems"] = Value::from(1);

    defs["CellEntry"]["description"] = Value::from(CELL_DESCRIPTION);
    let cell = defs["CellEntry"]["properties"].as_object_mut().expect("cell properties");
    cell["id"]["pattern"] = Value::from(CELL_ID_PATTERN);
    cell["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    cell["url"]["pattern"] = Value::from(PINNED_URL_PATTERN);
    cell["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);
    cell["sources"]["minItems"] = Value::from(1);

    defs["CellSource"]["properties"]["extract_id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    defs["CellSource"]["properties"]["snapshot"]["pattern"] = Value::from(DATE_PATTERN);

    flatten_descriptions(&mut schema);
    schema
}

/// Band-keyed object: the keys are band ids, so give them the id grammar rather than
/// letting any string through.
fn band_keyed_map(value: &mut Value) {
    value["propertyNames"] = serde_json::json!({ "pattern": ID_PATTERN });
}

/// The OBCT lattice bounds (`OBCT_Spec.md` §1.1, §3.1), applied wherever the pairing
/// is published. They are the format's, not the OBCM grid's, which is why they come
/// from `obc_formats::obct` rather than from this module's `MIN_CELL_LOG2`.
fn terrain_log2_bounds(properties: &mut Map<String, Value>) {
    properties["posting_log2"]["minimum"] = Value::from(obct::MIN_POSTING_LOG2);
    properties["posting_log2"]["maximum"] = Value::from(obct::MAX_POSTING_LOG2);
    properties["cell_log2"]["minimum"] = Value::from(obct::MIN_CELL_LOG2);
    properties["cell_log2"]["maximum"] = Value::from(obct::MAX_CELL_LOG2);
}

/// Stable pretty representation used to regenerate the checked-in schema:
/// `obc-pack schema --catalog > host/obc-pack/schema/catalog.schema.json`.
pub fn catalog_schema_json() -> String {
    let mut text = serde_json::to_string_pretty(&catalog_schema()).expect("catalog schema serializes");
    text.push('\n');
    text
}

// --- tree schema and skins ----------------------------------------------------------------

/// The schema as the tree states it: the packer config the cells were baked with,
/// whose `_meta` adds the revision and the band table.
///
/// One document rather than two because the parts must not be able to disagree: the
/// style-id assignment, the LOD ladder, `chunk_size` and the routing table are read
/// out of the very config that produced the cells' bytes, not out of a hand-written
/// description of it.
pub(super) struct SchemaDoc {
    pub(super) id: String,
    pub(super) revision: u32,
    pub(super) name: String,
    pub(super) description: String,
    pub(super) lods: Vec<LodEntry>,
    pub(super) bands: Vec<BandEntry>,
    pub(super) styles: Vec<StyleAssignment>,
    pub(super) routing: RoutingEntry,
    pub(super) chunk_size: u32,
    /// Feature type → its style values, for checking a skin covers exactly this set.
    pub(super) feature_types: BTreeMap<String, u8>,
}

#[derive(Debug, Deserialize)]
struct SchemaMetaDoc {
    #[serde(rename = "_meta")]
    meta: Option<SchemaMeta>,
}

#[derive(Debug, Deserialize)]
struct SchemaMeta {
    id: String,
    name: String,
    description: String,
    /// The cell store's identity. Bumping it invalidates every cell
    /// (`OBCA_Spec.md` §6.3), which is why it is stated here and recorded in every
    /// cell sidecar: the generator can then refuse a tree that mixes revisions.
    revision: u32,
    bands: Vec<BandDoc>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BandDoc {
    id: String,
    cell_log2: u8,
    #[serde(default)]
    lods: Vec<u32>,
    #[serde(default)]
    sections: Vec<BandSection>,
    role: BandRole,
}

pub(super) fn read_schema_doc(path: &Path) -> Result<SchemaDoc, String> {
    let text = std::fs::read_to_string(path).map_err(|e| {
        format!(
            "{}: {e} — a bake tree's `{SCHEMA_DOC}` is the packer config its cells were baked with, plus a `_meta` \
             block carrying `revision` and `bands`",
            path.display()
        )
    })?;
    let doc: SchemaMetaDoc = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
    let meta = doc
        .meta
        .ok_or_else(|| format!("{}: no `_meta` block (id, name, description, revision, bands)", path.display()))?;
    validate_id(&meta.id).map_err(|e| format!("{}: schema id {e}", path.display()))?;
    if meta.name.trim().is_empty() || meta.description.trim().is_empty() {
        return Err(format!("{}: `_meta.name` and `_meta.description` must be non-empty", path.display()));
    }
    if meta.revision == 0 {
        return Err(format!("{}: `_meta.revision` starts at 1 — a cell store has no revision zero", path.display()));
    }

    let config = Config::parse(&text).map_err(|e| format!("{}: {e}", path.display()))?;
    let bands = check_band_table(&meta.bands, config.lods.len(), path)?;
    let lods = ladder(&config, &bands, path)?;
    let (styles, feature_types) = style_assignment(&config, path)?;

    Ok(SchemaDoc {
        id: meta.id,
        revision: meta.revision,
        name: meta.name,
        description: meta.description,
        lods,
        bands,
        styles,
        routing: RoutingEntry {
            min_component_edges: config.routing.min_component_edges as u32,
            profiles: config.routing.profiles.iter().map(|p| p.name.clone()).collect(),
        },
        chunk_size: config.chunk_size as u32,
        feature_types,
    })
}

/// The band table's rules (§4, `OBCA_Spec.md` §1.2/§5.1), all of which a consumer
/// must reject and which therefore must not be publishable in the first place:
/// every ladder LOD in exactly one band, the nav and POI sections in exactly one
/// band, exactly one `core` band carrying the sections and no LOD, at most one
/// `coarse` band, everything else `geometry`.
fn check_band_table(bands: &[BandDoc], lod_count: usize, path: &Path) -> Result<Vec<BandEntry>, String> {
    let at = || path.display().to_string();
    if bands.is_empty() {
        return Err(format!("{}: `_meta.bands` is empty — a cell store needs a band table", at()));
    }
    let mut ids = BTreeSet::new();
    let mut lod_owner: BTreeMap<u32, &str> = BTreeMap::new();
    let mut section_owner: BTreeMap<BandSection, &str> = BTreeMap::new();
    let mut cores = Vec::new();
    let mut coarses = Vec::new();
    let mut out = Vec::new();
    for band in bands {
        validate_id(&band.id).map_err(|e| format!("{}: band id {e}", at()))?;
        if band.id == TERRAIN_DIR {
            return Err(format!(
                "{}: `{TERRAIN_DIR}` is reserved — `cells/{TERRAIN_DIR}/` holds the terrain artifact class, which is \
                 on its own revision track and is not a band (OBCC_Spec.md §13.1)",
                at()
            ));
        }
        if !ids.insert(band.id.as_str()) {
            return Err(format!("{}: band `{}` is listed twice", at(), band.id));
        }
        if !(MIN_CELL_LOG2..=MAX_CELL_LOG2).contains(&u32::from(band.cell_log2)) {
            return Err(format!(
                "{}: band `{}`: cell size 2^{} µdeg is outside 2^{MIN_CELL_LOG2}..=2^{MAX_CELL_LOG2}",
                at(),
                band.id,
                band.cell_log2
            ));
        }
        let mut lods = band.lods.clone();
        lods.sort_unstable();
        lods.dedup();
        if lods.len() != band.lods.len() {
            return Err(format!("{}: band `{}` lists a LOD twice", at(), band.id));
        }
        for &lod in &lods {
            if lod as usize >= lod_count {
                return Err(format!(
                    "{}: band `{}` claims LOD {lod}, but the ladder has {lod_count} level(s)",
                    at(),
                    band.id
                ));
            }
            if let Some(other) = lod_owner.insert(lod, &band.id) {
                return Err(format!(
                    "{}: LOD {lod} is in both band `{other}` and band `{}` — it would be written twice \
                     (OBCA_Spec.md §1.2)",
                    at(),
                    band.id
                ));
            }
        }
        let mut sections = band.sections.clone();
        sections.sort_unstable();
        sections.dedup();
        if sections.len() != band.sections.len() {
            return Err(format!("{}: band `{}` lists a section twice", at(), band.id));
        }
        for &section in &sections {
            if let Some(other) = section_owner.insert(section, &band.id) {
                return Err(format!(
                    "{}: the {section:?} section is in both band `{other}` and band `{}` — it belongs to exactly one",
                    at(),
                    band.id
                ));
            }
        }
        match band.role {
            BandRole::Core => {
                cores.push(band.id.as_str());
                if !lods.is_empty() {
                    return Err(format!(
                        "{}: the `core` band `{}` carries LOD(s) {lods:?}. The core file is the one file of a volume \
                         set that cannot be split by bbox, so no geometry may live in it (OBCA_Spec.md §5.1) — its \
                         headroom under 4 GiB is the design's hard limit.",
                        at(),
                        band.id
                    ));
                }
                if sections != [BandSection::Nav, BandSection::Poi] {
                    return Err(format!(
                        "{}: the `core` band `{}` must carry both the `nav` and `poi` sections (got {sections:?})",
                        at(),
                        band.id
                    ));
                }
            }
            BandRole::Coarse | BandRole::Geometry => {
                coarses.extend(matches!(band.role, BandRole::Coarse).then_some(band.id.as_str()));
                if lods.is_empty() {
                    return Err(format!("{}: band `{}` carries no LOD and is not the `core` band", at(), band.id));
                }
                if !sections.is_empty() {
                    return Err(format!(
                        "{}: band `{}` carries {sections:?}, but only the `core` band may carry a section",
                        at(),
                        band.id
                    ));
                }
            }
        }
        out.push(BandEntry { id: band.id.clone(), cell_log2: band.cell_log2, lods, sections, role: band.role });
    }

    if cores.len() != 1 {
        return Err(format!("{}: exactly one band must have `role: core` (got {cores:?})", at()));
    }
    if coarses.len() > 1 {
        return Err(format!("{}: at most one band may have `role: coarse` (got {coarses:?})", at()));
    }
    for section in [BandSection::Nav, BandSection::Poi] {
        if !section_owner.contains_key(&section) {
            return Err(format!("{}: no band carries the {section:?} section", at()));
        }
    }
    let missing: Vec<usize> = (0..lod_count).filter(|l| !lod_owner.contains_key(&(*l as u32))).collect();
    if !missing.is_empty() {
        return Err(format!(
            "{}: ladder LOD(s) {missing:?} are in no band — a map would be blank at that zoom (OBCA_Spec.md §1.2)",
            at()
        ));
    }

    // Published in band order as authored, which is the coarse→fine reading order of
    // the table; determinism comes from the file, not from a map.
    Ok(out)
}

/// The LOD ladder as the catalog publishes it, cross-checked against `OBCM_Spec.md`
/// §3: exactly one `+inf` level and it is index 0, strictly decreasing after.
fn ladder(config: &Config, bands: &[BandEntry], path: &Path) -> Result<Vec<LodEntry>, String> {
    let mut out = Vec::with_capacity(config.lods.len());
    let mut previous: Option<f64> = None;
    for (index, lod) in config.lods.iter().enumerate() {
        match (index, lod.max_mpp) {
            (0, None) => {}
            (0, Some(mpp)) => {
                return Err(format!(
                    "{}: ladder LOD 0 has max_mpp {mpp} — the coarsest level is +inf (`null`), OBCM_Spec.md §3",
                    path.display()
                ))
            }
            (_, None) => {
                return Err(format!("{}: ladder LOD {index} is +inf; only LOD 0 may be", path.display()));
            }
            (_, Some(mpp)) => {
                if let Some(prev) = previous {
                    if mpp >= prev {
                        return Err(format!(
                            "{}: ladder max_mpp must strictly decrease ({prev} then {mpp} at LOD {index})",
                            path.display()
                        ));
                    }
                }
                previous = Some(mpp);
            }
        }
        let band = bands
            .iter()
            .find(|b| b.lods.contains(&(index as u32)))
            .expect("check_band_table proved every LOD has a band");
        out.push(LodEntry { index: index as u32, max_mpp: lod.max_mpp, band: band.id.clone() });
    }
    Ok(out)
}

/// The canonical style-id assignment, read out of the config that assigned it —
/// [`feature_type_ids`], plus the duplicate-id check and the id-keyed view of it.
///
/// Returned sorted by id, which is also the order a style table is written in
/// (`OBCM_Spec.md` §2) and the order a skin's entries follow.
fn style_assignment(config: &Config, path: &Path) -> Result<(Vec<StyleAssignment>, BTreeMap<String, u8>), String> {
    let by_type = feature_type_ids(config);
    if by_type.is_empty() {
        return Err(format!("{}: no feature types — a schema with no styles draws nothing", path.display()));
    }
    // The same assignment read the other way round, which is also where a collision
    // shows up: two feature types on one id would make the published style table
    // ambiguous about which one a chunk's feature header meant.
    let mut by_id: BTreeMap<u8, String> = BTreeMap::new();
    for (feature_type, &id) in &by_type {
        if let Some(other) = by_id.insert(id, feature_type.clone()) {
            return Err(format!(
                "{}: style id {id} is assigned to both `{other}` and `{feature_type}`",
                path.display()
            ));
        }
    }
    let styles = by_id.into_iter().map(|(id, feature_type)| StyleAssignment { id, feature_type }).collect();
    Ok((styles, by_type))
}

/// A config's `feature_type → style id` assignment: `highway.primary → 3`, and so on
/// for every `(tag key, tag value)` pair it styles.
///
/// Public because it is the thing a **producer** has to agree with this generator
/// about. `obc-pack` numbers feature types 1-based in config document order and those
/// ids are referenced by every feature header in every chunk (`OBCM_Spec.md` §5.2), so
/// the assignment is part of the cells' bytes.
///
/// The one place this walk lives: [`style_assignment`] and [`check_skin`] both read
/// the assignment through here, so the generator and the producer-side check cannot
/// come to disagree about what a config assigns.
pub(super) fn feature_type_ids(config: &Config) -> BTreeMap<String, u8> {
    let mut by_type = BTreeMap::new();
    for (tag_key, values) in &config.features {
        for (tag_value, style) in values {
            by_type.insert(format!("{tag_key}.{tag_value}"), style.id);
        }
    }
    by_type
}

/// Prove a config **is a skin over** `schema`: same feature types, same style ids
/// (`OBCC_Spec.md` §5, `OBCA_Spec.md` §4.7).
///
/// This is the check [`generate`](super::generate) applies to every document in a tree's `skins/`, and
/// it is public so a producer can apply the *same* one before it spends hours cutting
/// cells a skin turns out not to fit. A skin may change only the presentation values
/// of a style record: introducing, dropping, reordering or renumbering a feature type
/// is a new schema and therefore a re-bake, because those ids are already baked into
/// every chunk of every cell.
pub(super) fn check_skin(schema: &Config, skin: &Config) -> Result<(), String> {
    check_skin_ids(&feature_type_ids(schema), &feature_type_ids(skin))
}

/// The presentation-only keys a style record in a skin may carry (`OBCC_Spec.md`
/// §5). Everything else in a packer config decides which bytes get written, and a
/// skin is stamped onto bytes that already exist.
/// `fixed_width` and `terrain_layer` (#1095) are on the list for the same reason `line_style` is:
/// they are **flag bits of the 8-byte style record**, which is precisely the ≈ 2 KB a skin stamps.
/// Neither decides which bytes get written — a contour is cut into the same cells whether it later
/// draws hairline or ramped — so both restyle without a re-bake.
const SKIN_STYLE_KEYS: &[&str] =
    &["color", "color2", "weight", "z_index", "priority", "line_style", "fixed_width", "terrain_layer"];

/// Prove a skin **document** is presentation only: no schema keys, at either level.
///
/// [`check_skin`] compares two parsed [`Config`]s and therefore cannot see this at
/// all — by the time a config exists, a missing `lods` and a `lods` restating the
/// defaults are the same value, so a skin carrying a whole LOD ladder parses into
/// something that looks exactly like a skin that carries none. The keys have to be
/// caught in the JSON, before that information is thrown away.
///
/// Silently dropping them would be the worse failure: a skin is stamped onto cells
/// that were cut at the *schema's* ladder, tolerances, merge passes and routing table,
/// so a skin that thinks it changes any of those is a document whose author believes
/// something false. The values would have no effect, the author would have no way to
/// find that out, and the map would quietly not be the one they wrote. That is a new
/// schema revision and a re-bake (epic #1016 D2), and the error says so — naming every
/// offending key rather than the first, so one edit fixes the document.
///
/// `min_lod` is in the list for the same reason `lods` is: it decides the level a
/// feature is first written at, which is a decision already baked into every cell.
pub(super) fn check_skin_document(json: &str, at: &str) -> Result<(), String> {
    let doc: serde_json::Value = serde_json::from_str(json).map_err(|e| format!("{at}: {e}"))?;
    let obj = doc.as_object().ok_or_else(|| format!("{at}: a skin document is a JSON object"))?;

    let mut offenders: Vec<String> = obj
        .keys()
        .filter(|k| !matches!(k.as_str(), "_meta" | "features" | "marker"))
        .map(|k| format!("`{k}`"))
        .collect();
    // `min_lod` hides one level down, per style record, and is the one a hand-written
    // skin picks up most easily — it is on nearly every line of the schema it was
    // copied from.
    let mut culled: BTreeSet<&str> = BTreeSet::new();
    if let Some(features) = obj.get("features").and_then(serde_json::Value::as_object) {
        for values in features.values().filter_map(serde_json::Value::as_object) {
            for style in values.values().filter_map(serde_json::Value::as_object) {
                for key in style.keys() {
                    if !SKIN_STYLE_KEYS.contains(&key.as_str()) {
                        culled.insert(key.as_str());
                    }
                }
            }
        }
    }
    offenders.extend(culled.into_iter().map(|k| format!("`features.*.*.{k}`")));

    if offenders.is_empty() {
        return Ok(());
    }
    Err(format!(
        "{at}: a skin is presentation only, and this one carries schema key(s): {}. A skin is stamped onto cells \
         already cut at the schema's ladder, tolerances, merge passes and routing table, so these would have no \
         effect — changing any of them is a new schema revision and a re-bake (OBCC_Spec.md §5). Remove them; a \
         style record may carry {}.",
        offenders.join(", "),
        SKIN_STYLE_KEYS.iter().map(|k| format!("`{k}`")).collect::<Vec<_>>().join(", ")
    ))
}

/// [`check_skin`] against the assignments themselves, so the generator can reuse it
/// with the one it already read out of the tree's `schema.json`.
fn check_skin_ids(want: &BTreeMap<String, u8>, have: &BTreeMap<String, u8>) -> Result<(), String> {
    let unknown: Vec<&str> = have.keys().filter(|t| !want.contains_key(*t)).map(String::as_str).collect();
    if !unknown.is_empty() {
        return Err(format!(
            "this skin styles feature type(s) the schema does not have: {}. A skin is a recolor of one schema — a new \
             feature type is a new schema revision and a re-bake.",
            joined(unknown.into_iter())
        ));
    }
    let missing: Vec<&str> = want.keys().filter(|t| !have.contains_key(*t)).map(String::as_str).collect();
    if !missing.is_empty() {
        return Err(format!(
            "this skin has no style for {}. A missing style would ship a map with an invisible layer \
             (OBCC_Spec.md §5).",
            joined(missing.into_iter())
        ));
    }
    let renumbered: Vec<String> = have
        .iter()
        .filter(|(feature_type, id)| want[*feature_type] != **id)
        .map(|(feature_type, id)| format!("`{feature_type}` is id {id} here but {} in the schema", want[feature_type]))
        .collect();
    if !renumbered.is_empty() {
        return Err(format!(
            "a skin MUST NOT renumber style ids — every feature header in every baked chunk references them \
             (OBCA_Spec.md §4.7): {}",
            renumbered.join("; ")
        ));
    }
    Ok(())
}

// --- skins --------------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct SkinMetaDoc {
    #[serde(rename = "_meta")]
    meta: Option<SkinMeta>,
}

#[derive(Debug, Deserialize)]
struct SkinMeta {
    id: String,
    name: String,
    description: String,
    version: u32,
}

pub(super) fn read_skins(
    dir: &Path,
    previews_dir: &Path,
    schema: &SchemaDoc,
    base_url: &str,
) -> Result<(Vec<SkinEntry>, Vec<PinnedArtifact>), String> {
    if !dir.is_dir() {
        return Err(format!("{}: no `{SKINS_DIR}/` directory — a catalog offers at least one skin", dir.display()));
    }
    let mut skins = Vec::new();
    let mut pinned_artifacts = Vec::new();
    for path in sorted_entries(dir)? {
        let name = file_name(&path)?;
        if name.starts_with('.') || path.is_dir() {
            continue;
        }
        let Some(stem) = name.strip_suffix(".json") else {
            return Err(format!("{}: only `<skin_id>.json` skin configs belong in `{SKINS_DIR}/`", path.display()));
        };
        validate_id(stem).map_err(|e| format!("{}: skin id {e}", path.display()))?;
        let text = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        let doc: SkinMetaDoc = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
        let meta =
            doc.meta.ok_or_else(|| format!("{}: no `_meta` block (id, name, description, version)", path.display()))?;
        if meta.id != stem {
            return Err(format!("{}: `_meta.id` is `{}` but the filename says `{stem}`", path.display(), meta.id));
        }
        if meta.name.trim().is_empty() || meta.description.trim().is_empty() {
            return Err(format!("{}: `_meta.name` and `_meta.description` must be non-empty", path.display()));
        }
        check_skin_document(&text, &path.display().to_string())?;
        let config = Config::parse(&text).map_err(|e| format!("{}: {e}", path.display()))?;
        let styles = skin_styles(&config, schema, &path)?;
        let preview_path = previews_dir.join(format!("{}.png", meta.id));
        let preview = if preview_path.exists() {
            let (bytes, sha256) = hash_file(&preview_path)?;
            let rel_path = format!("{PREVIEWS_DIR}/{}.png", meta.id);
            let published_rel_path = content_addressed_rel_path(&rel_path, &sha256);
            let url = format!("{base_url}/{published_rel_path}");
            pinned_artifacts.push(PinnedArtifact { rel_path, published_rel_path, bytes, sha256: sha256.clone() });
            Some(SkinPreview { url, bytes, sha256 })
        } else {
            None
        };
        skins.push(SkinEntry {
            id: meta.id,
            name: meta.name,
            description: meta.description,
            version: meta.version,
            marker_color: config.marker_color,
            styles,
            preview,
        });
    }
    if skins.is_empty() {
        return Err(format!("{}: no skin configs found", dir.display()));
    }
    Ok((skins, pinned_artifacts))
}

/// A skin's style values, in the schema's id order, after [`check_skin`] has proved
/// the skin is a skin: same feature types, same ids.
pub(super) fn skin_styles(config: &Config, schema: &SchemaDoc, path: &Path) -> Result<Vec<SkinStyle>, String> {
    let mut by_type = BTreeMap::new();
    for (tag_key, values) in &config.features {
        for (tag_value, style) in values {
            by_type.insert(format!("{tag_key}.{tag_value}"), style.clone());
        }
    }
    check_skin_ids(&schema.feature_types, &feature_type_ids(config)).map_err(|e| format!("{}: {e}", path.display()))?;

    // Schema order, so `skins[].styles[k]` and `schema.styles[k]` describe the same
    // feature type without a consumer having to join on the name.
    let mut styles: Vec<SkinStyle> = by_type
        .into_iter()
        .map(|(feature_type, s)| SkinStyle {
            feature_type,
            color: s.color,
            weight: s.weight,
            z_index: s.z_index,
            priority: s.priority,
            dashed: s.line_style == LineStyle::Dashed,
            fixed_width: s.fixed_width,
            terrain_layer: s.terrain_layer,
            color2: s.color2,
        })
        .collect();
    styles.sort_by_key(|s| schema.feature_types[&s.feature_type]);
    Ok(styles)
}

fn joined<'a>(items: impl Iterator<Item = &'a str>) -> String {
    items.collect::<Vec<_>>().join(", ")
}
