//! `catalog::v2` — the **`schema_version 2` catalog**: a cell store, one schema, a
//! set of skins, and named regions that are *selections* rather than artifacts.
//! [`OBCC_Spec.md` §11`](../../../../specs/OBCC_Spec.md) is normative and this module
//! is its only sanctioned producer; the grid, band, and cell semantics it publishes
//! are [`OBCA_Spec.md`](../../../../specs/OBCA_Spec.md).
//!
//! What changes from v1 (`super`), and why each change is here rather than in a
//! consumer:
//!
//! - **Cells are the artifacts.** A cell's coverage is *exactly* its grid square, so
//!   a cell entry carries no bbox: the id determines the square to the microdegree
//!   and this generator **verifies the artifact's own header bbox equals it**
//!   (§11.6). A stored copy could only agree (redundant) or disagree (a lie).
//! - **The document is a root plus digest-pinned satellites.** DACH is thousands of
//!   cells and a planet store is far more, so the cell lists move out of the root —
//!   but each satellite is pinned by `bytes` + `sha256` from the root, which keeps
//!   v1's all-or-nothing guarantee per document instead of weakening it (§11.1).
//! - **A region stores its cell set and carries a drawable boundary.** Deriving the
//!   set from the outline would let a simplification error silently drop a fine cell
//!   — a hole in street detail — so the outline is presentation only (§11.7, §11.8).
//! - **`preset_version` is gone.** A skin is stamped onto ~2 KB at assembly time, so
//!   no artifact can lag a restyle and there is nothing for the field to say (§11.4).
//!
//! **One deliberate deviation from §11.1's illustrated object layout**, called out
//! because a reader of that section will notice it: cell paths are keyed by **band**
//! (`cells/<band>/<i>/<j>.obcm`, `cells/<band>/index.json`) rather than by
//! `<log2(S)>`. The v1 band table gives `fine` and `network` the same `2^18` cell
//! size ([`OBCA_Spec.md` §1.5](../../../../specs/OBCA_Spec.md)), so a `<log2>`-keyed
//! path is not a function of (band, cell) and the two bands' indices and artifacts
//! would collide. Every published `url` is explicit in the manifest, and the band's
//! `cell_log2` is published beside it, so nothing a consumer does depends on the
//! spelling of the path.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::path::{Path, PathBuf};

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use obc_formats::obcm::VERSION as OBCM_VERSION;

use crate::config::{Config, LineStyle};

use super::boundary;
use super::{
    file_name, flatten_descriptions, hash_file, normalize_base_url, read_obcm_header_in, rel_url_path, sorted_entries,
    validate_date, validate_id, validate_timestamp, HeaderBounds, ID_PATTERN, REGION_ID_PATTERN, TIMESTAMP_PATTERN,
};

/// This module's envelope version. A consumer implements v1, v2, or both, and MUST
/// reject a `schema_version` it does not implement (`OBCC_Spec.md` §1).
pub const CATALOG_SCHEMA_VERSION: u32 = 2;

/// The generated JSON Schema for the v2 documents, checked in so a consumer can
/// validate a fetched catalog — root *and* satellites — without a Rust toolchain.
pub const CATALOG_SCHEMA_JSON: &str = include_str!("../../schema/catalog.v2.schema.json");

/// Worked example of the v2 **root**, regenerated by this module's tests from the
/// synthetic tree in `tests::example_tree`.
pub const CATALOG_EXAMPLE_JSON: &str = include_str!("../../schema/catalog.v2.example.json");

/// Worked example of a **cell index** satellite (§11.6).
pub const CELL_INDEX_EXAMPLE_JSON: &str = include_str!("../../schema/cell-index.v2.example.json");

/// Worked example of a **region cell list** satellite (§11.7).
pub const REGION_CELLS_EXAMPLE_JSON: &str = include_str!("../../schema/region-cells.v2.example.json");

// --- the grid (OBCA_Spec.md §1) -----------------------------------------------------------

/// `GRID_ORIGIN`: the shared origin of every band and every cell size, on both axes
/// (`OBCA_Spec.md` §1.1). `−2^28` rather than `−90 000 000` because it is divisible
/// by every permitted cell size, which is what makes quadtree midpoints and cell
/// boundaries coincide.
pub const GRID_ORIGIN_UDEG: i32 = -268_435_456;

/// `WORLD_SIDE`: `2^29` µdeg. The world box (≈ ±268°) is deliberately wider than the
/// geographic domain, so a cell may overhang ±90°/±180° and MUST NOT be clamped.
pub const WORLD_SIDE_UDEG: i32 = 536_870_912;

/// Smallest permitted `log2(S)` (`OBCA_Spec.md` §1.1).
pub const MIN_CELL_LOG2: u8 = 10;

/// Largest permitted `log2(S)`.
pub const MAX_CELL_LOG2: u8 = 28;

/// A cell's identity: its size as `log2(µdeg)` and its row/column on the global grid.
///
/// The id is the coverage statement — `square` derives the cell's box from it in
/// exact integer arithmetic — which is why a catalog cell entry has no bbox and this
/// generator checks the artifact's header against the id instead (§11.6).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct CellId {
    pub log2: u8,
    pub i: u32,
    pub j: u32,
}

/// A cell's grid square, in microdegrees: `[min, min + S)` on both axes. Half-open,
/// with `max` the exclusive upper bound the OBCM header stores.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CellSquare {
    pub min_lat: i32,
    pub min_lon: i32,
    pub max_lat: i32,
    pub max_lon: i32,
}

impl CellId {
    /// Parse the canonical `<log2>/<i>/<j>` id (`OBCA_Spec.md` §1.3).
    ///
    /// Strict about the zero padding: producers MUST widen rather than truncate, so
    /// `18/1204/52` and `18/01204/1052` are *different strings for the same cell* and
    /// exactly the kind of ambiguity a content-addressed store must not have.
    pub fn parse(s: &str) -> Result<CellId, String> {
        let mut parts = s.split('/');
        let (Some(log2), Some(i), Some(j), None) = (parts.next(), parts.next(), parts.next(), parts.next()) else {
            return Err(format!("cell id `{s}` is not `<log2>/<i>/<j>`"));
        };
        if log2.is_empty() || log2.len() > 2 || !log2.bytes().all(|b| b.is_ascii_digit()) {
            return Err(format!("cell id `{s}`: `{log2}` is not a 1–2 digit cell size"));
        }
        let log2: u8 = log2.parse().map_err(|_| format!("cell id `{s}`: bad cell size"))?;
        if !(MIN_CELL_LOG2..=MAX_CELL_LOG2).contains(&log2) {
            return Err(format!(
                "cell id `{s}`: cell size 2^{log2} µdeg is outside 2^{MIN_CELL_LOG2}..=2^{MAX_CELL_LOG2}"
            ));
        }
        let width = Self::index_width(log2);
        let count = Self::grid_side(log2);
        let mut idx = [0u32; 2];
        for (slot, (text, axis)) in idx.iter_mut().zip([(i, "i"), (j, "j")]) {
            if text.len() != width || !text.bytes().all(|b| b.is_ascii_digit()) {
                return Err(format!("cell id `{s}`: `{axis}` must be {width} digits, zero-padded (got `{text}`)"));
            }
            let v: u32 = text.parse().map_err(|_| format!("cell id `{s}`: `{text}` is not a number"))?;
            if v >= count {
                return Err(format!("cell id `{s}`: `{axis}` = {v} is off the grid (0..{count})"));
            }
            *slot = v;
        }
        Ok(CellId { log2, i: idx[0], j: idx[1] })
    }

    /// Cells per axis at this size: `WORLD_SIDE / S`.
    pub fn grid_side(log2: u8) -> u32 {
        (WORLD_SIDE_UDEG as u32) >> log2
    }

    /// Zero-padding width: `max(4, decimal_width(WORLD_SIDE / S − 1))`
    /// (`OBCA_Spec.md` §1.3).
    pub fn index_width(log2: u8) -> usize {
        let last = Self::grid_side(log2) - 1;
        let digits = last.to_string().len();
        digits.max(4)
    }

    /// The half-open square this id names, in exact integer microdegrees. May
    /// overhang the geographic domain (`OBCA_Spec.md` §1.4) — that is legal and the
    /// box MUST NOT be clamped.
    pub fn square(&self) -> CellSquare {
        let side = 1i64 << self.log2;
        let min_lat = i64::from(GRID_ORIGIN_UDEG) + i64::from(self.i) * side;
        let min_lon = i64::from(GRID_ORIGIN_UDEG) + i64::from(self.j) * side;
        CellSquare {
            min_lat: min_lat as i32,
            min_lon: min_lon as i32,
            max_lat: (min_lat + side) as i32,
            max_lon: (min_lon + side) as i32,
        }
    }
}

impl fmt::Display for CellId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let w = CellId::index_width(self.log2);
        write!(f, "{}/{:0w$}/{:0w$}", self.log2, self.i, self.j, w = w)
    }
}

// --- the root document (§11.2) ------------------------------------------------------------

/// The v2 root: small, short-cached, and the only document a consumer reads before it
/// knows what the catalog offers.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct CatalogV2 {
    /// Envelope version, `2`. Checked before any other field.
    pub schema_version: u32,
    /// When this root was generated, RFC 3339 UTC — the only wall clock on the
    /// generation path (`OBCC_Spec.md` §5).
    pub generated_at: String,
    /// The catalog's **single** schema. Not an array: the hosted store carries the
    /// 7-LOD bikepacking ladder and nothing else, because a second schema would make
    /// the whole planet-shaped cell store exist twice (§11.2, epic #1016 D2).
    pub schema: SchemaEntry,
    /// Every skin offered, sorted by `id`. Inlined rather than referenced: one is
    /// ≈ 2 KB and a builder needs all of them at once to draw a picker.
    pub skins: Vec<SkinEntry>,
    /// Named selections, sorted by `id`.
    pub regions: Vec<RegionEntry>,
    /// One entry per band, sorted by `cell_log2` descending (§11.6).
    pub cell_index: Vec<CellIndexRef>,
    /// Legacy whole-region artifacts during migration (§11.9), with exactly v1 §3
    /// semantics. A v2 consumer MAY ignore it; a finished migration omits it. This
    /// generator never emits it — a v2 tree has no whole-region artifacts to
    /// describe — but the field is here because a consumer built on these types must
    /// be able to read a bakery that is still serving both.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifacts: Option<Vec<super::ArtifactEntry>>,
}

/// The schema: the identity of the cell store. Everything a consumer needs to price a
/// selection and an assembler needs to stamp a skin, with no out-of-band constant
/// (§11.3).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SchemaEntry {
    /// Stable id, e.g. `bikepacking`.
    pub id: String,
    /// Monotone content revision. Every cell states the revision it was baked at, and
    /// a bump invalidates the whole store — assembly copies chunk bytes between files,
    /// which is only meaningful within one revision (`OBCA_Spec.md` §6.3).
    pub revision: u32,
    pub name: String,
    pub description: String,
    /// OBCM format version, read from the **cells' own headers**; every cell agrees or
    /// generation fails (§11.9).
    pub obcm_version: u8,
    /// The grid's constants, restated so no consumer hard-codes them.
    pub grid: GridEntry,
    /// The LOD ladder, coarsest first.
    pub lods: Vec<LodEntry>,
    /// The band table: which LODs and which non-geometry sections live in which cell
    /// size, and which file of a volume set they assemble into.
    pub bands: Vec<BandEntry>,
    /// The canonical style-id assignment. `obc-pack` numbers feature types 1-based in
    /// config document order and every feature header in every chunk references those
    /// ids, so the assignment is part of the cells' bytes — schema data, never skin
    /// data (§11.3).
    pub styles: Vec<StyleAssignment>,
    /// Routing facts baked into the cells. The island-prune threshold is schema data:
    /// two cells pruned at different thresholds do not assemble into a graph with
    /// consistent semantics (`OBCA_Spec.md` §3.5).
    pub routing: RoutingEntry,
    /// The per-LOD chunk capacity bound the cells were written with (`OBCM_Spec.md`
    /// §3). An assembler re-checks every copied offset pair against it.
    pub chunk_size: u32,
}

/// `OBCA_Spec.md` §1.1's constants. Published so a consumer computing a cell's square
/// or an assembly bbox never hard-codes a power of two.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct GridEntry {
    /// `−2^28` µdeg, on both axes.
    pub origin_udeg: i32,
    /// `2^29` µdeg: the world box's side.
    pub world_side_udeg: i32,
}

/// One rung of the LOD ladder.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct LodEntry {
    /// Ladder index, `0` = coarsest.
    pub index: u32,
    /// Meters-per-pixel upper bound; `null` for the `+inf` coarsest level
    /// (`OBCM_Spec.md` §3).
    pub max_mpp: Option<f64>,
    /// The band whose cells carry this LOD.
    pub band: String,
}

/// Which file of a volume set a band's content assembles into
/// (`OBCA_Spec.md` §5.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum BandRole {
    /// The one unsplittable file: nav graph, POIs, style table. Carries no LOD,
    /// because its headroom under `4 GiB − 1` is the design's hard limit.
    Core,
    /// The single whole-assembly coarse shard that keeps a zoomed-out viewport a
    /// one-file read.
    Coarse,
    /// An ordinary geometry shard's content; splits by bbox as needed.
    Geometry,
}

/// A non-geometry OBCM section a band may carry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum BandSection {
    /// The navigation graph (`OBCM_Spec.md` §8).
    Nav,
    /// POIs and the hours pool (`OBCM_Spec.md` §7).
    Poi,
}

/// One band: a cell size plus the content its cells carry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct BandEntry {
    /// Stable band id, e.g. `fine`. Also the band's segment in a cell URL.
    pub id: String,
    /// `log2(S)` in µdeg.
    pub cell_log2: u8,
    /// Ladder LODs this band's cells carry, ascending. Empty for the `core` band.
    pub lods: Vec<u32>,
    /// Non-geometry sections this band's cells carry. Only the `core` band has any.
    pub sections: Vec<BandSection>,
    /// Which file of a volume set this band becomes.
    pub role: BandRole,
}

/// One feature type's canonical style id — the assignment baked into every chunk.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct StyleAssignment {
    /// 1-based style id, as referenced by feature headers (`OBCM_Spec.md` §2, §5.2).
    pub id: u8,
    /// `<tag_key>.<tag_value>`, e.g. `highway.primary`.
    pub feature_type: String,
}

/// The routing facts a cell's nav bytes were produced under.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct RoutingEntry {
    /// Island-prune threshold, applied at **assembly** over the merged graph
    /// (`OBCA_Spec.md` §3.5/§4.6) — a cell bake prunes only strictly interior
    /// components.
    pub min_component_edges: u32,
    /// Profile names in `OBCM_Spec.md` §8.6 table order.
    pub profiles: Vec<String>,
}

/// A skin: the presentation half of what v1 called a preset. Stamped onto ~2 KB of an
/// assembly at assembly time, so it is baked into nothing and invalidates nothing
/// (§11.4).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SkinEntry {
    pub id: String,
    pub name: String,
    pub description: String,
    /// The skin's content version. Unlike v1's `preset_version` there is no
    /// per-artifact counterpart, because no artifact carries a skin.
    pub version: u32,
    /// RGB565 user-position marker color (`OBCM_Spec.md` §1).
    pub marker_color: u16,
    /// One entry per `schema.styles` feature type, in schema id order. A skin that
    /// misses one would ship a map with an invisible layer; one that names a feature
    /// type the schema lacks is stale (§11.4).
    pub styles: Vec<SkinStyle>,
    /// Rendered preview asset, resolved like a `url`. Absent until one exists.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
}

/// One feature type's presentation values — the seven bytes of a style record a skin
/// owns. The **id** is not here: it belongs to the schema, and a skin may not
/// renumber it (`OBCA_Spec.md` §4.7).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct SkinStyle {
    pub feature_type: String,
    /// RGB565.
    pub color: u16,
    pub weight: u8,
    pub z_index: i8,
    /// 1..=4.
    pub priority: u8,
    pub dashed: bool,
    /// Optional RGB565 secondary color; `null` when the style has none.
    pub color2: Option<u16>,
}

/// A named region: a boundary to draw and a cell set to fetch (§11.5).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct RegionEntry {
    /// Slash-separated id, same grammar as v1's `region_id`.
    pub id: String,
    pub name: String,
    /// The enclosing region's id, when the curation nests.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
    /// Simplified outline for drawing (§11.8). Presentation only.
    pub boundary: Boundary,
    /// Total bytes of every cell in this region's set, across all bands.
    pub bytes: u64,
    /// Those bytes per band, summing to `bytes`. This is what makes the §5.7
    /// pre-download projection *per file* rather than merely per set: a volume set's
    /// roles partition by band, so the `core` band's bytes are the core file's bytes.
    pub bytes_by_band: BTreeMap<String, u64>,
    /// Cells per band.
    pub cell_count: BTreeMap<String, u32>,
    /// How many of those cells are `partial` (§11.6). `0` for fully covered curation.
    pub partial_cell_count: u32,
    /// Where the region's cell-id list lives (§11.7).
    pub cells_url: String,
    /// Size of that document, in bytes.
    pub cells_bytes: u64,
    /// Its digest — the pin that keeps the satellite all-or-nothing.
    pub cells_sha256: String,
}

/// A region's simplified outline: rings of `[lat, lon]` integer microdegrees
/// (§11.8). Microdegrees and lat-first, matching v1's bbox and the OBCM header, so
/// nothing in the family mixes conventions.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct Boundary {
    /// The tolerance the outline was reduced at.
    pub tolerance_udeg: i32,
    /// One or more closed rings; the first is an exterior and any ring nested in it is
    /// a hole. A region that is several disjoint pieces repeats that pattern.
    pub rings: Vec<boundary::Ring>,
}

/// The root's pin on one band's cell index (§11.6).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CellIndexRef {
    pub band: String,
    /// `log2(S)`; matches the band's entry in `schema.bands`.
    pub cell_log2: u8,
    /// Cells in the referenced document.
    pub cell_count: u32,
    /// Size of the referenced document.
    pub bytes: u64,
    /// Its digest. A satellite that does not match MUST be rejected and the root kept.
    pub sha256: String,
    pub url: String,
}

/// A band's cell index: the satellite the root pins (§11.6).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CellIndexDocument {
    pub schema_version: u32,
    /// The revision every cell in this document was baked at.
    pub schema_revision: u32,
    pub band: String,
    /// Sorted by `(i, j)`.
    pub cells: Vec<CellEntry>,
}

/// One published cell. **No bbox, deliberately**: the `id` determines the square and
/// the generator verifies the artifact's header against it (§11.6).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CellEntry {
    /// Canonical cell id, `<log2>/<i>/<j>` (`OBCA_Spec.md` §1.3).
    pub id: String,
    pub bytes: u64,
    pub sha256: String,
    pub url: String,
    /// RFC 3339 UTC, recorded by the bake job.
    pub built_at: String,
    /// Every source extract this cell was baked from, sorted by `extract_id`.
    pub sources: Vec<CellSource>,
    /// `true` iff those sources do not fully cover the cell's square
    /// (`OBCA_Spec.md` §3.7). A consumer MUST NOT present a partial cell as canonical
    /// coverage.
    pub partial: bool,
}

/// One source extract behind a cell.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, JsonSchema)]
pub struct CellSource {
    /// The extract's identifier, e.g. `europe/switzerland`.
    pub extract_id: String,
    /// That extract's snapshot date, `YYYY-MM-DD`.
    pub snapshot: String,
}

/// A region's cell list: the satellite `RegionEntry::cells_url` points at (§11.7).
///
/// Cell ids only — every other fact is in the band's index, keyed by the same id.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct RegionCellsDocument {
    pub schema_version: u32,
    pub schema_revision: u32,
    pub region_id: String,
    /// Band id → sorted cell ids.
    pub cells: BTreeMap<String, Vec<String>>,
}

// --- generation ---------------------------------------------------------------------------

/// Generator inputs that cannot be derived from the tree.
#[derive(Debug, Clone)]
pub struct CatalogV2Options {
    /// Where the tree gets published; every `url` is this plus the object's path
    /// relative to the tree root.
    pub base_url: String,
    /// The root's `generated_at`, RFC 3339 UTC. Passed in so the generator is a pure
    /// function of (tree, options).
    pub generated_at: String,
    /// Boundary simplification tolerance in microdegrees
    /// ([`boundary::DEFAULT_TOLERANCE_UDEG`]).
    pub boundary_tolerance_udeg: i32,
}

impl CatalogV2Options {
    /// Options with the default outline tolerance.
    pub fn new(base_url: impl Into<String>, generated_at: impl Into<String>) -> CatalogV2Options {
        CatalogV2Options {
            base_url: base_url.into(),
            generated_at: generated_at.into(),
            boundary_tolerance_udeg: boundary::DEFAULT_TOLERANCE_UDEG,
        }
    }
}

/// A satellite document: its path relative to the tree root (which is also its path
/// relative to `base_url`) and its exact bytes — the bytes the root's digest pins.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Satellite {
    pub rel_path: String,
    pub body: String,
}

/// A generated v2 catalog: the root, the satellites it pins, and non-fatal
/// observations. Warnings are returned rather than printed so the bakery decides
/// whether a coverage gap is a log line or a failed job.
#[derive(Debug, Clone)]
pub struct GeneratedCatalogV2 {
    pub root: CatalogV2,
    pub satellites: Vec<Satellite>,
    pub warnings: Vec<String>,
}

/// A boundary bigger than this is worth a warning: §11.8 budgets "a few KB" per
/// region, and the root carries one per region *before* a consumer knows anything
/// else about the catalog.
const BOUNDARY_WARN_BYTES: usize = 16 * 1024;

const CELLS_DIR: &str = "cells";
const REGIONS_DIR: &str = "regions";
const SKINS_DIR: &str = "skins";
const SCHEMA_DOC: &str = "schema.json";
const CELL_EXT: &str = ".obcm";
const CELL_SIDECAR_EXT: &str = ".obcm.json";
const CELL_INDEX_NAME: &str = "index.json";
const REGION_DOC: &str = "region.json";
const REGION_POLY: &str = "boundary.poly";
const REGION_CELLS_NAME: &str = "cells.json";

/// Walk a v2 bake tree and build the root plus its satellites.
///
/// ```text
/// <tree>/
///   schema.json                        the packer config the cells were baked with; `_meta` adds the band table
///   skins/<skin_id>.json               one packer config per skin (same style ids, different values)
///   cells/<band>/<i>/<j>.obcm          a cell artifact
///   cells/<band>/<i>/<j>.obcm.json     its sidecar (schema revision, build time, sources, partial)
///   regions/<a>/…/region.json          the curated selection: display name + its cell ids per band
///   regions/<a>/…/boundary.poly        that region's Geofabrik .poly, simplified into the outline
///   cells/<band>/index.json            generated (§11.6)
///   regions/<a>/…/cells.json           generated (§11.7)
///   catalog.json                       generated root
/// ```
///
/// The generated documents are written *into* the tree, so re-running over a tree the
/// generator has already visited is normal and its own output is skipped by name.
pub fn generate(tree: &Path, opts: &CatalogV2Options) -> Result<GeneratedCatalogV2, String> {
    let base_url = normalize_base_url(&opts.base_url)?;
    validate_timestamp(&opts.generated_at).map_err(|e| format!("generated_at: {e}"))?;

    let schema = read_schema_doc(&tree.join(SCHEMA_DOC))?;
    let mut warnings = Vec::new();

    // Cells first: the schema's `obcm_version` is read out of their headers, so there
    // is no schema entry to publish until every cell has agreed.
    let cells = read_cells(tree, &schema, &base_url)?;
    let obcm_version = cells.obcm_version;

    let skins = read_skins(&tree.join(SKINS_DIR), &schema)?;

    let mut satellites = Vec::new();
    let mut cell_index = Vec::new();
    let mut by_band: BTreeMap<&str, BTreeMap<String, &CellEntry>> = BTreeMap::new();
    for band in &schema.bands {
        let entries = cells.by_band.get(band.id.as_str()).map_or(&[][..], Vec::as_slice);
        if entries.is_empty() {
            warnings.push(format!(
                "band `{}` has no published cells — every assembly at this schema will be missing what that band \
                 carries",
                band.id
            ));
        }
        let doc = CellIndexDocument {
            schema_version: CATALOG_SCHEMA_VERSION,
            schema_revision: schema.revision,
            band: band.id.clone(),
            cells: entries.to_vec(),
        };
        let rel_path = format!("{CELLS_DIR}/{}/{CELL_INDEX_NAME}", band.id);
        let body = document_json(&doc);
        let (bytes, sha256) = hash_str(&body);
        cell_index.push(CellIndexRef {
            band: band.id.clone(),
            cell_log2: band.cell_log2,
            cell_count: entries.len() as u32,
            bytes,
            sha256,
            url: format!("{base_url}/{rel_path}"),
        });
        satellites.push(Satellite { rel_path, body });
        by_band.insert(band.id.as_str(), entries.iter().map(|c| (c.id.clone(), c)).collect());
    }
    // §11.2: sorted by `cell_log2` descending — coarse first. Two bands may share a
    // size (v1's `fine` and `network` are both 2^18), so the band id breaks the tie
    // and the order stays total.
    cell_index.sort_by(|a, b| (b.cell_log2, &a.band).cmp(&(a.cell_log2, &b.band)));

    let regions = read_regions(tree, &schema, &by_band, &base_url, opts, &mut satellites, &mut warnings)?;
    if regions.is_empty() {
        warnings.push(
            "no regions — the catalog offers cells but no named selection, so a builder has nothing to pick from"
                .to_string(),
        );
    }

    let root = CatalogV2 {
        schema_version: CATALOG_SCHEMA_VERSION,
        generated_at: opts.generated_at.clone(),
        schema: SchemaEntry {
            id: schema.id,
            revision: schema.revision,
            name: schema.name,
            description: schema.description,
            obcm_version,
            grid: GridEntry { origin_udeg: GRID_ORIGIN_UDEG, world_side_udeg: WORLD_SIDE_UDEG },
            lods: schema.lods,
            bands: schema.bands,
            styles: schema.styles,
            routing: schema.routing,
            chunk_size: schema.chunk_size,
        },
        skins,
        regions,
        cell_index,
        artifacts: None,
    };
    Ok(GeneratedCatalogV2 { root, satellites, warnings })
}

/// Pretty JSON with a trailing newline — the same spelling v1 publishes, so a
/// published document diffs line-by-line and generation is byte-reproducible.
pub fn root_json(root: &CatalogV2) -> String {
    let mut text = serde_json::to_string_pretty(root).expect("v2 root serializes");
    text.push('\n');
    text
}

fn document_json<T: Serialize>(doc: &T) -> String {
    let mut text = serde_json::to_string_pretty(doc).expect("v2 satellite serializes");
    text.push('\n');
    text
}

fn hash_str(body: &str) -> (u64, String) {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(body.as_bytes());
    (body.len() as u64, super::hex(&hasher.finalize()))
}

/// Write the whole catalog into the tree: **satellites first, root last**.
///
/// That order is §11.1's digest pinning made operational — the root is the document
/// that claims a satellite exists with a given digest, so it must not become visible
/// until every satellite it names is on disk with those exact bytes. Each file is
/// written temp-then-`rename` by [`super::write_atomic`]'s mechanism, so no reader
/// ever sees a half-written document.
pub fn write_all_atomic(tree: &Path, generated: &GeneratedCatalogV2) -> Result<(), String> {
    for satellite in &generated.satellites {
        let path = tree.join(satellite.rel_path.replace('/', std::path::MAIN_SEPARATOR_STR));
        if let Some(dir) = path.parent() {
            std::fs::create_dir_all(dir).map_err(|e| format!("{}: {e}", dir.display()))?;
        }
        super::write_atomic_bytes(&path, &satellite.body)?;
    }
    super::write_atomic_bytes(&tree.join(super::DEFAULT_MANIFEST_NAME), &root_json(&generated.root))
}

// --- the schema document ------------------------------------------------------------------

/// The schema as the tree states it: the packer config the cells were baked with,
/// whose `_meta` adds the revision and the band table.
///
/// One document rather than two because the parts must not be able to disagree: the
/// style-id assignment, the LOD ladder, `chunk_size` and the routing table are read
/// out of the very config that produced the cells' bytes, not out of a hand-written
/// description of it.
struct SchemaDoc {
    id: String,
    revision: u32,
    name: String,
    description: String,
    lods: Vec<LodEntry>,
    bands: Vec<BandEntry>,
    styles: Vec<StyleAssignment>,
    routing: RoutingEntry,
    chunk_size: u32,
    /// Feature type → its style values, for checking a skin covers exactly this set.
    feature_types: BTreeMap<String, u8>,
}

#[derive(Debug, Deserialize)]
struct SchemaMetaDoc {
    #[serde(rename = "_meta")]
    meta: Option<SchemaMeta>,
}

#[derive(Debug, Deserialize)]
struct SchemaMeta {
    id: String,
    name: String,
    description: String,
    /// The cell store's identity. Bumping it invalidates every cell
    /// (`OBCA_Spec.md` §6.3), which is why it is stated here and recorded in every
    /// cell sidecar: the generator can then refuse a tree that mixes revisions.
    revision: u32,
    bands: Vec<BandDoc>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BandDoc {
    id: String,
    cell_log2: u8,
    #[serde(default)]
    lods: Vec<u32>,
    #[serde(default)]
    sections: Vec<BandSection>,
    role: BandRole,
}

fn read_schema_doc(path: &Path) -> Result<SchemaDoc, String> {
    let text = std::fs::read_to_string(path).map_err(|e| {
        format!(
            "{}: {e} — a v2 bake tree's `{SCHEMA_DOC}` is the packer config its cells were baked with, plus a `_meta` \
             block carrying `revision` and `bands`",
            path.display()
        )
    })?;
    let doc: SchemaMetaDoc = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
    let meta = doc
        .meta
        .ok_or_else(|| format!("{}: no `_meta` block (id, name, description, revision, bands)", path.display()))?;
    validate_id(&meta.id).map_err(|e| format!("{}: schema id {e}", path.display()))?;
    if meta.name.trim().is_empty() || meta.description.trim().is_empty() {
        return Err(format!("{}: `_meta.name` and `_meta.description` must be non-empty", path.display()));
    }
    if meta.revision == 0 {
        return Err(format!("{}: `_meta.revision` starts at 1 — a cell store has no revision zero", path.display()));
    }

    let config = Config::parse(&text).map_err(|e| format!("{}: {e}", path.display()))?;
    let bands = check_band_table(&meta.bands, config.lods.len(), path)?;
    let lods = ladder(&config, &bands, path)?;
    let (styles, feature_types) = style_assignment(&config, path)?;

    Ok(SchemaDoc {
        id: meta.id,
        revision: meta.revision,
        name: meta.name,
        description: meta.description,
        lods,
        bands,
        styles,
        routing: RoutingEntry {
            min_component_edges: config.routing.min_component_edges as u32,
            profiles: config.routing.profiles.iter().map(|p| p.name.clone()).collect(),
        },
        chunk_size: config.chunk_size as u32,
        feature_types,
    })
}

/// The band table's rules (§11.3, `OBCA_Spec.md` §1.2/§5.1), all of which a consumer
/// must reject and which therefore must not be publishable in the first place:
/// every ladder LOD in exactly one band, the nav and POI sections in exactly one
/// band, exactly one `core` band carrying the sections and no LOD, at most one
/// `coarse` band, everything else `geometry`.
fn check_band_table(bands: &[BandDoc], lod_count: usize, path: &Path) -> Result<Vec<BandEntry>, String> {
    let at = || path.display().to_string();
    if bands.is_empty() {
        return Err(format!("{}: `_meta.bands` is empty — a cell store needs a band table", at()));
    }
    let mut ids = BTreeSet::new();
    let mut lod_owner: BTreeMap<u32, &str> = BTreeMap::new();
    let mut section_owner: BTreeMap<BandSection, &str> = BTreeMap::new();
    let mut cores = Vec::new();
    let mut coarses = Vec::new();
    let mut out = Vec::new();
    for band in bands {
        validate_id(&band.id).map_err(|e| format!("{}: band id {e}", at()))?;
        if !ids.insert(band.id.as_str()) {
            return Err(format!("{}: band `{}` is listed twice", at(), band.id));
        }
        if !(MIN_CELL_LOG2..=MAX_CELL_LOG2).contains(&band.cell_log2) {
            return Err(format!(
                "{}: band `{}`: cell size 2^{} µdeg is outside 2^{MIN_CELL_LOG2}..=2^{MAX_CELL_LOG2}",
                at(),
                band.id,
                band.cell_log2
            ));
        }
        let mut lods = band.lods.clone();
        lods.sort_unstable();
        lods.dedup();
        if lods.len() != band.lods.len() {
            return Err(format!("{}: band `{}` lists a LOD twice", at(), band.id));
        }
        for &lod in &lods {
            if lod as usize >= lod_count {
                return Err(format!(
                    "{}: band `{}` claims LOD {lod}, but the ladder has {lod_count} level(s)",
                    at(),
                    band.id
                ));
            }
            if let Some(other) = lod_owner.insert(lod, &band.id) {
                return Err(format!(
                    "{}: LOD {lod} is in both band `{other}` and band `{}` — it would be written twice \
                     (OBCA_Spec.md §1.2)",
                    at(),
                    band.id
                ));
            }
        }
        let mut sections = band.sections.clone();
        sections.sort_unstable();
        sections.dedup();
        if sections.len() != band.sections.len() {
            return Err(format!("{}: band `{}` lists a section twice", at(), band.id));
        }
        for &section in &sections {
            if let Some(other) = section_owner.insert(section, &band.id) {
                return Err(format!(
                    "{}: the {section:?} section is in both band `{other}` and band `{}` — it belongs to exactly one",
                    at(),
                    band.id
                ));
            }
        }
        match band.role {
            BandRole::Core => {
                cores.push(band.id.as_str());
                if !lods.is_empty() {
                    return Err(format!(
                        "{}: the `core` band `{}` carries LOD(s) {lods:?}. The core file is the one file of a volume \
                         set that cannot be split by bbox, so no geometry may live in it (OBCA_Spec.md §5.1) — its \
                         headroom under 4 GiB is the design's hard limit.",
                        at(),
                        band.id
                    ));
                }
                if sections != [BandSection::Nav, BandSection::Poi] {
                    return Err(format!(
                        "{}: the `core` band `{}` must carry both the `nav` and `poi` sections (got {sections:?})",
                        at(),
                        band.id
                    ));
                }
            }
            BandRole::Coarse | BandRole::Geometry => {
                coarses.extend(matches!(band.role, BandRole::Coarse).then_some(band.id.as_str()));
                if lods.is_empty() {
                    return Err(format!("{}: band `{}` carries no LOD and is not the `core` band", at(), band.id));
                }
                if !sections.is_empty() {
                    return Err(format!(
                        "{}: band `{}` carries {sections:?}, but only the `core` band may carry a section",
                        at(),
                        band.id
                    ));
                }
            }
        }
        out.push(BandEntry { id: band.id.clone(), cell_log2: band.cell_log2, lods, sections, role: band.role });
    }

    if cores.len() != 1 {
        return Err(format!("{}: exactly one band must have `role: core` (got {cores:?})", at()));
    }
    if coarses.len() > 1 {
        return Err(format!("{}: at most one band may have `role: coarse` (got {coarses:?})", at()));
    }
    for section in [BandSection::Nav, BandSection::Poi] {
        if !section_owner.contains_key(&section) {
            return Err(format!("{}: no band carries the {section:?} section", at()));
        }
    }
    let missing: Vec<usize> = (0..lod_count).filter(|l| !lod_owner.contains_key(&(*l as u32))).collect();
    if !missing.is_empty() {
        return Err(format!(
            "{}: ladder LOD(s) {missing:?} are in no band — a map would be blank at that zoom (OBCA_Spec.md §1.2)",
            at()
        ));
    }

    // Published in band order as authored, which is the coarse→fine reading order of
    // the table; determinism comes from the file, not from a map.
    Ok(out)
}

/// The LOD ladder as the catalog publishes it, cross-checked against `OBCM_Spec.md`
/// §3: exactly one `+inf` level and it is index 0, strictly decreasing after.
fn ladder(config: &Config, bands: &[BandEntry], path: &Path) -> Result<Vec<LodEntry>, String> {
    let mut out = Vec::with_capacity(config.lods.len());
    let mut previous: Option<f64> = None;
    for (index, lod) in config.lods.iter().enumerate() {
        match (index, lod.max_mpp) {
            (0, None) => {}
            (0, Some(mpp)) => {
                return Err(format!(
                    "{}: ladder LOD 0 has max_mpp {mpp} — the coarsest level is +inf (`null`), OBCM_Spec.md §3",
                    path.display()
                ))
            }
            (_, None) => {
                return Err(format!("{}: ladder LOD {index} is +inf; only LOD 0 may be", path.display()));
            }
            (_, Some(mpp)) => {
                if let Some(prev) = previous {
                    if mpp >= prev {
                        return Err(format!(
                            "{}: ladder max_mpp must strictly decrease ({prev} then {mpp} at LOD {index})",
                            path.display()
                        ));
                    }
                }
                previous = Some(mpp);
            }
        }
        let band = bands
            .iter()
            .find(|b| b.lods.contains(&(index as u32)))
            .expect("check_band_table proved every LOD has a band");
        out.push(LodEntry { index: index as u32, max_mpp: lod.max_mpp, band: band.id.clone() });
    }
    Ok(out)
}

/// The canonical style-id assignment, read out of the config that assigned it.
///
/// Returned sorted by id, which is also the order a style table is written in
/// (`OBCM_Spec.md` §2) and the order a skin's entries follow.
fn style_assignment(config: &Config, path: &Path) -> Result<(Vec<StyleAssignment>, BTreeMap<String, u8>), String> {
    let mut by_type = BTreeMap::new();
    let mut by_id: BTreeMap<u8, String> = BTreeMap::new();
    for (tag_key, values) in &config.features {
        for (tag_value, style) in values {
            let feature_type = format!("{tag_key}.{tag_value}");
            if let Some(other) = by_id.insert(style.id, feature_type.clone()) {
                return Err(format!(
                    "{}: style id {} is assigned to both `{other}` and `{feature_type}`",
                    path.display(),
                    style.id
                ));
            }
            by_type.insert(feature_type, style.id);
        }
    }
    if by_type.is_empty() {
        return Err(format!("{}: no feature types — a schema with no styles draws nothing", path.display()));
    }
    let styles = by_id.into_iter().map(|(id, feature_type)| StyleAssignment { id, feature_type }).collect();
    Ok((styles, by_type))
}

// --- skins --------------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
struct SkinMetaDoc {
    #[serde(rename = "_meta")]
    meta: Option<SkinMeta>,
}

#[derive(Debug, Deserialize)]
struct SkinMeta {
    id: String,
    name: String,
    description: String,
    version: u32,
    #[serde(default)]
    preview: Option<String>,
}

fn read_skins(dir: &Path, schema: &SchemaDoc) -> Result<Vec<SkinEntry>, String> {
    if !dir.is_dir() {
        return Err(format!("{}: no `{SKINS_DIR}/` directory — a v2 catalog offers at least one skin", dir.display()));
    }
    let mut skins = Vec::new();
    for path in sorted_entries(dir)? {
        let name = file_name(&path)?;
        if name.starts_with('.') || path.is_dir() {
            continue;
        }
        let Some(stem) = name.strip_suffix(".json") else {
            return Err(format!("{}: only `<skin_id>.json` skin configs belong in `{SKINS_DIR}/`", path.display()));
        };
        validate_id(stem).map_err(|e| format!("{}: skin id {e}", path.display()))?;
        let text = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        let doc: SkinMetaDoc = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
        let meta =
            doc.meta.ok_or_else(|| format!("{}: no `_meta` block (id, name, description, version)", path.display()))?;
        if meta.id != stem {
            return Err(format!("{}: `_meta.id` is `{}` but the filename says `{stem}`", path.display(), meta.id));
        }
        if meta.name.trim().is_empty() || meta.description.trim().is_empty() {
            return Err(format!("{}: `_meta.name` and `_meta.description` must be non-empty", path.display()));
        }
        let config = Config::parse(&text).map_err(|e| format!("{}: {e}", path.display()))?;
        let styles = skin_styles(&config, schema, &path)?;
        skins.push(SkinEntry {
            id: meta.id,
            name: meta.name,
            description: meta.description,
            version: meta.version,
            marker_color: config.marker_color,
            styles,
            preview: meta.preview,
        });
    }
    if skins.is_empty() {
        return Err(format!("{}: no skin configs found", dir.display()));
    }
    Ok(skins)
}

/// A skin's style values, in the schema's id order, after proving the skin is a skin:
/// same feature types, same ids. `OBCA_Spec.md` §4.7 — a skin may change only the
/// seven presentation bytes of a style record, never introduce, remove, reorder or
/// renumber an id, because those ids are referenced by every feature header in every
/// chunk already baked.
fn skin_styles(config: &Config, schema: &SchemaDoc, path: &Path) -> Result<Vec<SkinStyle>, String> {
    let mut by_type = BTreeMap::new();
    for (tag_key, values) in &config.features {
        for (tag_value, style) in values {
            by_type.insert(format!("{tag_key}.{tag_value}"), style.clone());
        }
    }
    let unknown: Vec<&String> = by_type.keys().filter(|t| !schema.feature_types.contains_key(*t)).collect();
    if !unknown.is_empty() {
        return Err(format!(
            "{}: this skin styles feature type(s) the schema does not have: {}. A skin is a recolor of one schema — a \
             new feature type is a new schema revision and a re-bake.",
            path.display(),
            joined(unknown.iter().map(|t| t.as_str()))
        ));
    }
    let missing: Vec<&str> =
        schema.feature_types.keys().filter(|t| !by_type.contains_key(*t)).map(String::as_str).collect();
    if !missing.is_empty() {
        return Err(format!(
            "{}: this skin has no style for {}. A missing style would ship a map with an invisible layer \
             (OBCC_Spec.md §11.4).",
            path.display(),
            joined(missing.into_iter())
        ));
    }
    let mut renumbered = Vec::new();
    for (feature_type, style) in &by_type {
        let want = schema.feature_types[feature_type];
        if style.id != want {
            renumbered.push(format!("`{feature_type}` is id {} here but {want} in the schema", style.id));
        }
    }
    if !renumbered.is_empty() {
        return Err(format!(
            "{}: a skin MUST NOT renumber style ids — every feature header in every baked chunk references them \
             (OBCA_Spec.md §4.7): {}",
            path.display(),
            renumbered.join("; ")
        ));
    }

    // Schema order, so `skins[].styles[k]` and `schema.styles[k]` describe the same
    // feature type without a consumer having to join on the name.
    let mut styles: Vec<SkinStyle> = by_type
        .into_iter()
        .map(|(feature_type, s)| SkinStyle {
            feature_type,
            color: s.color,
            weight: s.weight,
            z_index: s.z_index,
            priority: s.priority,
            dashed: s.line_style == LineStyle::Dashed,
            color2: s.color2,
        })
        .collect();
    styles.sort_by_key(|s| schema.feature_types[&s.feature_type]);
    Ok(styles)
}

fn joined<'a>(items: impl Iterator<Item = &'a str>) -> String {
    items.collect::<Vec<_>>().join(", ")
}

// --- cells --------------------------------------------------------------------------------

/// Every published cell, grouped by band, plus the one OBCM version they all agree on.
///
/// §11.6's "MUST NOT publish a canonical cell and a partial cell for the same `id` at
/// the same `schema_revision`" holds by construction here: a (band, i, j) is one path
/// in the tree, so a re-bake that finds a covering source overwrites the partial cell
/// rather than adding a second entry beside it.
struct Cells {
    by_band: BTreeMap<String, Vec<CellEntry>>,
    obcm_version: u8,
}

/// The facts a cell's bytes cannot state. Band is **not** among them: band membership
/// is a property of the schema revision, and a cell writes the full ladder with the
/// LODs outside its band empty, so a legitimately empty cell is indistinguishable
/// from an out-of-band one (`OBCA_Spec.md` §3.1). The tree's path says the band.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct CellSidecar {
    /// The schema revision this cell was baked at. Recorded per cell so the generator
    /// can refuse a tree that mixes revisions (`OBCA_Spec.md` §6.3).
    schema_revision: u32,
    built_at: String,
    /// Every extract this cell was baked from, with that extract's snapshot date.
    sources: Vec<CellSource>,
    /// Whether the sources fully cover the cell's square (`OBCA_Spec.md` §3.7).
    partial: bool,
}

fn read_cells(tree: &Path, schema: &SchemaDoc, base_url: &str) -> Result<Cells, String> {
    let root = tree.join(CELLS_DIR);
    if !root.is_dir() {
        return Err(format!("{}: no `{CELLS_DIR}/` directory — is this a v2 bake tree?", root.display()));
    }
    let bands: BTreeMap<&str, &BandEntry> = schema.bands.iter().map(|b| (b.id.as_str(), b)).collect();
    let mut by_band: BTreeMap<String, Vec<CellEntry>> = BTreeMap::new();
    let mut obcm_version = None;

    for band_dir in sorted_entries(&root)? {
        let name = file_name(&band_dir)?;
        if name.starts_with('.') {
            continue;
        }
        if !band_dir.is_dir() {
            return Err(format!(
                "{}: `{CELLS_DIR}/` holds one directory per band; loose files do not belong here",
                band_dir.display()
            ));
        }
        let band = bands.get(name.as_str()).ok_or_else(|| {
            format!(
                "{}: `{name}` is not a band in `{SCHEMA_DOC}`'s band table. Cell paths are keyed by band because two \
                 bands may share a cell size.",
                band_dir.display()
            )
        })?;

        let mut entries = Vec::new();
        for i_dir in sorted_entries(&band_dir)? {
            let name = file_name(&i_dir)?;
            if name.starts_with('.') || name == CELL_INDEX_NAME {
                // `index.json` is this generator's own output, written into the tree.
                continue;
            }
            if !i_dir.is_dir() {
                return Err(format!(
                    "{}: expected a `<i>` directory or the generated `{CELL_INDEX_NAME}`",
                    i_dir.display()
                ));
            }
            read_cell_row(&i_dir, &name, band, tree, schema, base_url, &mut entries, &mut obcm_version)?;
        }
        entries.sort_by(|a, b| a.id.cmp(&b.id));
        by_band.insert(band.id.clone(), entries);
    }

    let total: usize = by_band.values().map(Vec::len).sum();
    if total == 0 {
        return Err(format!("{}: no cells found — refusing to publish an empty cell store", root.display()));
    }
    Ok(Cells { by_band, obcm_version: obcm_version.expect("a cell was read") })
}

#[allow(clippy::too_many_arguments)]
fn read_cell_row(
    dir: &Path,
    i_text: &str,
    band: &BandEntry,
    tree: &Path,
    schema: &SchemaDoc,
    base_url: &str,
    out: &mut Vec<CellEntry>,
    obcm_version: &mut Option<u8>,
) -> Result<(), String> {
    let mut sidecars: Vec<String> = Vec::new();
    let mut artifacts: Vec<(String, PathBuf)> = Vec::new();
    for entry in sorted_entries(dir)? {
        let name = file_name(&entry)?;
        if name.starts_with('.') {
            continue;
        }
        if let Some(stem) = name.strip_suffix(CELL_SIDECAR_EXT) {
            sidecars.push(stem.to_string());
        } else if let Some(stem) = name.strip_suffix(CELL_EXT) {
            artifacts.push((stem.to_string(), entry));
        } else {
            return Err(format!(
                "{}: unexpected entry in a cell row (expected `<j>{CELL_EXT}` and `<j>{CELL_SIDECAR_EXT}`)",
                entry.display()
            ));
        }
    }

    for (j_text, path) in artifacts {
        let id = CellId::parse(&format!("{}/{i_text}/{j_text}", band.cell_log2))
            .map_err(|e| format!("{}: {e}", path.display()))?;
        let sidecar_path = path.with_file_name(format!("{j_text}{CELL_SIDECAR_EXT}"));
        let sidecar = read_cell_sidecar(&sidecar_path)?;
        sidecars.retain(|s| s != &j_text);

        // A schema-revision bump is as hard a cut as an OBCM bump: assembly copies
        // chunk bytes between files, which is only meaningful within one revision.
        if sidecar.schema_revision != schema.revision {
            return Err(format!(
                "{}: cell was baked at schema revision {} but `{SCHEMA_DOC}` is revision {}. A schema-revision bump \
                 invalidates every cell (OBCA_Spec.md §6.3) — re-bake, or publish the revision the cells actually \
                 carry. There is no mixed-revision catalog.",
                path.display(),
                sidecar.schema_revision,
                schema.revision
            ));
        }

        // The world box is wider than the geographic domain and a cell may legally
        // overhang ±90°/±180° (OBCA_Spec.md §1.4), so this is the one header read
        // that must not apply the domain clamp v1's artifacts are checked against.
        let header = read_obcm_header_in(&path, HeaderBounds::WorldBox)?;
        if header.version != OBCM_VERSION {
            return Err(format!(
                "{}: cell is OBCM v{} but this obc-pack writes v{OBCM_VERSION}. An OBCM format bump invalidates every \
                 baked cell (OBCC_Spec.md §6, §11.9) — re-bake the store with the current packer.",
                path.display(),
                header.version
            ));
        }
        match obcm_version {
            None => *obcm_version = Some(header.version),
            Some(v) if *v != header.version => {
                return Err(format!("{}: cell is OBCM v{} but the store is v{v}", path.display(), header.version));
            }
            Some(_) => {}
        }

        // §11.6: no bbox is stored, so this is where the identifier and the bytes are
        // made to agree. A cell whose header is not exactly its grid square would
        // graft into an assembly at the wrong place, silently.
        let square = id.square();
        let got = (header.bbox.min_lat, header.bbox.min_lon, header.bbox.max_lat, header.bbox.max_lon);
        let want = (square.min_lat, square.min_lon, square.max_lat, square.max_lon);
        if got != want {
            return Err(format!(
                "{}: cell `{id}`'s header bbox is {got:?} but its grid square is {want:?}. A cell's bbox MUST be \
                 exactly its square (OBCA_Spec.md §3.1) — that is what lets an assembler copy its chunk bytes \
                 verbatim, and it is why the catalog stores no bbox for a cell.",
                path.display()
            ));
        }

        let (bytes, sha256) = hash_file(&path)?;
        let rel = path.strip_prefix(tree).map_err(|_| format!("{}: cell is outside the tree root", path.display()))?;
        out.push(CellEntry {
            id: id.to_string(),
            bytes,
            sha256,
            url: format!("{base_url}/{}", rel_url_path(rel)?),
            built_at: sidecar.built_at,
            sources: sidecar.sources,
            partial: sidecar.partial,
        });
    }

    if let Some(orphan) = sidecars.first() {
        return Err(format!(
            "{}: sidecar with no cell — `{orphan}{CELL_EXT}` is missing",
            dir.join(format!("{orphan}{CELL_SIDECAR_EXT}")).display()
        ));
    }
    Ok(())
}

fn read_cell_sidecar(path: &Path) -> Result<CellSidecar, String> {
    let text = std::fs::read_to_string(path).map_err(|e| {
        format!("{}: {e} — every cell needs a sidecar (schema_revision, built_at, sources, partial)", path.display())
    })?;
    let mut sidecar: CellSidecar = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
    validate_timestamp(&sidecar.built_at).map_err(|e| format!("{}: built_at {e}", path.display()))?;
    if sidecar.sources.is_empty() {
        return Err(format!(
            "{}: `sources` is empty — a cell must record what it was baked from (OBCA_Spec.md §3.7)",
            path.display()
        ));
    }
    let mut seen = BTreeSet::new();
    for source in &sidecar.sources {
        validate_region_id(&source.extract_id).map_err(|e| format!("{}: sources.extract_id {e}", path.display()))?;
        validate_date(&source.snapshot).map_err(|e| format!("{}: sources.snapshot {e}", path.display()))?;
        if !seen.insert(source.extract_id.as_str()) {
            return Err(format!("{}: extract `{}` is listed twice", path.display(), source.extract_id));
        }
    }
    // §11.6 publishes sources sorted by extract_id; the order a bake job happened to
    // write them in is not content.
    sidecar.sources.sort();
    Ok(sidecar)
}

// --- regions ------------------------------------------------------------------------------

/// The curated selection, as the tree states it. `parent` is **not** a field: it is
/// the nearest ancestor directory that is itself a region, so the curation cannot
/// declare a nesting the tree contradicts (the same reason v1 derives `region_id`
/// from the path).
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RegionDoc {
    name: String,
    /// Band id → the cell ids this region selects in that band. **Stored, not derived
    /// from the boundary** (§11.7): a simplification error must not be able to drop an
    /// edge cell, and two consumers with different point-in-polygon edge handling must
    /// not be able to disagree about what a region is.
    cells: BTreeMap<String, Vec<String>>,
}

#[allow(clippy::too_many_arguments)]
fn read_regions(
    tree: &Path,
    schema: &SchemaDoc,
    by_band: &BTreeMap<&str, BTreeMap<String, &CellEntry>>,
    base_url: &str,
    opts: &CatalogV2Options,
    satellites: &mut Vec<Satellite>,
    warnings: &mut Vec<String>,
) -> Result<Vec<RegionEntry>, String> {
    let root = tree.join(REGIONS_DIR);
    if !root.is_dir() {
        return Ok(Vec::new());
    }
    let mut found: Vec<(String, PathBuf)> = Vec::new();
    collect_region_dirs(&root, &mut Vec::new(), &mut found)?;

    let ids: BTreeSet<&str> = found.iter().map(|(id, _)| id.as_str()).collect();
    let mut out = Vec::new();
    for (id, dir) in &found {
        // The nearest enclosing *region* — not merely the parent directory, which for
        // `europe/switzerland` is the uncurated `europe`.
        let parent = ancestors(id).find(|a| ids.contains(*a)).map(str::to_string);
        out.push(read_region(id, parent, dir, schema, by_band, base_url, opts, satellites, warnings)?);
    }
    out.sort_by(|a, b| a.id.cmp(&b.id));
    Ok(out)
}

/// `europe/germany/bayern` → `europe/germany`, `europe`.
fn ancestors(id: &str) -> impl Iterator<Item = &str> {
    let mut rest = Some(id);
    std::iter::from_fn(move || {
        let current = rest?;
        let cut = current.rfind('/')?;
        rest = Some(&current[..cut]);
        Some(&current[..cut])
    })
}

fn collect_region_dirs(dir: &Path, segments: &mut Vec<String>, out: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    let mut subdirs = Vec::new();
    let mut is_region = false;
    for entry in sorted_entries(dir)? {
        let name = file_name(&entry)?;
        if name.starts_with('.') {
            continue;
        }
        if entry.is_dir() {
            validate_id(&name).map_err(|e| format!("{}: region path segment {e}", entry.display()))?;
            subdirs.push((name, entry));
        } else if name == REGION_DOC {
            is_region = true;
        } else if name == REGION_POLY || name == REGION_CELLS_NAME {
            // The outline's source, and this generator's own output.
        } else {
            return Err(format!(
                "{}: unexpected entry in a region tree (expected `{REGION_DOC}`, `{REGION_POLY}`, the generated \
                 `{REGION_CELLS_NAME}`, or a sub-region directory)",
                entry.display()
            ));
        }
    }
    if is_region {
        if segments.is_empty() {
            return Err(format!("{}: a region must live in a directory under `{REGIONS_DIR}/`", dir.display()));
        }
        out.push((segments.join("/"), dir.to_path_buf()));
    }
    for (name, path) in subdirs {
        segments.push(name);
        collect_region_dirs(&path, segments, out)?;
        segments.pop();
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn read_region(
    id: &str,
    parent: Option<String>,
    dir: &Path,
    schema: &SchemaDoc,
    by_band: &BTreeMap<&str, BTreeMap<String, &CellEntry>>,
    base_url: &str,
    opts: &CatalogV2Options,
    satellites: &mut Vec<Satellite>,
    warnings: &mut Vec<String>,
) -> Result<RegionEntry, String> {
    let doc_path = dir.join(REGION_DOC);
    let text = std::fs::read_to_string(&doc_path).map_err(|e| format!("{}: {e}", doc_path.display()))?;
    let doc: RegionDoc = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", doc_path.display()))?;
    if doc.name.trim().is_empty() {
        return Err(format!("{}: name is empty", doc_path.display()));
    }

    let mut cells: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut bytes_by_band = BTreeMap::new();
    let mut cell_count = BTreeMap::new();
    let mut partial_cell_count = 0u32;
    let mut total = 0u64;
    for band in &schema.bands {
        let listed = doc.cells.get(&band.id).map_or(&[][..], Vec::as_slice);
        let index = by_band.get(band.id.as_str()).expect("every band has an index");
        let mut ids = BTreeSet::new();
        let mut band_bytes = 0u64;
        for text in listed {
            let cell = CellId::parse(text).map_err(|e| format!("{}: {e}", doc_path.display()))?;
            if cell.log2 != band.cell_log2 {
                return Err(format!(
                    "{}: cell `{text}` is 2^{} µdeg but band `{}` is 2^{}",
                    doc_path.display(),
                    cell.log2,
                    band.id,
                    band.cell_log2
                ));
            }
            let canonical = cell.to_string();
            if !ids.insert(canonical.clone()) {
                return Err(format!(
                    "{}: cell `{canonical}` is listed twice in band `{}`",
                    doc_path.display(),
                    band.id
                ));
            }
            // §11.7: a region MUST NOT name a cell absent from the band's index. A
            // consumer would reject the pair, so publishing it is not an option.
            let entry = index.get(&canonical).ok_or_else(|| {
                format!(
                    "{}: band `{}` names cell `{canonical}`, which is not published — either bake it or drop it from \
                     the selection (OBCC_Spec.md §11.7)",
                    doc_path.display(),
                    band.id
                )
            })?;
            band_bytes += entry.bytes;
            if entry.partial {
                partial_cell_count += 1;
            }
        }
        if ids.is_empty() {
            warnings.push(format!(
                "region `{id}` names no cells in band `{}` — that band's content will be missing from every assembly \
                 of this region",
                band.id
            ));
        }
        total += band_bytes;
        bytes_by_band.insert(band.id.clone(), band_bytes);
        cell_count.insert(band.id.clone(), ids.len() as u32);
        cells.insert(band.id.clone(), ids.into_iter().collect());
    }
    for band in doc.cells.keys() {
        if !schema.bands.iter().any(|b| &b.id == band) {
            return Err(format!("{}: band `{band}` is not in `{SCHEMA_DOC}`'s band table", doc_path.display()));
        }
    }

    let poly_path = dir.join(REGION_POLY);
    let poly = std::fs::read_to_string(&poly_path).map_err(|e| {
        format!(
            "{}: {e} — a region's outline comes from its Geofabrik `.poly` (`https://download.geofabrik.de/{id}.poly`)",
            poly_path.display()
        )
    })?;
    let rings = boundary::simplified_rings(&poly, opts.boundary_tolerance_udeg)
        .map_err(|e| format!("{}: {e}", poly_path.display()))?;
    let boundary = Boundary { tolerance_udeg: opts.boundary_tolerance_udeg, rings };
    let boundary_bytes = serde_json::to_string(&boundary).map_or(0, |json| json.len());
    if boundary_bytes > BOUNDARY_WARN_BYTES {
        warnings.push(format!(
            "region `{id}`: its outline is {boundary_bytes} bytes at a {} µdeg tolerance — §11.8 budgets a few KB per \
             region, and every one of them is in the root a consumer reads first",
            opts.boundary_tolerance_udeg
        ));
    }

    let cells_doc = RegionCellsDocument {
        schema_version: CATALOG_SCHEMA_VERSION,
        schema_revision: schema.revision,
        region_id: id.to_string(),
        cells,
    };
    let rel_path = format!("{REGIONS_DIR}/{id}/{REGION_CELLS_NAME}");
    let body = document_json(&cells_doc);
    let (cells_bytes, cells_sha256) = hash_str(&body);
    satellites.push(Satellite { rel_path: rel_path.clone(), body });

    Ok(RegionEntry {
        id: id.to_string(),
        name: doc.name,
        parent,
        boundary,
        bytes: total,
        bytes_by_band,
        cell_count,
        partial_cell_count,
        cells_url: format!("{base_url}/{rel_path}"),
        cells_bytes,
        cells_sha256,
    })
}

/// A slash-separated region/extract id: v1 §3's grammar, reused for `sources`.
fn validate_region_id(id: &str) -> Result<(), String> {
    if id.is_empty() {
        return Err("`` is empty".to_string());
    }
    for segment in id.split('/') {
        validate_id(segment).map_err(|e| format!("`{id}`: segment {e}"))?;
    }
    Ok(())
}

// --- schema -------------------------------------------------------------------------------

const CELL_ID_PATTERN: &str = r"^\d{1,2}/\d{4,}/\d{4,}$";
const SHA256_PATTERN: &str = "^[0-9a-f]{64}$";
const URL_PATTERN: &str = "^(https?://|/)";
const DATE_PATTERN: &str = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$";

const CATALOG_DESCRIPTION: &str =
    "The schema_version 2 map catalog: one schema, a set of skins, named cell-set regions with drawable \
     boundaries, and digest-pinned per-band cell indices. A consumer prices a selection from this document \
     alone — total bytes and bytes per band, which is the per-file projection a volume set needs — and \
     verifies each satellite against the `bytes` + `sha256` pinned here. The satellite documents are \
     `$defs/CellIndexDocument` and `$defs/RegionCellsDocument`. Normative contract: OBCC_Spec.md §11, with \
     OBCA_Spec.md for the grid, bands, and assembly.";

const BOUNDARY_DESCRIPTION: &str =
    "A region's simplified outline, in integer microdegrees, `[lat, lon]` per point. Presentation only: it \
     MUST NOT be used to compute a cell set (that is stored, §11.7), to price a selection, or as a packer \
     input bbox. The coverage outline a builder draws for a live selection is a different object — the union \
     of the selected cells' squares, computed client-side — and is deliberately not in the catalog.";

const CELL_DESCRIPTION: &str =
    "One published cell. There is deliberately no bbox: a cell's coverage is exactly its grid square, which \
     the `id` determines to the microdegree (OBCA_Spec.md §1.3), and the generator verifies the artifact's own \
     OBCM header bbox against it at bake time. A stored copy could only agree (redundant) or disagree (a lie).";

/// Generate the v2 documents' JSON Schema from the same serde model the generator
/// writes and consumers deserialize, then add the constraints Rust types cannot
/// express, and fold the two satellite documents into `$defs` so one checked-in file
/// validates all three shapes.
pub fn catalog_schema() -> Value {
    let mut schema = serde_json::to_value(schemars::schema_for!(CatalogV2)).expect("v2 schema serializes");
    let root = schema.as_object_mut().expect("root schema is an object");
    root.insert("$schema".into(), Value::String("https://json-schema.org/draft/2020-12/schema".into()));
    root.insert("title".into(), Value::String("OpenBikeComputer map catalog (schema_version 2)".into()));
    root.insert("description".into(), Value::String(CATALOG_DESCRIPTION.into()));
    // §11.9: `presets` is not a thing that exists in v2 — a preset is a schema and a
    // skin. A root carrying one is a v1 document wearing a v2 number.
    root.insert(
        "not".into(),
        serde_json::json!({ "required": ["presets"], "description": "§11.9: `presets` MUST NOT appear in a v2 root." }),
    );

    // The satellites are separate documents, so their models are not reachable from
    // `CatalogV2`; generate each and merge, which also brings `CellEntry`/`CellSource`
    // into `$defs` where the root's own definitions live.
    let mut extra_defs = Map::new();
    for (name, mut doc) in [
        ("CellIndexDocument", serde_json::to_value(schemars::schema_for!(CellIndexDocument)).expect("cell index")),
        (
            "RegionCellsDocument",
            serde_json::to_value(schemars::schema_for!(RegionCellsDocument)).expect("region cells"),
        ),
    ] {
        let obj = doc.as_object_mut().expect("satellite schema is an object");
        obj.remove("$schema");
        obj.remove("title");
        if let Some(Value::Object(defs)) = obj.remove("$defs") {
            for (k, v) in defs {
                extra_defs.insert(k, v);
            }
        }
        extra_defs.insert(name.to_string(), doc);
    }

    let props = root.get_mut("properties").and_then(Value::as_object_mut).expect("v2 properties");
    props["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
    props["generated_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let defs = root.get_mut("$defs").and_then(Value::as_object_mut).expect("v2 definitions");
    for (k, v) in extra_defs {
        defs.insert(k, v);
    }
    for (doc, field) in [("CellIndexDocument", "schema_revision"), ("RegionCellsDocument", "schema_revision")] {
        defs[doc]["properties"]["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
        // A satellite states the revision it belongs to; a consumer that has the root
        // compares it and rejects a mismatch rather than mixing revisions.
        defs[doc]["properties"][field]["minimum"] = Value::from(1);
    }
    defs["RegionCellsDocument"]["properties"]["region_id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    band_keyed_map(&mut defs["RegionCellsDocument"]["properties"]["cells"]);

    let schema_entry = defs["SchemaEntry"]["properties"].as_object_mut().expect("schema properties");
    schema_entry["id"]["pattern"] = Value::from(ID_PATTERN);
    schema_entry["name"]["minLength"] = Value::from(1);
    schema_entry["description"]["minLength"] = Value::from(1);
    schema_entry["revision"]["minimum"] = Value::from(1);
    schema_entry["lods"]["minItems"] = Value::from(1);
    schema_entry["bands"]["minItems"] = Value::from(1);
    schema_entry["styles"]["minItems"] = Value::from(1);

    defs["GridEntry"]["properties"]["origin_udeg"]["const"] = Value::from(GRID_ORIGIN_UDEG);
    defs["GridEntry"]["properties"]["world_side_udeg"]["const"] = Value::from(WORLD_SIDE_UDEG);

    let band = defs["BandEntry"]["properties"].as_object_mut().expect("band properties");
    band["id"]["pattern"] = Value::from(ID_PATTERN);
    band["cell_log2"]["minimum"] = Value::from(MIN_CELL_LOG2);
    band["cell_log2"]["maximum"] = Value::from(MAX_CELL_LOG2);

    defs["LodEntry"]["properties"]["band"]["pattern"] = Value::from(ID_PATTERN);
    defs["StyleAssignment"]["properties"]["feature_type"]["minLength"] = Value::from(1);
    defs["StyleAssignment"]["properties"]["id"]["minimum"] = Value::from(1);

    let skin = defs["SkinEntry"]["properties"].as_object_mut().expect("skin properties");
    skin["id"]["pattern"] = Value::from(ID_PATTERN);
    skin["name"]["minLength"] = Value::from(1);
    skin["description"]["minLength"] = Value::from(1);
    skin["styles"]["minItems"] = Value::from(1);
    defs["SkinStyle"]["properties"]["feature_type"]["minLength"] = Value::from(1);
    defs["SkinStyle"]["properties"]["priority"]["minimum"] = Value::from(1);
    defs["SkinStyle"]["properties"]["priority"]["maximum"] = Value::from(4);

    let region = defs["RegionEntry"]["properties"].as_object_mut().expect("region properties");
    region["id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    region["name"]["minLength"] = Value::from(1);
    region["cells_sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    region["cells_url"]["pattern"] = Value::from(URL_PATTERN);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["bytes_by_band"]);
    band_keyed_map(&mut defs["RegionEntry"]["properties"]["cell_count"]);

    defs["Boundary"]["description"] = Value::from(BOUNDARY_DESCRIPTION);
    defs["Boundary"]["properties"]["rings"]["minItems"] = Value::from(1);
    // A closed ring: 3 distinct points plus the repeat of the first.
    defs["Boundary"]["properties"]["rings"]["items"]["minItems"] = Value::from(4);

    let cell_ref = defs["CellIndexRef"]["properties"].as_object_mut().expect("cell index ref properties");
    cell_ref["band"]["pattern"] = Value::from(ID_PATTERN);
    cell_ref["cell_log2"]["minimum"] = Value::from(MIN_CELL_LOG2);
    cell_ref["cell_log2"]["maximum"] = Value::from(MAX_CELL_LOG2);
    cell_ref["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    cell_ref["url"]["pattern"] = Value::from(URL_PATTERN);

    defs["CellEntry"]["description"] = Value::from(CELL_DESCRIPTION);
    let cell = defs["CellEntry"]["properties"].as_object_mut().expect("cell properties");
    cell["id"]["pattern"] = Value::from(CELL_ID_PATTERN);
    cell["sha256"]["pattern"] = Value::from(SHA256_PATTERN);
    cell["url"]["pattern"] = Value::from(URL_PATTERN);
    cell["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);
    cell["sources"]["minItems"] = Value::from(1);

    defs["CellSource"]["properties"]["extract_id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    defs["CellSource"]["properties"]["snapshot"]["pattern"] = Value::from(DATE_PATTERN);

    flatten_descriptions(&mut schema);
    schema
}

/// Band-keyed object: the keys are band ids, so give them the id grammar rather than
/// letting any string through.
fn band_keyed_map(value: &mut Value) {
    value["propertyNames"] = serde_json::json!({ "pattern": ID_PATTERN });
}

/// Stable pretty representation used to regenerate the checked-in schema:
/// `obc-pack schema --catalog-v2 > host/obc-pack/schema/catalog.v2.schema.json`.
pub fn catalog_schema_json() -> String {
    let mut text = serde_json::to_string_pretty(&catalog_schema()).expect("v2 schema serializes");
    text.push('\n');
    text
}

#[cfg(test)]
mod tests;
