SELECT DISTINCT ?item ?type ?article ?image WHERE {
  hint:Query hint:optimizer "None" .
  ?item wdt:P17 wd:Q39 .
  ?item wdt:P625 ?coord; wdt:P31 ?type .
  ?article schema:about ?item; schema:isPartOf ?wiki .
  FILTER(?wiki IN (
    <https://en.wikipedia.org/>, <https://de.wikipedia.org/>,
    <https://fr.wikipedia.org/>, <https://it.wikipedia.org/>
  ))
  OPTIONAL { ?item wdt:P18 ?image . }
}
