//! `catalog.rs` — the **map catalog manifest**: the contract between the bakery
//! (which builds `.obcm` artifacts once, centrally) and every consumer that hands
//! one to a device (the hosted site, the desktop app). The repo-root `OBCC_Spec.md`
//! is the normative document; this module is its code authority and only producer.
//!
//! Two properties drive every design decision here.
//!
//! **The version law.** An OBCM format bump invalidates every baked artifact, so
//! `obcm_version` is read out of the artifact's own 40-byte header — never from
//! the builder's intent — and the generator refuses to emit a manifest that mixes
//! versions or carries a version this packer does not write. That makes a stale
//! bake a build failure instead of a map a rider's device silently cannot open.
//!
//! **Never partially consumed.** The manifest is written temp-then-`rename`, so a
//! reader either sees the whole previous file or the whole new one, and it is a
//! single self-delimiting JSON document, so a truncated body cannot parse. Both
//! halves are required; see [`write_atomic`] and `OBCC_Spec.md` §7.

use std::collections::BTreeMap;
use std::fs::{self, File};
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use sha2::{Digest, Sha256};

use obc_formats::io::rd_i32;
use obc_formats::obcm::{HEADER_LEN, MAGIC, VERSION as OBCM_VERSION};

/// Version of the manifest envelope itself. Bump only on a breaking change to the
/// document shape — adding an optional field is not one. A consumer that does not
/// recognise this number MUST reject the whole document (`OBCC_Spec.md` §7).
pub const CATALOG_SCHEMA_VERSION: u32 = 1;

/// The generated manifest schema, checked in so the hosted site can validate a
/// fetched catalog without a Rust toolchain. A pinning test keeps it identical to
/// [`catalog_schema`] — same mechanism as `schema/config.schema.json`.
pub const CATALOG_SCHEMA_JSON: &str = include_str!("../schema/catalog.schema.json");

/// A generated manifest over the checked-in synthetic bake tree, regenerated by
/// the tests. Its `obcm_version` fields are what make the stale-generation guard
/// concrete: an OBCM bump changes this file, so it cannot go unnoticed.
pub const CATALOG_EXAMPLE_JSON: &str = include_str!("../schema/catalog.example.json");

/// The OBCM format version this catalog surface was written and pinned against.
///
/// Deliberately a literal, not an alias for [`OBCM_VERSION`]: moving OBCM's version
/// constant must *break* a test, because the bump invalidates every artifact already
/// baked and published. See the `obcm_version_pin_is_deliberate` test for the
/// checklist that failure prints.
pub const PINNED_OBCM_VERSION: u8 = 10;

/// Default manifest filename inside a bake tree.
pub const DEFAULT_MANIFEST_NAME: &str = "catalog.json";

const REGIONS_DIR: &str = "regions";
const PRESETS_DIR: &str = "presets";
const ARTIFACT_EXT: &str = ".obcm";
const SIDECAR_EXT: &str = ".obcm.json";

/// Hash/copy buffer. Artifacts are hundreds of megabytes, so the file is streamed;
/// nothing in this module ever holds an artifact body in memory.
const HASH_BUF: usize = 64 * 1024;

// --- the manifest ------------------------------------------------------------------------

/// The catalog manifest: every artifact the bakery published, plus the presets they
/// were built with.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CatalogManifest {
    /// Manifest envelope version. A consumer that does not recognise it rejects the
    /// entire document rather than reading the fields it happens to understand.
    pub schema_version: u32,
    /// When this manifest was generated, RFC 3339 UTC (`YYYY-MM-DDTHH:MM:SSZ`).
    pub generated_at: String,
    /// The presets artifacts were built with, sorted by `id`. Display order is the
    /// consumer's business, not the manifest's.
    pub presets: Vec<PresetEntry>,
    /// Every published artifact, sorted by `(region_id, preset_id)`.
    pub artifacts: Vec<ArtifactEntry>,
}

/// One style preset offered to the user.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct PresetEntry {
    /// Stable preset id, e.g. `default`. Matches `preset_id` on artifacts.
    pub id: String,
    /// Display name, e.g. `Bikepacking`.
    pub name: String,
    /// One-line description of what this preset draws.
    pub description: String,
    /// Preset content version — bumped whenever the preset's styling changes, so a
    /// consumer can tell "same preset, restyled" from "same bytes".
    pub version: u32,
    /// Optional reference to a rendered preview asset, resolved against the same
    /// base URL as `url` on artifacts. Absent until the preview exists.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preview: Option<String>,
}

/// One published `.obcm` artifact: a (region, preset) pair.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct ArtifactEntry {
    /// Slash-separated region id mirroring the Geofabrik hierarchy, e.g.
    /// `europe/switzerland`. Derived from the artifact's directory path.
    pub region_id: String,
    /// Human-readable region name, e.g. `Switzerland`.
    pub region_name: String,
    /// The preset this artifact was built with; matches a `presets[].id`.
    pub preset_id: String,
    /// The preset's `version` **as recorded by the bake job that produced this
    /// artifact** — read from its sidecar, not from the preset config sitting in the
    /// tree when the manifest was generated.
    ///
    /// That distinction is the whole point of the field. A preset restyle invalidates
    /// only that preset's artifacts, so partial re-bakes are the normal operation (a
    /// full bake is ~20 CPU-hours). Copied from the current preset config it would
    /// equal `presets[].version` by construction and could never signal anything,
    /// while every not-yet-re-baked artifact silently claimed styling it does not
    /// have. Lower than the matching `presets[].version` means exactly one thing: this
    /// artifact carries older styling (`OBCC_Spec.md` §3).
    pub preset_version: u32,
    /// OBCM format version, read from the artifact's own header — never from the
    /// builder's intent. A consumer MUST refuse an artifact whose version the target
    /// firmware cannot read (`OBCC_Spec.md` §6).
    pub obcm_version: u8,
    /// Artifact size in bytes.
    pub bytes: u64,
    /// Lowercase hex SHA-256 of the artifact bytes.
    pub sha256: String,
    /// Coverage bbox, copied from the artifact header. Descriptive output, never a
    /// build input — see [`CoverageBBox`].
    pub bbox: CoverageBBox,
    /// When the artifact was packed, RFC 3339 UTC.
    pub built_at: String,
    /// Date of the OSM extract it was packed from, `YYYY-MM-DD`.
    pub source_snapshot: String,
    /// Absolute or root-relative URL the artifact can be fetched from.
    pub url: String,
}

/// The artifact's coverage bounding box in **microdegrees**, exactly as the OBCM
/// header stores it.
///
/// This is what the packed file actually covers, which is always a little wider than
/// the extract box it was cut from: complete ways and stray coastline features push
/// it out. `obc-sim/assets/repack.sh` therefore forbids feeding a header bbox back in
/// as an extract bbox — self-sourcing ratchets the box wider on every re-pack (a
/// fixture once grew to 14.5 MB that way).
///
/// That rule is about *inputs*. This field is an *output*: the honest answer to "what
/// does this download cover?", which is the only question a catalog consumer asks. It
/// MUST NOT be used as a packer input bbox, and `OBCC_Spec.md` §4 says so normatively.
///
/// Microdegrees rather than degrees, because the format's own unit is integer
/// microdegrees and integers serialize deterministically; floats would not.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
pub struct CoverageBBox {
    pub min_lat: i32,
    pub min_lon: i32,
    pub max_lat: i32,
    pub max_lon: i32,
}

/// A generated manifest plus non-fatal observations about the tree.
///
/// Warnings are returned rather than printed: the bakery decides whether a coverage
/// hole is a log line or a failed job, and tests can assert on them.
#[derive(Debug, Clone)]
pub struct GeneratedCatalog {
    pub manifest: CatalogManifest,
    pub warnings: Vec<String>,
}

/// Generator inputs that cannot be derived from the tree.
#[derive(Debug, Clone)]
pub struct CatalogOptions {
    /// Prefix every artifact `url` is built from — the location the tree is published
    /// at. Absolute `http(s)://…` or root-relative `/…`; a trailing slash is trimmed.
    pub base_url: String,
    /// The manifest's `generated_at`, RFC 3339 UTC.
    ///
    /// Passed in, not read from the clock, so the generator is a pure function of
    /// (tree, options): the same tree yields byte-identical output. The CLI fills this
    /// from the system clock when `--generated-at` is absent, and that is the *only*
    /// place a wall clock enters the manifest — `built_at` comes from the sidecars.
    pub generated_at: String,
}

// --- generation --------------------------------------------------------------------------

/// Walk a bake output tree and build the manifest.
///
/// The tree is self-describing (`OBCC_Spec.md` §8):
///
/// ```text
/// <tree>/presets/<preset_id>.json              the exact packer config used, `_meta` describes it
/// <tree>/regions/<a>/<b>/<preset_id>.obcm      the artifact; its directory path is the region id
/// <tree>/regions/<a>/<b>/<preset_id>.obcm.json its sidecar (region name, snapshot, build time)
/// ```
///
/// Per-artifact sidecars rather than one central index: a matrix bake runs one job per
/// (region, preset), and each job writes only its own two files. Nothing has to be
/// merged, so nothing can race.
pub fn generate(tree: &Path, opts: &CatalogOptions) -> Result<GeneratedCatalog, String> {
    let base_url = normalize_base_url(&opts.base_url)?;
    validate_timestamp(&opts.generated_at).map_err(|e| format!("generated_at: {e}"))?;

    let presets = read_presets(&tree.join(PRESETS_DIR))?;
    let regions_root = tree.join(REGIONS_DIR);
    if !regions_root.is_dir() {
        return Err(format!("{}: no `{REGIONS_DIR}/` directory — is this a bake tree?", tree.display()));
    }

    let mut artifacts = Vec::new();
    collect_region_dirs(&regions_root, &mut Vec::new(), &mut |region_id, dir| {
        read_region(region_id, dir, tree, &presets, &base_url, &mut artifacts)
    })?;

    if artifacts.is_empty() {
        return Err(format!("{}: no `.obcm` artifacts found — refusing to publish an empty catalog", tree.display()));
    }

    // Sorted output, so the manifest depends on the tree's content and not on the
    // order the filesystem happened to hand back directory entries.
    artifacts.sort_by(|a, b| (&a.region_id, &a.preset_id).cmp(&(&b.region_id, &b.preset_id)));

    let warnings = check_coherence(&artifacts, &presets)?;

    let manifest = CatalogManifest {
        schema_version: CATALOG_SCHEMA_VERSION,
        generated_at: opts.generated_at.clone(),
        presets: presets.into_values().collect(),
        artifacts,
    };
    Ok(GeneratedCatalog { manifest, warnings })
}

/// Stable serialization: pretty-printed with a trailing newline, so a published
/// manifest diffs line-by-line and `generate` → `manifest_json` is byte-reproducible.
///
/// Field order is struct-declaration order — `serde_json`'s `preserve_order` feature
/// (already mandatory for the packer's config) keeps maps insertion-ordered too.
pub fn manifest_json(manifest: &CatalogManifest) -> String {
    let mut text = serde_json::to_string_pretty(manifest).expect("manifest serializes");
    text.push('\n');
    text
}

/// Write the manifest so it is never observed half-written.
///
/// Temp file in the *same directory* (so the rename cannot cross a filesystem) →
/// `sync_all` → `rename`, which is atomic on every filesystem the bakery runs on. A
/// concurrent reader therefore sees either the complete previous manifest or the
/// complete new one, never a prefix of either.
///
/// That covers the local tree. The other half of "never partially consumed" is the
/// consumer's, and it is not optional: a catalog client MUST read the entire response
/// body, parse it as one JSON document, and check `schema_version` *before* using any
/// field. A single self-delimiting document is what makes that check sufficient —
/// truncation cannot survive `JSON.parse`. `OBCC_Spec.md` §7 states both halves.
pub fn write_atomic(path: &Path, manifest: &CatalogManifest) -> Result<(), String> {
    let body = manifest_json(manifest);
    let dir = path.parent().filter(|p| !p.as_os_str().is_empty()).map_or_else(|| PathBuf::from("."), Path::to_path_buf);
    // Unique per process so two generators pointed at one tree cannot corrupt each
    // other's temp file; the rename still makes the last writer win cleanly.
    let tmp = dir.join(format!(
        ".{}.tmp{}",
        path.file_name().and_then(|n| n.to_str()).unwrap_or(DEFAULT_MANIFEST_NAME),
        std::process::id()
    ));

    let write = |tmp: &Path| -> std::io::Result<()> {
        let mut f = File::create(tmp)?;
        f.write_all(body.as_bytes())?;
        // Durability before visibility: a crash between rename and writeback must not
        // leave a zero-length file where a valid manifest used to be.
        f.sync_all()
    };
    if let Err(e) = write(&tmp) {
        let _ = fs::remove_file(&tmp);
        return Err(format!("{}: {e}", tmp.display()));
    }
    if let Err(e) = fs::rename(&tmp, path) {
        let _ = fs::remove_file(&tmp);
        return Err(format!("{} -> {}: {e}", tmp.display(), path.display()));
    }
    // Best effort: persist the directory entry itself. Not portable (opening a
    // directory fails on Windows), and the rename is already atomic, so a failure
    // here is not worth aborting a good publish for.
    if let Ok(d) = File::open(&dir) {
        let _ = d.sync_all();
    }
    Ok(())
}

// --- tree walking ------------------------------------------------------------------------

/// Recurse `regions/`, calling `visit` for every directory that holds artifacts.
///
/// A directory may both hold artifacts and contain sub-regions: `regions/europe/germany`
/// can be baked while `regions/europe/germany/bayern` is baked separately, which is
/// exactly the nested-region case the region picker has to render.
fn collect_region_dirs(
    dir: &Path,
    segments: &mut Vec<String>,
    visit: &mut impl FnMut(&str, &Path) -> Result<(), String>,
) -> Result<(), String> {
    let mut subdirs = Vec::new();
    let mut has_artifacts = false;
    for entry in sorted_entries(dir)? {
        let name = file_name(&entry)?;
        // Dotfiles are tooling debris (`.DS_Store`, `.gitkeep`), never catalog content.
        if name.starts_with('.') {
            continue;
        }
        if entry.is_dir() {
            validate_id(&name).map_err(|e| format!("{}: region path segment {e}", entry.display()))?;
            subdirs.push((name, entry));
        } else if name.ends_with(SIDECAR_EXT) {
            // Paired with its artifact below; a stray sidecar is caught in read_region.
        } else if name.ends_with(ARTIFACT_EXT) {
            has_artifacts = true;
        } else {
            // Silence here would let a mis-named artifact read as "region not covered",
            // which is indistinguishable from a deliberate curation choice.
            return Err(format!("{}: unexpected entry in a region tree (expected `*{ARTIFACT_EXT}`, `*{SIDECAR_EXT}`, or a sub-region directory)", entry.display()));
        }
    }

    if has_artifacts {
        if segments.is_empty() {
            return Err(format!("{}: artifacts must live in a region directory under `{REGIONS_DIR}/`", dir.display()));
        }
        visit(&segments.join("/"), dir)?;
    }
    for (name, path) in subdirs {
        segments.push(name);
        collect_region_dirs(&path, segments, visit)?;
        segments.pop();
    }
    Ok(())
}

/// Turn one region directory into artifact entries.
fn read_region(
    region_id: &str,
    dir: &Path,
    tree: &Path,
    presets: &BTreeMap<String, PresetEntry>,
    base_url: &str,
    out: &mut Vec<ArtifactEntry>,
) -> Result<(), String> {
    let mut region_name: Option<(String, PathBuf)> = None;
    let mut sidecars = Vec::new();
    let mut artifacts = Vec::new();
    for entry in sorted_entries(dir)? {
        let name = file_name(&entry)?;
        if name.starts_with('.') || entry.is_dir() {
            continue;
        }
        if let Some(stem) = name.strip_suffix(SIDECAR_EXT) {
            sidecars.push(stem.to_string());
        } else if let Some(stem) = name.strip_suffix(ARTIFACT_EXT) {
            artifacts.push((stem.to_string(), entry));
        }
    }

    for (preset_id, path) in artifacts {
        validate_id(&preset_id).map_err(|e| format!("{}: preset id {e}", path.display()))?;
        if !presets.contains_key(&preset_id) {
            return Err(format!(
                "{}: preset `{preset_id}` is not described in `{PRESETS_DIR}/{preset_id}.json` — the tree must \
                 describe every preset it holds artifacts for",
                path.display()
            ));
        }
        let sidecar_path = path.with_file_name(format!("{preset_id}{SIDECAR_EXT}"));
        let sidecar = read_sidecar(&sidecar_path)?;
        sidecars.retain(|s| s != &preset_id);

        let header = read_obcm_header(&path)?;
        // The version law, enforced at the earliest point the answer is known and
        // against *this packer's* version rather than merely "all the same" — a
        // catalog baked entirely with last month's packer is the failure mode this
        // check exists for, and it is uniform.
        if header.version != OBCM_VERSION {
            return Err(format!(
                "{}: artifact is OBCM v{} but this obc-pack writes v{OBCM_VERSION}. An OBCM format bump invalidates \
                 every baked artifact (OBCC_Spec.md §6) — re-bake this region with the current packer. Publishing a \
                 mixed-version catalog would hand devices maps they cannot open.",
                path.display(),
                header.version
            ));
        }
        let (bytes, sha256) = hash_file(&path)?;

        // Region names come from independently-written sidecars; a disagreement means
        // two jobs disagreed about what they were baking. Fail rather than pick one.
        match &region_name {
            None => region_name = Some((sidecar.region_name.clone(), sidecar_path.clone())),
            Some((first, first_path)) if first != &sidecar.region_name => {
                return Err(format!(
                    "region `{region_id}`: conflicting region_name — `{first}` in {} but `{}` in {}",
                    first_path.display(),
                    sidecar.region_name,
                    sidecar_path.display()
                ));
            }
            Some(_) => {}
        }

        let rel =
            path.strip_prefix(tree).map_err(|_| format!("{}: artifact is outside the tree root", path.display()))?;
        let url = format!("{base_url}/{}", rel_url_path(rel)?);

        out.push(ArtifactEntry {
            region_id: region_id.to_string(),
            region_name: sidecar.region_name,
            preset_id,
            preset_version: sidecar.preset_version,
            obcm_version: header.version,
            bytes,
            sha256,
            bbox: header.bbox,
            built_at: sidecar.built_at,
            source_snapshot: sidecar.source_snapshot,
            url,
        });
    }

    if let Some(orphan) = sidecars.first() {
        return Err(format!(
            "{}: sidecar with no artifact — `{orphan}{ARTIFACT_EXT}` is missing",
            dir.join(format!("{orphan}{SIDECAR_EXT}")).display()
        ));
    }
    Ok(())
}

/// The facts a bake job knows that the artifact bytes cannot state.
///
/// Every field here is a *record of the bake*, fixed when the artifact was written.
/// Nothing in this struct may be re-derived at generation time from the tree's current
/// state — that is what lets the manifest describe an artifact the tree has since
/// moved past.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct ArtifactSidecar {
    region_name: String,
    /// The `_meta.version` of the preset config this artifact was actually packed
    /// with. Recorded here rather than read back off the tree's preset config, which
    /// the next restyle moves out from under already-baked artifacts.
    preset_version: u32,
    /// RFC 3339 UTC instant the artifact was packed.
    built_at: String,
    /// `YYYY-MM-DD` date of the Geofabrik extract it was packed from.
    source_snapshot: String,
}

fn read_sidecar(path: &Path) -> Result<ArtifactSidecar, String> {
    let text = fs::read_to_string(path).map_err(|e| {
        format!(
            "{}: {e} — every artifact needs a sidecar (region_name, preset_version, built_at, source_snapshot)",
            path.display()
        )
    })?;
    let sidecar: ArtifactSidecar = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
    if sidecar.region_name.trim().is_empty() {
        return Err(format!("{}: region_name is empty", path.display()));
    }
    validate_timestamp(&sidecar.built_at).map_err(|e| format!("{}: built_at {e}", path.display()))?;
    validate_date(&sidecar.source_snapshot).map_err(|e| format!("{}: source_snapshot {e}", path.display()))?;
    Ok(sidecar)
}

/// `_meta` from a packer preset config. The preset file in the tree is the **current**
/// definition of a preset: it names and describes it, and its `version` is what a fresh
/// bake would produce. What an already-baked artifact was built with is its sidecar's
/// business, not this file's.
#[derive(Debug, Deserialize)]
struct PresetDoc {
    #[serde(rename = "_meta")]
    meta: Option<PresetMeta>,
}

#[derive(Debug, Deserialize)]
struct PresetMeta {
    id: String,
    name: String,
    description: String,
    version: u32,
    /// Filled in once a rendered preview asset exists; other `_meta` keys the web
    /// builder uses (`swatch`, `palette_note`) are deliberately not in the catalog.
    #[serde(default)]
    preview: Option<String>,
}

fn read_presets(dir: &Path) -> Result<BTreeMap<String, PresetEntry>, String> {
    if !dir.is_dir() {
        return Err(format!(
            "{}: no `{PRESETS_DIR}/` directory — the bake tree must describe every preset it holds artifacts for",
            dir.display()
        ));
    }
    let mut presets = BTreeMap::new();
    for path in sorted_entries(dir)? {
        let name = file_name(&path)?;
        if name.starts_with('.') || path.is_dir() {
            continue;
        }
        let Some(stem) = name.strip_suffix(".json") else {
            return Err(format!(
                "{}: only `<preset_id>.json` preset configs belong in `{PRESETS_DIR}/`",
                path.display()
            ));
        };
        validate_id(stem).map_err(|e| format!("{}: preset id {e}", path.display()))?;
        let text = fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
        let doc: PresetDoc = serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
        let meta = doc.meta.ok_or_else(|| {
            format!("{}: preset config has no `_meta` block (id, name, description, version)", path.display())
        })?;
        if meta.id != stem {
            return Err(format!("{}: `_meta.id` is `{}` but the filename says `{stem}`", path.display(), meta.id));
        }
        if meta.name.trim().is_empty() || meta.description.trim().is_empty() {
            return Err(format!("{}: `_meta.name` and `_meta.description` must be non-empty", path.display()));
        }
        presets.insert(
            stem.to_string(),
            PresetEntry {
                id: meta.id,
                name: meta.name,
                description: meta.description,
                version: meta.version,
                preview: meta.preview,
            },
        );
    }
    if presets.is_empty() {
        return Err(format!("{}: no preset configs found", dir.display()));
    }
    Ok(presets)
}

/// Cross-artifact rules. Everything fatal here would otherwise ship a catalog a
/// device cannot use; everything merely surprising comes back as a warning.
fn check_coherence(
    artifacts: &[ArtifactEntry],
    presets: &BTreeMap<String, PresetEntry>,
) -> Result<Vec<String>, String> {
    // A preset nobody built is a preset the picker would offer and then fail to serve.
    let mut used: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for a in artifacts {
        used.entry(a.preset_id.as_str()).or_default().push(a.region_id.as_str());
    }
    for id in presets.keys() {
        if !used.contains_key(id.as_str()) {
            return Err(format!(
                "preset `{id}` is described in `{PRESETS_DIR}/` but no artifact uses it — either bake it or drop the \
                 preset; a catalog must not advertise a preset it cannot serve"
            ));
        }
    }

    let mut warnings = Vec::new();

    // Artifact vs. the tree's current preset config. Now that `preset_version` records
    // the bake instead of mirroring the tree, the two can disagree — and each direction
    // means something different.
    for a in artifacts {
        // `read_region` already refused an artifact whose preset is undescribed.
        let Some(current) = presets.get(a.preset_id.as_str()) else { continue };
        match a.preset_version.cmp(&current.version) {
            // Artifact newer than the config that supposedly describes it: the tree is
            // internally inconsistent (a reverted preset, or one copied in from the
            // wrong place), and the catalog cannot describe that artifact honestly.
            std::cmp::Ordering::Greater => {
                return Err(format!(
                    "region `{}` preset `{}`: the artifact was baked at preset version {} but \
                     `{PRESETS_DIR}/{}.json` is only version {} — the tree's preset config is older than an artifact \
                     built from it, so the catalog cannot describe that artifact's styling. Update the preset config \
                     in the tree, or re-bake the region.",
                    a.region_id, a.preset_id, a.preset_version, a.preset_id, current.version
                ));
            }
            // Artifact older: a lagging partial re-bake. Deliberately NOT fatal. Unlike
            // an OBCM bump the artifact is perfectly readable — it is styled the way the
            // preset looked last month — so refusing to publish would turn a cosmetic lag
            // into total unavailability for every region not yet re-baked, and make a
            // ~20 CPU-hour full bake a precondition for any publish. The manifest states
            // the lag truthfully instead; §3 defines what a consumer may conclude. B1
            // owns whether a lag blocks a given publish: that is policy, and it gets
            // this list.
            std::cmp::Ordering::Less => warnings.push(format!(
                "region `{}` preset `{}`: artifact was baked at preset version {}, but the tree's preset is now \
                 version {} — it carries older styling until re-baked",
                a.region_id, a.preset_id, a.preset_version, current.version
            )),
            std::cmp::Ordering::Equal => {}
        }
    }

    // Coverage holes are legitimate (a bake can be partial) but never silent: a
    // region that quietly failed for one preset reads to a user as a curation choice.
    let mut by_region: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for a in artifacts {
        by_region.entry(a.region_id.as_str()).or_default().push(a.preset_id.as_str());
    }
    for (region, built) in &by_region {
        let missing: Vec<&str> = presets.keys().map(String::as_str).filter(|p| !built.contains(p)).collect();
        if !missing.is_empty() {
            warnings.push(format!("region `{region}` is missing preset(s): {}", missing.join(", ")));
        }
    }
    Ok(warnings)
}

// --- artifact inspection -----------------------------------------------------------------

struct ObcmHeader {
    version: u8,
    bbox: CoverageBBox,
}

/// Read the OBCM version and coverage bbox out of the artifact's own 40-byte header.
///
/// The whole point of the manifest's version field is that it describes the bytes that
/// will be downloaded, so it is read from those bytes. The layout is `OBCM_Spec.md` §1
/// (magic, version, then the bbox stored **lat, lon, lat, lon**).
fn read_obcm_header(path: &Path) -> Result<ObcmHeader, String> {
    let mut f = File::open(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let mut h = [0u8; HEADER_LEN];
    f.read_exact(&mut h).map_err(|e| {
        format!("{}: {e} — too short to be an OBCM artifact ({HEADER_LEN}-byte header)", path.display())
    })?;
    if h[..4] != MAGIC {
        return Err(format!("{}: not an OBCM file (bad magic)", path.display()));
    }
    let bbox = CoverageBBox {
        min_lat: rd_i32(&h, 5),
        min_lon: rd_i32(&h, 9),
        max_lat: rd_i32(&h, 13),
        max_lon: rd_i32(&h, 17),
    };
    if bbox.min_lat > bbox.max_lat || bbox.min_lon > bbox.max_lon {
        return Err(format!("{}: header bbox is inverted ({bbox:?})", path.display()));
    }
    if bbox.min_lat < -90_000_000
        || bbox.max_lat > 90_000_000
        || bbox.min_lon < -180_000_000
        || bbox.max_lon > 180_000_000
    {
        return Err(format!("{}: header bbox is outside the world ({bbox:?})", path.display()));
    }
    Ok(ObcmHeader { version: h[4], bbox })
}

/// Stream the file, returning `(bytes, lowercase hex sha256)`.
///
/// Streamed because artifacts are hundreds of megabytes; the byte count comes from the
/// stream rather than the directory entry, and is cross-checked against it, so a file
/// rewritten mid-hash fails loudly instead of publishing a hash for bytes that no
/// longer exist.
fn hash_file(path: &Path) -> Result<(u64, String), String> {
    let mut f = File::open(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let declared = f.metadata().map_err(|e| format!("{}: {e}", path.display()))?.len();
    let mut hasher = Sha256::new();
    let mut buf = vec![0u8; HASH_BUF];
    let mut total = 0u64;
    loop {
        let n = f.read(&mut buf).map_err(|e| format!("{}: {e}", path.display()))?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
        total += n as u64;
    }
    if total != declared {
        return Err(format!(
            "{}: changed while being hashed ({declared} bytes declared, {total} read)",
            path.display()
        ));
    }
    Ok((total, hex(&hasher.finalize())))
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        use std::fmt::Write;
        let _ = write!(s, "{b:02x}");
    }
    s
}

// --- small helpers -----------------------------------------------------------------------

/// Directory entries in a stable order. `read_dir` order is filesystem-dependent, so
/// sorting here is what makes the whole generator reproducible.
fn sorted_entries(dir: &Path) -> Result<Vec<PathBuf>, String> {
    let mut paths = Vec::new();
    for entry in fs::read_dir(dir).map_err(|e| format!("{}: {e}", dir.display()))? {
        paths.push(entry.map_err(|e| format!("{}: {e}", dir.display()))?.path());
    }
    paths.sort();
    Ok(paths)
}

fn file_name(path: &Path) -> Result<String, String> {
    path.file_name()
        .and_then(|n| n.to_str())
        .map(str::to_string)
        .ok_or_else(|| format!("{}: non-UTF-8 filename", path.display()))
}

/// Region path segments and preset ids share one lowercase-kebab vocabulary: they end
/// up in URLs and in the site's region join, so `Switzerland/` and `switzerland/` must
/// not be able to coexist.
fn validate_id(id: &str) -> Result<(), String> {
    if id.is_empty() {
        return Err("`` is empty".to_string());
    }
    let ok = id
        .split('-')
        .all(|part| !part.is_empty() && part.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit()));
    if !ok {
        return Err(format!("`{id}` must be lowercase kebab-case (a-z, 0-9, single hyphens)"));
    }
    Ok(())
}

fn rel_url_path(rel: &Path) -> Result<String, String> {
    let mut parts = Vec::new();
    for c in rel.components() {
        match c {
            std::path::Component::Normal(s) => {
                parts.push(s.to_str().ok_or_else(|| format!("{}: non-UTF-8 path", rel.display()))?)
            }
            _ => return Err(format!("{}: unexpected path component", rel.display())),
        }
    }
    Ok(parts.join("/"))
}

/// The publish location. Kept deliberately narrow: anything a browser cannot resolve
/// against the catalog's own origin is a mistake worth catching at bake time.
fn normalize_base_url(base: &str) -> Result<String, String> {
    let trimmed = base.trim_end_matches('/');
    if trimmed.is_empty() {
        return Err("base URL is empty".to_string());
    }
    let absolute = trimmed.starts_with("https://") || trimmed.starts_with("http://");
    if !absolute && !trimmed.starts_with('/') {
        return Err(format!("base URL `{base}` must be absolute (`https://…`) or root-relative (`/…`)"));
    }
    if trimmed.chars().any(char::is_whitespace) {
        return Err(format!("base URL `{base}` contains whitespace"));
    }
    Ok(trimmed.to_string())
}

// --- timestamps --------------------------------------------------------------------------
//
// One strict spelling, `YYYY-MM-DDTHH:MM:SSZ`: no offsets, no fractional seconds, no
// lowercase `z`. A catalog's timestamps are compared and sorted by consumers in three
// languages; one spelling makes string comparison correct, and rejecting the rest at
// bake time is cheaper than discovering the variants later.

/// Validate `YYYY-MM-DDTHH:MM:SSZ` and return the instant as a Unix timestamp.
pub fn validate_timestamp(s: &str) -> Result<i64, String> {
    let bytes = s.as_bytes();
    if bytes.len() != 20 || bytes[10] != b'T' || bytes[19] != b'Z' {
        return Err(format!("`{s}` is not an RFC 3339 UTC instant (YYYY-MM-DDTHH:MM:SSZ)"));
    }
    let days = civil_days(&s[..10]).map_err(|e| format!("`{s}`: {e}"))?;
    let (h, m, sec) = (num(&s[11..13])?, num(&s[14..16])?, num(&s[17..19])?);
    if s.as_bytes()[13] != b':' || s.as_bytes()[16] != b':' {
        return Err(format!("`{s}` is not an RFC 3339 UTC instant (YYYY-MM-DDTHH:MM:SSZ)"));
    }
    // 60 would be a leap second; the format has no room for one and no consumer wants it.
    if h > 23 || m > 59 || sec > 59 {
        return Err(format!("`{s}` has an out-of-range time"));
    }
    Ok(days * 86_400 + i64::from(h) * 3_600 + i64::from(m) * 60 + i64::from(sec))
}

/// Validate `YYYY-MM-DD` (the Geofabrik extract date).
pub fn validate_date(s: &str) -> Result<(), String> {
    if s.len() != 10 {
        return Err(format!("`{s}` is not a YYYY-MM-DD date"));
    }
    civil_days(s).map(|_| ()).map_err(|e| format!("`{s}`: {e}"))
}

/// Format a Unix timestamp as `YYYY-MM-DDTHH:MM:SSZ`.
///
/// Hand-rolled rather than pulling a date crate in for one call site: the packer's
/// only use of civil time is stamping `generated_at`.
pub fn format_timestamp(unix: i64) -> String {
    let days = unix.div_euclid(86_400);
    let secs = unix.rem_euclid(86_400);
    let (y, m, d) = civil_from_days(days);
    format!("{y:04}-{m:02}-{d:02}T{:02}:{:02}:{:02}Z", secs / 3600, (secs % 3600) / 60, secs % 60)
}

/// `generated_at` for a run with no explicit `--generated-at`. The single place this
/// crate reads a wall clock.
pub fn now_timestamp() -> String {
    let secs = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map_or(0, |d| d.as_secs() as i64);
    format_timestamp(secs)
}

fn num(s: &str) -> Result<u32, String> {
    s.parse::<u32>().map_err(|_| format!("`{s}` is not a number"))
}

/// Days since 1970-01-01 for a validated `YYYY-MM-DD`, rejecting impossible dates
/// (2026-02-30 parses digit-wise but is not a day).
fn civil_days(date: &str) -> Result<i64, String> {
    let b = date.as_bytes();
    if b.len() != 10 || b[4] != b'-' || b[7] != b'-' {
        return Err("not a YYYY-MM-DD date".to_string());
    }
    let (y, m, d) = (num(&date[..4])? as i64, num(&date[5..7])?, num(&date[8..10])?);
    if !(1..=12).contains(&m) || d < 1 || d > days_in_month(y, m) {
        return Err("is not a real calendar date".to_string());
    }
    Ok(days_from_civil(y, m, d))
}

fn is_leap(y: i64) -> bool {
    (y % 4 == 0 && y % 100 != 0) || y % 400 == 0
}

fn days_in_month(y: i64, m: u32) -> u32 {
    match m {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if is_leap(y) => 29,
        2 => 28,
        _ => 0,
    }
}

/// Howard Hinnant's `days_from_civil`: the proleptic Gregorian day number, shifted so
/// 1970-01-01 is day 0.
fn days_from_civil(y: i64, m: u32, d: u32) -> i64 {
    let y = if m <= 2 { y - 1 } else { y };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = y - era * 400;
    let mp = i64::from((m + 9) % 12);
    let doy = (153 * mp + 2) / 5 + i64::from(d) - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era * 146_097 + doe - 719_468
}

/// Inverse of [`days_from_civil`].
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = (doy - (153 * mp + 2) / 5 + 1) as u32;
    let m = if mp < 10 { mp + 3 } else { mp - 9 } as u32;
    (if m <= 2 { y + 1 } else { y }, m, d)
}

// --- schema ------------------------------------------------------------------------------

/// Generate the manifest's JSON Schema from the same serde model the generator writes
/// and consumers deserialize, then add the constraints Rust types cannot express
/// (hex/timestamp patterns, coordinate ranges, the pinned envelope version).
pub fn catalog_schema() -> Value {
    let mut schema = serde_json::to_value(schemars::schema_for!(CatalogManifest)).expect("catalog schema serializes");
    let root = schema.as_object_mut().expect("root schema is an object");
    root.insert("$schema".into(), Value::String("https://json-schema.org/draft/2020-12/schema".into()));
    root.insert("title".into(), Value::String("OpenBikeComputer map catalog".into()));
    root.insert("description".into(), Value::String(CATALOG_DESCRIPTION.into()));

    let props = root.get_mut("properties").and_then(Value::as_object_mut).expect("catalog properties");
    // A consumer validating against this schema is validating against *its* envelope
    // version; a future v2 manifest must fail here rather than half-parse.
    props["schema_version"]["const"] = Value::from(CATALOG_SCHEMA_VERSION);
    props["generated_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);

    let defs = root.get_mut("$defs").and_then(Value::as_object_mut).expect("catalog definitions");
    let artifact = defs["ArtifactEntry"]["properties"].as_object_mut().expect("artifact properties");
    artifact["region_id"]["pattern"] = Value::from(REGION_ID_PATTERN);
    artifact["preset_id"]["pattern"] = Value::from(ID_PATTERN);
    artifact["sha256"]["pattern"] = Value::from("^[0-9a-f]{64}$");
    artifact["built_at"]["pattern"] = Value::from(TIMESTAMP_PATTERN);
    artifact["source_snapshot"]["pattern"] = Value::from(DATE_PATTERN);
    artifact["url"]["pattern"] = Value::from("^(https?://|/)");
    artifact["region_name"]["minLength"] = Value::from(1);

    let preset = defs["PresetEntry"]["properties"].as_object_mut().expect("preset properties");
    preset["id"]["pattern"] = Value::from(ID_PATTERN);
    preset["name"]["minLength"] = Value::from(1);
    preset["description"]["minLength"] = Value::from(1);

    // The struct's rustdoc argues the header-bbox decision at length for a reader of
    // the code; the schema wants the one-sentence contract.
    defs["CoverageBBox"]["description"] = Value::from(BBOX_DESCRIPTION);
    let bbox = defs["CoverageBBox"]["properties"].as_object_mut().expect("bbox properties");
    for f in ["min_lat", "max_lat"] {
        bound(bbox, f, -90_000_000, 90_000_000);
    }
    for f in ["min_lon", "max_lon"] {
        bound(bbox, f, -180_000_000, 180_000_000);
    }

    flatten_descriptions(&mut schema);
    schema
}

/// Doc comments arrive with the source's hard line wraps baked in. The schema is a
/// published artifact a JSON-Schema-aware editor renders, so collapse each description
/// to one line.
fn flatten_descriptions(value: &mut Value) {
    match value {
        Value::Object(map) => {
            if let Some(Value::String(d)) = map.get_mut("description") {
                *d = d.split_whitespace().collect::<Vec<_>>().join(" ");
            }
            for (_, v) in map.iter_mut() {
                flatten_descriptions(v);
            }
        }
        Value::Array(items) => items.iter_mut().for_each(flatten_descriptions),
        _ => {}
    }
}

fn bound(props: &mut Map<String, Value>, field: &str, min: i64, max: i64) {
    props[field]["minimum"] = Value::from(min);
    props[field]["maximum"] = Value::from(max);
}

/// Stable pretty representation used to regenerate the checked-in schema:
/// `obc-pack schema --catalog > obc-pack/schema/catalog.schema.json`.
pub fn catalog_schema_json() -> String {
    let mut text = serde_json::to_string_pretty(&catalog_schema()).expect("catalog schema serializes");
    text.push('\n');
    text
}

const TIMESTAMP_PATTERN: &str = "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$";
const DATE_PATTERN: &str = "^[0-9]{4}-[0-9]{2}-[0-9]{2}$";
const ID_PATTERN: &str = "^[a-z0-9]+(-[a-z0-9]+)*$";
const REGION_ID_PATTERN: &str = "^[a-z0-9]+(-[a-z0-9]+)*(/[a-z0-9]+(-[a-z0-9]+)*)*$";
const BBOX_DESCRIPTION: &str = "What the packed artifact actually covers, in integer microdegrees, copied from its \
                                OBCM header. Always a little wider than the extract box it was cut from (complete \
                                ways, stray coastline). Descriptive output only: it MUST NOT be fed back as a packer \
                                input bbox — see OBCC_Spec.md §4.";
const CATALOG_DESCRIPTION: &str = "The manifest of pre-baked .obcm maps: what exists, what it covers, what it was \
                                   built from, and which OBCM format version it is. `obcm_version` is read from each \
                                   artifact's own header, so a consumer can refuse a map the target firmware cannot \
                                   read before downloading it. Normative contract: OBCC_Spec.md.";

#[cfg(test)]
mod tests {
    use super::*;

    use obc_formats::io::put_i32;

    // --- fixture bake trees ---------------------------------------------------------------

    /// A scratch directory that removes itself. The packer already builds its temp
    /// paths by hand (`main.rs`), so tests do the same rather than adding a dep.
    struct TempTree(PathBuf);

    impl TempTree {
        fn new(tag: &str) -> TempTree {
            let mut p = std::env::temp_dir();
            p.push(format!("obc-catalog-{tag}-{}-{:?}", std::process::id(), std::thread::current().id()));
            let _ = fs::remove_dir_all(&p);
            fs::create_dir_all(&p).expect("temp tree");
            TempTree(p)
        }
        fn path(&self) -> &Path {
            &self.0
        }
    }

    impl Drop for TempTree {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    /// A minimal but *real* OBCM header: magic, version, bbox. Everything the catalog
    /// generator reads, and nothing it does not.
    fn obcm_bytes(version: u8, bbox: CoverageBBox, pad: usize) -> Vec<u8> {
        let mut h = vec![0u8; HEADER_LEN + pad];
        h[..4].copy_from_slice(&MAGIC);
        h[4] = version;
        put_i32(&mut h, 5, bbox.min_lat);
        put_i32(&mut h, 9, bbox.min_lon);
        put_i32(&mut h, 13, bbox.max_lat);
        put_i32(&mut h, 17, bbox.max_lon);
        h
    }

    fn write(path: &Path, body: &str) {
        fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
        fs::write(path, body).expect("write");
    }

    fn write_preset(tree: &Path, id: &str, name: &str, description: &str, version: u32, preview: Option<&str>) {
        // `swatch` is a real `_meta` key the web builder uses; it rides along here to
        // prove the catalog reads only the keys it documents.
        let preview = preview.map_or(String::new(), |p| format!(r#", "preview": "{p}""#));
        write(
            &tree.join(PRESETS_DIR).join(format!("{id}.json")),
            &format!(
                r##"{{"_meta": {{"id": "{id}", "name": "{name}", "description": "{description}",
                    "version": {version}, "swatch": ["#FF5500"]{preview}}}, "features": {{}}}}"##
            ),
        );
    }

    fn write_artifact(tree: &Path, region: &str, preset: &str, version: u8, bbox: CoverageBBox, pad: usize) {
        let dir = tree.join(REGIONS_DIR).join(region);
        fs::create_dir_all(&dir).expect("mkdir");
        fs::write(dir.join(format!("{preset}{ARTIFACT_EXT}")), obcm_bytes(version, bbox, pad)).expect("artifact");
    }

    /// Write a sidecar. `preset_version` is what the *bake* recorded — tests that
    /// care about lag pass a different number from the tree's preset config.
    fn write_sidecar(
        tree: &Path,
        region: &str,
        preset: &str,
        name: &str,
        preset_version: u32,
        built: &str,
        snapshot: &str,
    ) {
        write(
            &tree.join(REGIONS_DIR).join(region).join(format!("{preset}{SIDECAR_EXT}")),
            &format!(
                "{{\n  \"region_name\": \"{name}\",\n  \"preset_version\": {preset_version},\n  \
                 \"built_at\": \"{built}\",\n  \"source_snapshot\": \"{snapshot}\"\n}}\n"
            ),
        );
    }

    fn bbox(min_lat: i32, min_lon: i32, max_lat: i32, max_lon: i32) -> CoverageBBox {
        CoverageBBox { min_lat, min_lon, max_lat, max_lon }
    }

    fn opts() -> CatalogOptions {
        CatalogOptions {
            base_url: "https://maps.example.org/catalog/v1/".into(),
            generated_at: "2026-07-26T09:00:00Z".into(),
        }
    }

    /// The canonical tree the checked-in example manifest is generated from: two
    /// regions (one nested under the other, the Geofabrik parent/child case) × two
    /// presets, with one deliberate coverage hole.
    fn example_tree(tree: &Path) {
        write_preset(tree, "default", "Bikepacking", DEFAULT_BLURB, 3, Some("previews/default.png"));
        // No preview yet — `preview` is optional until B2 renders one, and the example
        // shows both shapes so the site is built against reality.
        write_preset(tree, "minimal", "Minimal", MINIMAL_BLURB, 2, None);

        write_artifact(
            tree,
            "europe/switzerland",
            "default",
            OBCM_VERSION,
            bbox(45_817_995, 5_955_911, 47_808_455, 10_492_294),
            1_024,
        );
        write_sidecar(tree, "europe/switzerland", "default", "Switzerland", 3, "2026-07-20T02:14:07Z", "2026-07-19");
        write_artifact(
            tree,
            "europe/switzerland",
            "minimal",
            OBCM_VERSION,
            bbox(45_817_995, 5_955_911, 47_808_455, 10_492_294),
            512,
        );
        write_sidecar(tree, "europe/switzerland", "minimal", "Switzerland", 2, "2026-07-20T02:31:55Z", "2026-07-19");

        // A sub-region baked separately from its parent — the nested case the picker
        // has to get right.
        write_artifact(
            tree,
            "europe/switzerland/ticino",
            "default",
            OBCM_VERSION,
            bbox(45_817_995, 8_380_000, 46_630_000, 9_170_000),
            256,
        );
        write_sidecar(tree, "europe/switzerland/ticino", "default", "Ticino", 3, "2026-07-20T02:41:02Z", "2026-07-19");

        write_artifact(
            tree,
            "europe/monaco",
            "default",
            OBCM_VERSION,
            bbox(43_724_355, 7_409_055, 43_751_930, 7_439_812),
            128,
        );
        write_sidecar(tree, "europe/monaco", "default", "Monaco", 3, "2026-07-20T02:44:19Z", "2026-07-19");
        write_artifact(
            tree,
            "europe/monaco",
            "minimal",
            OBCM_VERSION,
            bbox(43_724_355, 7_409_055, 43_751_930, 7_439_812),
            64,
        );
        write_sidecar(tree, "europe/monaco", "minimal", "Monaco", 2, "2026-07-20T02:44:41Z", "2026-07-19");
    }

    const DEFAULT_BLURB: &str =
        "The full touring map: roads by class, trails and cycleways, rail, water, forests and landuse.";
    const MINIMAL_BLURB: &str = "The big picture: major roads, rail, rivers and lakes. Small files, fast builds.";

    fn generated(tree: &Path) -> GeneratedCatalog {
        generate(tree, &opts()).expect("example tree generates")
    }

    // --- shape ----------------------------------------------------------------------------

    #[test]
    fn walks_a_tree_into_sorted_artifacts() {
        let t = TempTree::new("walk");
        example_tree(t.path());
        let g = generated(t.path());

        let ids: Vec<(&str, &str)> =
            g.manifest.artifacts.iter().map(|a| (a.region_id.as_str(), a.preset_id.as_str())).collect();
        assert_eq!(
            ids,
            [
                ("europe/monaco", "default"),
                ("europe/monaco", "minimal"),
                ("europe/switzerland", "default"),
                ("europe/switzerland", "minimal"),
                ("europe/switzerland/ticino", "default"),
            ],
            "artifacts sort by (region_id, preset_id); a nested region is its own entry"
        );
        assert_eq!(g.manifest.presets.iter().map(|p| p.id.as_str()).collect::<Vec<_>>(), ["default", "minimal"]);
        assert_eq!(g.manifest.schema_version, CATALOG_SCHEMA_VERSION);
        assert_eq!(g.warnings, ["region `europe/switzerland/ticino` is missing preset(s): minimal"]);
    }

    #[test]
    fn artifact_facts_come_from_the_bytes_and_the_sidecar() {
        let t = TempTree::new("facts");
        example_tree(t.path());
        let g = generated(t.path());
        let a =
            g.manifest.artifacts.iter().find(|a| a.region_id == "europe/monaco" && a.preset_id == "minimal").unwrap();

        assert_eq!(a.obcm_version, OBCM_VERSION, "version is read from the header, not assumed");
        assert_eq!(a.bytes, (HEADER_LEN + 64) as u64);
        assert_eq!(a.bbox, bbox(43_724_355, 7_409_055, 43_751_930, 7_439_812));
        assert_eq!(a.region_name, "Monaco");
        assert_eq!(a.built_at, "2026-07-20T02:44:41Z");
        assert_eq!(a.source_snapshot, "2026-07-19");
        assert_eq!(a.preset_version, 2, "preset_version comes from the sidecar the bake job wrote");
        assert_eq!(a.url, "https://maps.example.org/catalog/v1/regions/europe/monaco/minimal.obcm");
        assert_eq!(a.sha256.len(), 64);
        assert!(a.sha256.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit()), "lowercase hex");
    }

    /// Known-answer test for the hash encoding: NIST's SHA-256 of "abc".
    #[test]
    fn sha256_is_lowercase_hex_of_the_file_bytes() {
        let t = TempTree::new("sha");
        let p = t.path().join("abc.bin");
        fs::write(&p, b"abc").unwrap();
        assert_eq!(
            hash_file(&p).unwrap(),
            (3, "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad".to_string())
        );
    }

    // --- determinism ------------------------------------------------------------------------

    #[test]
    fn generation_is_deterministic_for_a_given_tree() {
        let a = TempTree::new("det-a");
        example_tree(a.path());
        let first = manifest_json(&generated(a.path()).manifest);
        let second = manifest_json(&generated(a.path()).manifest);
        assert_eq!(first, second, "running the generator twice over one tree must be byte-identical");

        // A second tree built by a different code path (same content, different
        // creation order, different directory) must produce the same bytes: this is
        // what proves the ordering is content-derived, not `read_dir`-derived.
        let b = TempTree::new("det-b");
        write_preset(b.path(), "minimal", "Minimal", MINIMAL_BLURB, 2, None);
        write_artifact(
            b.path(),
            "europe/monaco",
            "minimal",
            OBCM_VERSION,
            bbox(43_724_355, 7_409_055, 43_751_930, 7_439_812),
            64,
        );
        write_sidecar(b.path(), "europe/monaco", "minimal", "Monaco", 2, "2026-07-20T02:44:41Z", "2026-07-19");
        write_artifact(
            b.path(),
            "europe/switzerland/ticino",
            "default",
            OBCM_VERSION,
            bbox(45_817_995, 8_380_000, 46_630_000, 9_170_000),
            256,
        );
        write_sidecar(
            b.path(),
            "europe/switzerland/ticino",
            "default",
            "Ticino",
            3,
            "2026-07-20T02:41:02Z",
            "2026-07-19",
        );
        write_artifact(
            b.path(),
            "europe/monaco",
            "default",
            OBCM_VERSION,
            bbox(43_724_355, 7_409_055, 43_751_930, 7_439_812),
            128,
        );
        write_sidecar(b.path(), "europe/monaco", "default", "Monaco", 3, "2026-07-20T02:44:19Z", "2026-07-19");
        write_artifact(
            b.path(),
            "europe/switzerland",
            "minimal",
            OBCM_VERSION,
            bbox(45_817_995, 5_955_911, 47_808_455, 10_492_294),
            512,
        );
        write_sidecar(
            b.path(),
            "europe/switzerland",
            "minimal",
            "Switzerland",
            2,
            "2026-07-20T02:31:55Z",
            "2026-07-19",
        );
        write_artifact(
            b.path(),
            "europe/switzerland",
            "default",
            OBCM_VERSION,
            bbox(45_817_995, 5_955_911, 47_808_455, 10_492_294),
            1_024,
        );
        write_sidecar(
            b.path(),
            "europe/switzerland",
            "default",
            "Switzerland",
            3,
            "2026-07-20T02:14:07Z",
            "2026-07-19",
        );
        write_preset(b.path(), "default", "Bikepacking", DEFAULT_BLURB, 3, Some("previews/default.png"));
        assert_eq!(first, manifest_json(&generated(b.path()).manifest), "output must not depend on creation order");
    }

    #[test]
    fn only_generated_at_carries_a_clock() {
        let t = TempTree::new("clock");
        example_tree(t.path());
        let mut o = opts();
        o.generated_at = "2030-01-01T00:00:00Z".into();
        let later = generate(t.path(), &o).unwrap().manifest;
        let base = generated(t.path()).manifest;
        assert_ne!(base.generated_at, later.generated_at);
        assert_eq!(base.artifacts, later.artifacts, "nothing but generated_at may move with the clock");
    }

    #[test]
    fn write_atomic_leaves_no_temp_file_behind() {
        let t = TempTree::new("atomic");
        example_tree(t.path());
        let m = generated(t.path()).manifest;
        let out = t.path().join(DEFAULT_MANIFEST_NAME);
        write_atomic(&out, &m).expect("atomic write");
        assert_eq!(fs::read_to_string(&out).unwrap(), manifest_json(&m));

        let leftovers: Vec<String> = sorted_entries(t.path())
            .unwrap()
            .iter()
            .filter_map(|p| file_name(p).ok())
            .filter(|n| n.contains(".tmp"))
            .collect();
        assert!(leftovers.is_empty(), "temp files must be renamed away, not left in the tree: {leftovers:?}");

        // And it overwrites in place, so a re-publish keeps the same path.
        write_atomic(&out, &m).expect("second atomic write");
        assert_eq!(fs::read_to_string(&out).unwrap(), manifest_json(&m));
    }

    // --- the version law --------------------------------------------------------------------

    #[test]
    fn an_artifact_from_another_obcm_version_is_refused() {
        let t = TempTree::new("stale-artifact");
        example_tree(t.path());
        write_artifact(
            t.path(),
            "europe/monaco",
            "minimal",
            OBCM_VERSION - 1,
            bbox(43_724_355, 7_409_055, 43_751_930, 7_439_812),
            64,
        );
        let err = generate(t.path(), &opts()).expect_err("a stale artifact must fail the bake");
        assert!(err.contains(&format!("OBCM v{}", OBCM_VERSION - 1)), "{err}");
        assert!(err.contains("re-bake"), "the error must say what to do: {err}");
    }

    /// The stale-generation guard.
    ///
    /// [`PINNED_OBCM_VERSION`] is a literal on purpose. Bumping OBCM's `VERSION`
    /// invalidates every artifact already baked and published, so it must not be
    /// possible to do it and leave the catalog path untouched.
    #[test]
    fn obcm_version_pin_is_deliberate() {
        assert_eq!(
            OBCM_VERSION, PINNED_OBCM_VERSION,
            "OBCM's format version moved from v{PINNED_OBCM_VERSION} to v{OBCM_VERSION}, which invalidates every \
             baked map catalog artifact (OBCC_Spec.md §6). Do all four, in order:\n  \
             1. re-bake the whole catalog with the new packer (B1) — every published .obcm is now unreadable;\n  \
             2. republish the manifest, so `obcm_version` reports v{OBCM_VERSION} before anyone downloads 200 MB;\n  \
             3. regenerate the checked-in example: `OBC_UPDATE_CATALOG_EXAMPLE=1 cargo test -p obc-pack \
             catalog_example_is_current`;\n  \
             4. set catalog.rs's PINNED_OBCM_VERSION to {OBCM_VERSION}.\n\
             Changing only step 4 to make this test pass ships maps devices cannot open."
        );
    }

    /// The other half of the guard: the checked-in example must have been regenerated
    /// through the real generator, so its `obcm_version` cannot be stale.
    #[test]
    fn catalog_example_is_current() {
        let t = TempTree::new("example");
        example_tree(t.path());
        let regenerated = manifest_json(&generated(t.path()).manifest);
        // Regeneration is a deliberate act, so it needs a deliberate switch:
        //   OBC_UPDATE_CATALOG_EXAMPLE=1 cargo test -p obc-pack catalog_example_is_current
        if std::env::var_os("OBC_UPDATE_CATALOG_EXAMPLE").is_some() {
            fs::write(Path::new(env!("CARGO_MANIFEST_DIR")).join("schema/catalog.example.json"), &regenerated)
                .expect("update the checked-in example");
        }
        assert_eq!(
            CATALOG_EXAMPLE_JSON, regenerated,
            "schema/catalog.example.json is stale — regenerate with `OBC_UPDATE_CATALOG_EXAMPLE=1 cargo test -p \
             obc-pack catalog_example_is_current`. (The example is generated from the synthetic tree in catalog.rs's \
             `example_tree`, so its sha256s are stable across fixture repacks — only an OBCM version bump or a \
             manifest-shape change should move it.)"
        );

        let parsed: CatalogManifest = serde_json::from_str(CATALOG_EXAMPLE_JSON).expect("example parses");
        assert!(
            parsed.artifacts.iter().all(|a| a.obcm_version == OBCM_VERSION),
            "every artifact in the example must report the OBCM version this packer writes (v{OBCM_VERSION})"
        );
        assert_eq!(parsed.schema_version, CATALOG_SCHEMA_VERSION);
    }

    // --- loud failures ----------------------------------------------------------------------

    /// A partial re-bake after a preset restyle. The lagging artifact must report the
    /// version it was *baked* with — not the tree's current one — and say so out loud,
    /// because that field is the only signal a consumer has that the styling is old.
    #[test]
    fn a_lagging_preset_version_is_recorded_not_papered_over() {
        let t = TempTree::new("preset-lag");
        example_tree(t.path());
        // The restyle: `minimal` moves 2 → 3, and only Switzerland gets re-baked.
        write_preset(t.path(), "minimal", "Minimal", MINIMAL_BLURB, 3, None);
        write_sidecar(
            t.path(),
            "europe/switzerland",
            "minimal",
            "Switzerland",
            3,
            "2026-07-26T04:02:11Z",
            "2026-07-25",
        );

        let g = generated(t.path());
        let by = |region: &str| {
            g.manifest
                .artifacts
                .iter()
                .find(|a| a.region_id == region && a.preset_id == "minimal")
                .expect("minimal artifact")
                .preset_version
        };
        assert_eq!(by("europe/switzerland"), 3, "the re-baked region carries the new styling");
        assert_eq!(by("europe/monaco"), 2, "the lagging region must NOT be relabelled to 3");
        assert_eq!(
            g.manifest.presets.iter().find(|p| p.id == "minimal").unwrap().version,
            3,
            "presets[].version is the current definition — what a fresh bake would produce"
        );
        assert!(
            g.warnings.iter().any(|w| w.contains("europe/monaco") && w.contains("older styling")),
            "a lag must be reported, not silent: {:?}",
            g.warnings
        );
    }

    /// The other direction is not a lag, it is an inconsistent tree: a preset config
    /// older than an artifact built from it cannot be described honestly at all.
    #[test]
    fn an_artifact_newer_than_its_preset_config_fails() {
        let t = TempTree::new("preset-ahead");
        example_tree(t.path());
        write_sidecar(t.path(), "europe/monaco", "minimal", "Monaco", 9, "2026-07-20T02:44:41Z", "2026-07-19");
        let err = generate(t.path(), &opts()).expect_err("an artifact ahead of its preset config must fail");
        assert!(err.contains("older than an artifact built from it"), "{err}");
    }

    #[test]
    fn a_missing_sidecar_fails() {
        let t = TempTree::new("no-sidecar");
        example_tree(t.path());
        fs::remove_file(t.path().join("regions/europe/monaco/minimal.obcm.json")).unwrap();
        let err = generate(t.path(), &opts()).expect_err("an artifact with no sidecar must fail");
        assert!(err.contains("sidecar"), "{err}");
    }

    #[test]
    fn a_sidecar_with_no_artifact_fails() {
        let t = TempTree::new("orphan-sidecar");
        example_tree(t.path());
        write_sidecar(t.path(), "europe/monaco", "high-detail", "Monaco", 3, "2026-07-20T02:44:41Z", "2026-07-19");
        let err = generate(t.path(), &opts()).expect_err("an orphan sidecar must fail");
        assert!(err.contains("no artifact"), "{err}");
    }

    #[test]
    fn an_undescribed_preset_fails() {
        let t = TempTree::new("unknown-preset");
        example_tree(t.path());
        write_artifact(t.path(), "europe/monaco", "high-detail", OBCM_VERSION, bbox(1, 1, 2, 2), 0);
        write_sidecar(t.path(), "europe/monaco", "high-detail", "Monaco", 3, "2026-07-20T02:44:41Z", "2026-07-19");
        let err = generate(t.path(), &opts()).expect_err("an artifact for an undescribed preset must fail");
        assert!(err.contains("high-detail"), "{err}");
    }

    #[test]
    fn a_preset_no_artifact_uses_fails() {
        let t = TempTree::new("unused-preset");
        example_tree(t.path());
        write_preset(t.path(), "high-detail", "High detail", "Everything the panel can show.", 3, None);
        let err = generate(t.path(), &opts()).expect_err("an unbaked preset must fail");
        assert!(err.contains("must not advertise a preset it cannot serve"), "{err}");
    }

    #[test]
    fn disagreeing_region_names_fail() {
        let t = TempTree::new("region-name");
        example_tree(t.path());
        write_sidecar(t.path(), "europe/monaco", "minimal", "Monaco-Ville", 2, "2026-07-20T02:44:41Z", "2026-07-19");
        let err = generate(t.path(), &opts()).expect_err("two names for one region must fail");
        assert!(err.contains("conflicting region_name"), "{err}");
    }

    #[test]
    fn a_non_obcm_artifact_fails() {
        let t = TempTree::new("bad-magic");
        example_tree(t.path());
        fs::write(t.path().join("regions/europe/monaco/minimal.obcm"), b"not a map at all, but long enough to read 40")
            .unwrap();
        let err = generate(t.path(), &opts()).expect_err("bad magic must fail");
        assert!(err.contains("bad magic"), "{err}");
    }

    #[test]
    fn a_truncated_artifact_fails() {
        let t = TempTree::new("short");
        example_tree(t.path());
        fs::write(t.path().join("regions/europe/monaco/minimal.obcm"), b"OBCM").unwrap();
        let err = generate(t.path(), &opts()).expect_err("a short artifact must fail");
        assert!(err.contains("too short"), "{err}");
    }

    #[test]
    fn stray_files_and_bad_ids_fail() {
        let t = TempTree::new("stray");
        example_tree(t.path());
        write(&t.path().join(REGIONS_DIR).join("europe/monaco/README.txt"), "notes");
        let err = generate(t.path(), &opts()).expect_err("an unexpected file must fail");
        assert!(err.contains("unexpected entry"), "{err}");

        // `Europe` would fold onto `europe` on a case-insensitive filesystem, so the
        // tree-level check uses a character that cannot fold; casing itself is covered
        // by `ids_are_lowercase_kebab`.
        let u = TempTree::new("bad-segment");
        example_tree(u.path());
        write_artifact(u.path(), "east_europe", "default", OBCM_VERSION, bbox(1, 1, 2, 2), 0);
        let err = generate(u.path(), &opts()).expect_err("a non-kebab region segment must fail");
        assert!(err.contains("kebab-case"), "{err}");
    }

    /// Dotfiles are the one thing skipped silently — macOS sprinkles `.DS_Store`
    /// through any directory a Finder window has visited.
    #[test]
    fn dotfiles_are_ignored() {
        let t = TempTree::new("dotfiles");
        example_tree(t.path());
        let clean = manifest_json(&generated(t.path()).manifest);
        write(&t.path().join(REGIONS_DIR).join("europe/monaco/.DS_Store"), "junk");
        write(&t.path().join(PRESETS_DIR).join(".gitkeep"), "");
        assert_eq!(manifest_json(&generated(t.path()).manifest), clean);
    }

    #[test]
    fn a_sidecar_typo_fails_rather_than_defaulting() {
        let t = TempTree::new("typo");
        example_tree(t.path());
        write(
            &t.path().join("regions/europe/monaco/minimal.obcm.json"),
            r#"{"region_name": "Monaco", "preset_version": 2, "built_at": "2026-07-20T02:44:41Z",
                 "sourceSnapshot": "2026-07-19"}"#,
        );
        let err = generate(t.path(), &opts()).expect_err("an unknown sidecar key must fail");
        assert!(err.contains("sourceSnapshot") || err.contains("unknown field"), "{err}");
    }

    #[test]
    fn bad_timestamps_fail() {
        let t = TempTree::new("timestamps");
        example_tree(t.path());
        write_sidecar(t.path(), "europe/monaco", "minimal", "Monaco", 2, "2026-07-20T02:44:41+02:00", "2026-07-19");
        assert!(generate(t.path(), &opts()).unwrap_err().contains("built_at"), "offsets are not accepted");

        write_sidecar(t.path(), "europe/monaco", "minimal", "Monaco", 2, "2026-07-20T02:44:41Z", "2026-02-30");
        assert!(generate(t.path(), &opts()).unwrap_err().contains("source_snapshot"), "2026-02-30 is not a day");
    }

    #[test]
    fn an_empty_tree_fails() {
        let t = TempTree::new("empty");
        write_preset(t.path(), "default", "Bikepacking", DEFAULT_BLURB, 3, None);
        fs::create_dir_all(t.path().join(REGIONS_DIR)).unwrap();
        assert!(generate(t.path(), &opts()).unwrap_err().contains("no `.obcm` artifacts"));
    }

    // --- URLs and ids -------------------------------------------------------------------------

    #[test]
    fn base_urls_are_normalized_and_checked() {
        assert_eq!(normalize_base_url("https://x.example/c/").unwrap(), "https://x.example/c");
        assert_eq!(normalize_base_url("/catalog/v1").unwrap(), "/catalog/v1");
        assert!(normalize_base_url("maps.example.org").is_err(), "a bare host is not resolvable by a browser");
        assert!(normalize_base_url("").is_err());
        assert!(normalize_base_url("https://x.example/a b").is_err());
    }

    #[test]
    fn ids_are_lowercase_kebab() {
        for ok in ["default", "high-detail", "us-california", "a1"] {
            assert!(validate_id(ok).is_ok(), "{ok}");
        }
        for bad in ["", "Default", "high_detail", "high--detail", "-lead", "trail-", "eu/de"] {
            assert!(validate_id(bad).is_err(), "{bad}");
        }
    }

    // --- timestamps ---------------------------------------------------------------------------

    #[test]
    fn timestamps_round_trip() {
        for s in ["1970-01-01T00:00:00Z", "2026-07-26T09:00:00Z", "2024-02-29T23:59:59Z", "2100-03-01T12:00:00Z"] {
            assert_eq!(format_timestamp(validate_timestamp(s).unwrap()), s, "{s}");
        }
        assert_eq!(validate_timestamp("1970-01-02T00:00:00Z").unwrap(), 86_400);
        assert_eq!(format_timestamp(0), "1970-01-01T00:00:00Z");
    }

    #[test]
    fn timestamps_reject_everything_else() {
        for bad in [
            "2026-07-26T09:00:00",       // no zone
            "2026-07-26T09:00:00z",      // lowercase
            "2026-07-26T09:00:00.5Z",    // fractional
            "2026-07-26T09:00:00+00:00", // offset
            "2026-13-01T00:00:00Z",      // month 13
            "2026-02-30T00:00:00Z",      // not a day
            "2026-07-26T24:00:00Z",      // hour 24
            "2026-07-26T23:60:00Z",      // minute 60
            "2026-07-26 09:00:00Z",      // space separator
            "2023-02-29T00:00:00Z",      // 2023 is not a leap year
        ] {
            assert!(validate_timestamp(bad).is_err(), "{bad} must be rejected");
        }
        assert!(validate_date("2024-02-29").is_ok());
        assert!(validate_date("2023-02-29").is_err());
        assert!(validate_date("2026-7-26").is_err());
    }

    #[test]
    fn now_is_a_valid_timestamp() {
        let now = now_timestamp();
        assert!(validate_timestamp(&now).is_ok(), "{now}");
    }

    // --- schema --------------------------------------------------------------------------------

    #[test]
    fn checked_in_catalog_schema_is_current_generated_schema() {
        let checked_in: Value = serde_json::from_str(CATALOG_SCHEMA_JSON).expect("checked-in schema is valid JSON");
        assert_eq!(
            checked_in,
            catalog_schema(),
            "schema/catalog.schema.json is stale; regenerate with `cargo run -p obc-pack --bin obc-pack -- schema \
             --catalog > obc-pack/schema/catalog.schema.json`"
        );
    }

    #[test]
    fn schema_pins_the_envelope_version_and_the_field_patterns() {
        let s = catalog_schema();
        assert_eq!(s["properties"]["schema_version"]["const"].as_u64(), Some(CATALOG_SCHEMA_VERSION as u64));
        assert_eq!(s["$defs"]["ArtifactEntry"]["properties"]["sha256"]["pattern"].as_str(), Some("^[0-9a-f]{64}$"));
        assert_eq!(s["$defs"]["ArtifactEntry"]["properties"]["obcm_version"]["maximum"].as_u64(), Some(255));
        assert_eq!(s["$defs"]["CoverageBBox"]["properties"]["min_lon"]["minimum"].as_i64(), Some(-180_000_000));
        // `preview` is the one optional field: absent until B2's previews exist.
        let required = s["$defs"]["PresetEntry"]["required"].as_array().expect("preset required");
        assert!(!required.iter().any(|v| v == "preview"), "preview must stay optional");
    }

    /// The manifest a real tree produces must actually validate against the schema
    /// consumers will validate with — not merely be structurally plausible.
    #[test]
    fn generated_manifests_validate_against_the_checked_in_schema() {
        let schema: Value = serde_json::from_str(CATALOG_SCHEMA_JSON).expect("schema JSON");
        let compiled = boon::Compiler::new();
        let mut schemas = boon::Schemas::new();
        let mut compiler = compiled;
        compiler.add_resource("catalog.schema.json", schema).expect("add schema");
        let sid = compiler.compile("catalog.schema.json", &mut schemas).expect("compile schema");

        let t = TempTree::new("validate");
        example_tree(t.path());
        let instance: Value = serde_json::from_str(&manifest_json(&generated(t.path()).manifest)).unwrap();
        if let Err(e) = schemas.validate(&instance, sid) {
            panic!("generated manifest does not validate:\n{e:#}");
        }

        // The checked-in example is the artifact C1 will build against; validate it too.
        let example: Value = serde_json::from_str(CATALOG_EXAMPLE_JSON).unwrap();
        if let Err(e) = schemas.validate(&example, sid) {
            panic!("catalog.example.json does not validate:\n{e:#}");
        }

        // And the schema has teeth: a bad sha256 must be caught, not shrugged off.
        let mut broken = instance.clone();
        broken["artifacts"][0]["sha256"] = Value::from("NOTAHASH");
        assert!(schemas.validate(&broken, sid).is_err(), "the sha256 pattern must reject a non-hex digest");
        let mut future = instance;
        future["schema_version"] = Value::from(2);
        assert!(schemas.validate(&future, sid).is_err(), "a future envelope version must not validate as v1");
    }

    /// A truncated manifest cannot be half-consumed: JSON is self-delimiting, so every
    /// prefix of a valid document fails to parse. This is the format half of the
    /// "never partially consumed" rule; `write_atomic` is the writer half.
    #[test]
    fn every_truncation_of_a_manifest_fails_to_parse() {
        let t = TempTree::new("truncate");
        example_tree(t.path());
        let body = manifest_json(&generated(t.path()).manifest);
        assert!(serde_json::from_str::<CatalogManifest>(&body).is_ok());
        for cut in (1..body.len()).step_by(7) {
            assert!(
                serde_json::from_str::<CatalogManifest>(&body[..cut]).is_err(),
                "a manifest truncated at byte {cut} must not parse"
            );
        }
    }

    // --- real artifacts -------------------------------------------------------------------------

    /// The synthetic trees above write headers by hand, so this test checks the reader
    /// side against a real packed map: the committed simulator fixtures.
    #[test]
    fn reads_the_header_of_a_real_packed_map() {
        let monaco = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../apps/obc-sim/assets/monaco.obcm");
        let header = read_obcm_header(&monaco).expect("monaco.obcm header");
        assert_eq!(header.version, OBCM_VERSION, "the committed fixture is packed at the current OBCM version");
        // Monaco: repack.sh cuts it at 7.39,43.71 → 7.47,43.77; the packed coverage box
        // is a little wider (complete ways + coastline), which is exactly why the
        // manifest reports the header box and never feeds it back as an extract box.
        assert!(header.bbox.min_lat > 43_000_000 && header.bbox.max_lat < 44_000_000, "{:?}", header.bbox);
        assert!(header.bbox.min_lon > 7_000_000 && header.bbox.max_lon < 8_000_000, "{:?}", header.bbox);

        let (bytes, sha) = hash_file(&monaco).expect("hash");
        assert_eq!(bytes, fs::metadata(&monaco).unwrap().len());
        assert_eq!(sha.len(), 64);
    }

    /// The shipped presets are real inputs to the bakery: their `_meta` must satisfy
    /// the catalog's requirements, or B1's first bake fails on data we control.
    #[test]
    fn the_shipped_presets_describe_themselves() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packer/presets");
        let presets = read_presets(&dir).expect("packer/presets is a valid preset directory");
        assert!(presets.contains_key("default") && presets.contains_key("minimal"));
        for (id, p) in &presets {
            assert_eq!(&p.id, id);
            assert!(!p.description.is_empty(), "{id} needs a one-line description");
            assert!(p.version >= 1, "{id} needs a _meta.version");
        }
    }
}
