import { marked } from 'marked';
import sanitize from 'sanitize-html';
import type { Candidate } from '../types.ts';
import { readiness } from './domain.ts';
const escape = (s: unknown) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const markdown = (source: string) => sanitize(marked.parse(source, { async: false }), { allowedTags: sanitize.defaults.allowedTags, allowedAttributes: { a: ['href', 'title'] }, allowedSchemes: ['https', 'http'] });
export function report(candidate: Candidate): string {
  const state = readiness(candidate);
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>OBC ${escape(candidate.version)} verification</title><style>body{font:16px/1.6 system-ui;max-width:900px;margin:40px auto;padding:24px;color:#172b2b}article{border-top:1px solid #ccd;padding:24px 0}pre{white-space:pre-wrap}small{color:#567}code{overflow-wrap:anywhere}</style><h1>OpenBikeComputer ${escape(candidate.version)}</h1><p>Candidate ${escape(candidate.id)} · ${escape(candidate.createdAt)}</p><p>Source <code>${escape(candidate.sourceSha)}</code> · Requirements revision ${candidate.revision.id}</p><h2>${state.ready ? 'Verified' : 'Incomplete'}: ${state.verified}/${state.total} requirements</h2>${state.missing.map((m) => `<p>${escape(m)}</p>`).join('')}${candidate.revision.requirements.map((r) => `<article><h2>${escape(r.id)} — ${escape(r.title)}${r.active ? '' : ' (inactive)'}</h2>${markdown(r.statement)}${r.tests.map((t) => `<h3>${escape(t.title)} · ${t.kind}</h3>${t.kind === 'manual' ? markdown(t.steps || '') + '<h4>Expected</h4>' + markdown(t.expected || '') : `<p><code>${escape(t.caseId)}</code>: ${escape(candidate.results.find((result) => result.caseId === t.caseId)?.status || 'missing')}</p>`}<h4>Inputs</h4>${t.inputs.map((a) => `<p>${escape(a.name)} — SHA-256 <code>${a.sha256}</code></p>`).join('')}${candidate.manualRuns.filter((run) => run.requirementId === r.id && run.testId === t.id).map((run) => `<p><strong>${run.result}</strong> · ${escape(run.author)} · ${escape(run.createdAt)} · ${escape(run.device)}</p>${markdown(run.notes)}${run.evidence.map((a) => `<p>Evidence: ${escape(a.name)} — <code>${a.sha256}</code></p>`).join('')}`).join('')}`).join('')}</article>`).join('')}<h2>Firmware assets</h2>${candidate.assets.map((a) => `<p>${escape(a.name)} — ${a.size} bytes — <code>${a.sha256}</code></p>`).join('')}<p>Automated run: ${candidate.runId ?? 'not received'} / attempt ${candidate.runAttempt ?? '—'}</p></html>`;
}
