/* obc-boot memory map — the bootloader's 32 KB slot at the bottom of the nRF54L15's RRAM.
 *
 * The full device layout (epic #615; the app side of it is emitted by
 * ../obc-fw-nrf54l/build.rs — keep the two in agreement):
 *
 *   0x0000_0000  obc-boot          32 KB   (this crate — FLASH below)
 *   0x0000_8000  app slot        1996 KB   (the board crate, linked at 0x8000)
 *   0x001F_B000  BOOT_STATE page    4 KB   (the obc-dfu handoff page — read here)
 *   0x001F_C000  SETTINGS page      4 KB   (the app's persistent settings, #193 — never ours)
 *
 * RAM is 500 KB — the full 512 KB minus the chip's top-of-RAM VPR/ProtectedRAM reservation, which
 * the bootloader never touches. The bootloader runs alone (the app re-initialises RAM from its own
 * reset path after the jump, so nothing here needs to survive) and it starts no coprocessor: the
 * app owns the FLPR and copies both soft-peripheral images itself, after boot has handed off.
 *
 * ⚠️ This extent is NO LONGER the app's. Since #1158 the app links only 480 KB: the 20 KB below
 * the display FLPR's carve holds the sEMMC soft-peripheral image (the SD host controller), and the
 * app's memory.x — generated by ../obc-fw-nrf54l/build.rs — ends its RAM at 0x2007_8000 where this
 * one runs to 0x2007_D000. The bootloader's stack therefore starts inside what will later be the
 * sEMMC carve. That is safe, and only because the handoff is strictly sequential: boot reads the
 * card and the boot-state page, jumps, and is gone; nothing it left behind is read afterwards, and
 * nothing in either carve exists yet (the app copies the images in after it starts). Do not turn
 * that into an invariant either side relies on — if the bootloader ever gains a
 * survives-the-jump handoff buffer, or the app ever expects carve contents to predate its own
 * boot, this extent must shrink to match the app's.
 *
 * Unlike the board crate (whose memory.x is generated into $OUT_DIR by build.rs), this file is
 * static and committed: build.rs copies it to $OUT_DIR for cortex-m-rt's `INCLUDE memory.x`.
 */
MEMORY
{
    FLASH      : ORIGIN = 0x00000000, LENGTH = 32K
    BOOT_STATE : ORIGIN = 0x001FB000, LENGTH = 4K   /* boot-state handoff page (OBCU_Spec.md §2) */
    RAM        : ORIGIN = 0x20000000, LENGTH = 500K
}

/* Base of the boot-state page — same symbol convention as the app's `__settings_base`
 * (the magic address lives only in the linker script; main.rs reads the symbol). */
PROVIDE(__boot_state_base = ORIGIN(BOOT_STATE));

/* Base of the app slot — the app's link origin (0x8000), which is exactly one past the
 * bootloader's own FLASH region. Derived so growing the bootloader (bump LENGTH(FLASH))
 * shifts the app base automatically; main.rs reads this symbol instead of a literal, the
 * same "magic address lives only in the linker script" rule as `__boot_state_base`. Mirrors
 * the board crate's `__app_slot_base` symbol (there FLASH *is* the app slot, so it PROVIDEs
 * `ORIGIN(FLASH)`; here FLASH is the bootloader, so the app base is its end). */
PROVIDE(__app_slot_base = ORIGIN(FLASH) + LENGTH(FLASH));
