//! Two jobs: let `tauri-build` generate the app context (which embeds the built
//! frontend named by `tauri.conf.json`), and bake the shipped **packer configs** —
//! `builder/presets/*.json`, which since #1036 is the one `schema.json` — into the
//! binary.
//!
//! They have to be *embedded* rather than read at runtime: a shipped app has no repo
//! checkout next to it, and the shipped styling is the app's own content, not user
//! data. Generating the table here rather than listing the files by hand means adding
//! one is a file rather than two edits — and the `rerun-if-changed` below makes an
//! edit rebuild the app.
//!
//! Only the top level of that directory is read, which is what keeps `skins/` out:
//! a skin is presentation stamped onto already-baked bytes at assembly time
//! (`OBCC_Spec.md` §11.4), not something this app can hand the packer.

use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();
    embed_presets();
}

fn presets_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../builder/presets")
}

fn embed_presets() {
    let dir = presets_dir();
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    // Sorted so the generated table — and therefore the order the app offers these in
    // — does not depend on the filesystem's directory order. (There is no longer a
    // default-first sort downstream to re-impose one: since #1036 the top level holds
    // exactly one document, the schema.)
    entries.sort();
    assert!(!entries.is_empty(), "no presets found in {}", dir.display());

    let mut out = String::from("/// (file stem, file body) for every shipped preset. Generated by build.rs.\npub static PRESETS: &[(&str, &str)] = &[\n");
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().expect("preset file stem").to_string_lossy();
        out.push_str(&format!("    ({stem:?}, include_str!({:?})),\n", include_path(path)));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("presets.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}

/// An absolute path `include_str!` will accept, on every platform (#907).
///
/// `canonicalize` is what resolves the `../../` in [`presets_dir`], but on Windows
/// it hands back an **extended-length path** — `\\?\C:\…` — and `include_str!`
/// resolves its argument through the compiler's own path handling rather than the
/// raw Win32 API, so the verbatim prefix is not reliably understood. Stripping it
/// leaves a perfectly ordinary `C:\…`, which is what we wanted from canonicalize
/// in the first place. A no-op everywhere else.
fn include_path(path: &Path) -> PathBuf {
    let resolved = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
    let text = resolved.to_string_lossy();
    match text.strip_prefix(r"\\?\") {
        Some(plain) => PathBuf::from(plain),
        None => resolved,
    }
}
