//! Two jobs: let `tauri-build` generate the app context (which embeds the built
//! frontend named by `tauri.conf.json`), and bake `packer/presets/*.json` into the
//! binary.
//!
//! The presets have to be *embedded* rather than read at runtime: a shipped app
//! has no repo checkout next to it, and the style presets are the app's own
//! content, not user data. Generating the table here rather than listing the files
//! by hand means adding a preset is one file, not two edits — and the
//! `rerun-if-changed` below makes a preset edit rebuild the app.

use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();
    embed_presets();
}

fn presets_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packer/presets")
}

fn embed_presets() {
    let dir = presets_dir();
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    // Sorted so the generated table — and therefore the app's preset order before
    // the default-first sort — does not depend on the filesystem's directory order.
    entries.sort();
    assert!(!entries.is_empty(), "no presets found in {}", dir.display());

    let mut out = String::from("/// (file stem, file body) for every shipped preset. Generated by build.rs.\npub static PRESETS: &[(&str, &str)] = &[\n");
    for path in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let stem = path.file_stem().expect("preset file stem").to_string_lossy();
        out.push_str(&format!("    ({stem:?}, include_str!({:?})),\n", path.canonicalize().unwrap_or(path.clone())));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("presets.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));
}
