#!/usr/bin/env bash
# OBC weather bakery — idempotent installer for one Debian-class VPS.
#
#   sudo ops/weather/install.sh --from-source            # build on the box from this checkout
#   sudo ops/weather/install.sh --binary ./obc-wx-bake   # or install a binary you built elsewhere
#   sudo ops/weather/install.sh                          # re-sync units/config, keep the binary
#
# Run it as often as you like: it creates what is missing, replaces what changed, disables timers
# that are no longer in adapters.conf, and never touches /etc/obc-wx/r2.env once that file exists.
# Everything it writes is listed in ops/weather/RUNBOOK.md.
#
# --generate-only DIR writes the unit files it *would* install into DIR and exits. No root, no
# systemd, no package manager — that is the mode this script is tested in on a workstation.
set -euo pipefail

BIN_NAME=obc-wx-bake
BIN_PATH=/usr/local/bin/$BIN_NAME
SERVICE_USER=obc-wx
CONFIG_DIR=/etc/obc-wx
ENV_FILE=$CONFIG_DIR/r2.env
STATE_DIR=/var/lib/obc-wx
UNIT_DIR=/etc/systemd/system
SRC_DIR=/opt/obc-wx/src
REPO_URL=https://github.com/timohueser/OpenBikeComputer.git

unset CDPATH
HERE=$(cd -- "$(dirname -- "$0")" && pwd)
ADAPTERS_CONF=$HERE/adapters.conf
SERVICE_TEMPLATE=$HERE/systemd/obc-wx-bake@.service

binary_source=
build_from_source=false
build_ref=
generate_only=
verify=true

die() { printf 'install.sh: %s\n' "$*" >&2; exit 1; }
say() { printf '  %s\n' "$*"; }
step() { printf '\n== %s\n' "$*"; }

usage() {
    sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
    cat <<'EOF'

Options:
  --binary PATH        install this prebuilt obc-wx-bake binary
  --from-source [REF]  clone/update the repo on this box and cargo build --release (default: develop)
  --generate-only DIR  write the generated unit files to DIR and exit (no root needed)
  --no-verify          skip the post-install dry-run bake
  -h, --help           this text
EOF
}

while [ $# -gt 0 ]; do
    case $1 in
        --binary) binary_source=${2:?--binary needs a path}; shift 2 ;;
        --from-source)
            build_from_source=true
            case ${2:-} in ''|--*) build_ref=develop; shift ;; *) build_ref=$2; shift 2 ;; esac ;;
        --generate-only) generate_only=${2:?--generate-only needs a directory}; shift 2 ;;
        --no-verify) verify=false; shift ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; die "unknown argument $1" ;;
    esac
done

[ -f "$ADAPTERS_CONF" ] || die "$ADAPTERS_CONF is missing"
[ -f "$SERVICE_TEMPLATE" ] || die "$SERVICE_TEMPLATE is missing"
if [ -n "$binary_source" ] && [ "$build_from_source" = true ]; then
    die "--binary and --from-source are mutually exclusive"
fi

# ── The adapter table ────────────────────────────────────────────────────────────────────────
# Emit "name<TAB>oncalendar<TAB>delay<TAB>note" for every non-comment row, failing loudly on a
# row this script cannot parse rather than silently installing a timer that never fires.
read_adapters() {
    local line name cal delay runs note
    while IFS= read -r line; do
        line=${line%%$'\r'}
        case $line in ''|'#'*) continue ;; esac
        read -r name cal delay runs note <<<"$line"
        [ -n "$name" ] && [ -n "$cal" ] && [ -n "$delay" ] && [ -n "$runs" ] \
            || die "adapters.conf: cannot parse '$line' (want: name oncalendar delay runs/day note)"
        case $name in
            *[!a-z0-9-]*) die "adapters.conf: '$name' is not a plain lowercase adapter id" ;;
        esac
        case $delay in
            *[!0-9]*) die "adapters.conf: delay '$delay' for $name is not a number of seconds" ;;
        esac
        case $runs in
            *[!0-9]*) die "adapters.conf: runs/day '$runs' for $name is not a number" ;;
        esac
        printf '%s\t%s\t%s\t%s\n' "$name" "$cal" "$delay" "$note"
    done <"$ADAPTERS_CONF"
}

timer_unit() {  # name oncalendar delay note
    cat <<EOF
# GENERATED by ops/weather/install.sh from ops/weather/adapters.conf — do not edit here.
# Change the cadence in adapters.conf and re-run the installer.
#
# $4
[Unit]
Description=OBC weather bakery — $1 cadence ($2)
Documentation=https://github.com/timohueser/OpenBikeComputer/blob/develop/ops/weather/RUNBOOK.md

[Timer]
OnCalendar=$2
RandomizedDelaySec=$3
AccuracySec=5s
# Never catch up. A tick missed while the box was down would bake a run that is already worthless
# — and a reboot must not fire every adapter at once.
Persistent=false
Unit=obc-wx-bake@$1.service

[Install]
WantedBy=timers.target
EOF
}

# ── --generate-only: the workstation-testable path ───────────────────────────────────────────
if [ -n "$generate_only" ]; then
    mkdir -p "$generate_only"
    cp "$SERVICE_TEMPLATE" "$generate_only/obc-wx-bake@.service"
    while IFS=$'\t' read -r name cal delay note; do
        timer_unit "$name" "$cal" "$delay" "$note" >"$generate_only/obc-wx-bake@$name.timer"
        chmod 0644 "$generate_only/obc-wx-bake@$name.timer"
        say "generated obc-wx-bake@$name.timer ($cal)"
    done < <(read_adapters)
    printf '\nGenerated units in %s (nothing was installed).\n' "$generate_only"
    exit 0
fi

[ "$(id -u)" = 0 ] || die "run as root (sudo), or use --generate-only DIR"
command -v systemctl >/dev/null || die "no systemctl — this installer targets a systemd (Debian-class) host"

# ── Packages ─────────────────────────────────────────────────────────────────────────────────
step "Packages"
need_pkgs=()
command -v rclone >/dev/null || need_pkgs+=(rclone)
command -v flock  >/dev/null || need_pkgs+=(util-linux)
command -v curl   >/dev/null || need_pkgs+=(curl)
[ -f /etc/apt/apt.conf.d/20auto-upgrades ] || need_pkgs+=(unattended-upgrades)
if [ "$build_from_source" = true ]; then
    command -v git >/dev/null || need_pkgs+=(git)
    command -v cc  >/dev/null || need_pkgs+=(build-essential)
    command -v pkg-config >/dev/null || need_pkgs+=(pkg-config)
fi
if [ ${#need_pkgs[@]} -gt 0 ]; then
    say "installing: ${need_pkgs[*]}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq "${need_pkgs[@]}"
else
    say "nothing to install"
fi

# ── User, directories, secrets ───────────────────────────────────────────────────────────────
step "Service account and directories"
if id -u "$SERVICE_USER" >/dev/null 2>&1; then
    say "user $SERVICE_USER exists"
else
    useradd --system --no-create-home --home-dir "$STATE_DIR" --shell /usr/sbin/nologin "$SERVICE_USER"
    say "created system user $SERVICE_USER"
fi
install -d -o root -g "$SERVICE_USER" -m 0750 "$CONFIG_DIR"
install -d -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0750 "$STATE_DIR"

if [ -f "$ENV_FILE" ]; then
    chown root:root "$ENV_FILE"; chmod 0600 "$ENV_FILE"
    say "$ENV_FILE exists — left untouched (0600 root:root)"
else
    # The umask lives in this subshell only: it must not leak into the unit files written below,
    # which systemd expects to be world-readable 0644.
    ( umask 077; cat >"$ENV_FILE" <<'EOF'
# R2 credentials for obc-wx-bake. 0600 root:root — systemd reads this as root before dropping to
# the obc-wx user, so the service account itself never has the secret on disk it can read.
# NEVER commit this file. Rotation procedure: ops/weather/RUNBOOK.md § Rotate the R2 token.
OBC_WX_R2_ACCOUNT_ID=
OBC_WX_R2_BUCKET=obc-wx
OBC_WX_R2_ACCESS_KEY_ID=
OBC_WX_R2_SECRET_ACCESS_KEY=

# Only for a bucket created with a *jurisdiction* (European Union / FedRAMP) rather than a plain
# location hint: those live on their own S3 endpoint, and the endpoint the account id derives
# (https://<account>.r2.cloudflarestorage.com) cannot see them — every object comes back 403
# AccessDenied with a perfectly valid token. Uncomment and paste the bucket's own S3 API host:
#OBC_WX_R2_ENDPOINT=https://<account>.eu.r2.cloudflarestorage.com
EOF
    )
    chown root:root "$ENV_FILE"; chmod 0600 "$ENV_FILE"
    say "wrote the $ENV_FILE skeleton — fill in the R2 token before starting the timers"
fi

# Are the credentials actually filled in? Timers are installed either way, but starting them
# against a placeholder file would only manufacture a failure every five minutes.
credentials_ready=true
for key in OBC_WX_R2_ACCOUNT_ID OBC_WX_R2_ACCESS_KEY_ID OBC_WX_R2_SECRET_ACCESS_KEY; do
    grep -qE "^$key=.+" "$ENV_FILE" || credentials_ready=false
done

# ── The binary ───────────────────────────────────────────────────────────────────────────────
step "Binary"
if [ "$build_from_source" = true ]; then
    if [ -d "$SRC_DIR/.git" ]; then
        git -C "$SRC_DIR" fetch --quiet origin
    else
        install -d -m 0755 "$(dirname "$SRC_DIR")"
        git clone --quiet "$REPO_URL" "$SRC_DIR"
    fi
    git -C "$SRC_DIR" checkout --quiet --detach "origin/$build_ref" 2>/dev/null \
        || git -C "$SRC_DIR" checkout --quiet --detach "$build_ref"
    say "building $(git -C "$SRC_DIR" rev-parse --short HEAD) — this takes a few minutes on a small VPS"
    if ! command -v cargo >/dev/null; then
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --no-modify-path
    fi
    # shellcheck disable=SC1091
    [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
    ( cd "$SRC_DIR" && cargo build --release --locked -p obc-wx-bake )
    binary_source=$SRC_DIR/target/release/$BIN_NAME
fi

if [ -n "$binary_source" ]; then
    [ -x "$binary_source" ] || die "$binary_source is not an executable file"
    install -o root -g root -m 0755 "$binary_source" "$BIN_PATH"
    say "installed $BIN_PATH from $binary_source"
elif [ -x "$BIN_PATH" ]; then
    say "keeping the installed $BIN_PATH (pass --binary or --from-source to replace it)"
else
    die "no binary: pass --binary PATH or --from-source"
fi

# Does this binary know a subcommand? A known one with no destination fails with the destination
# complaint; an unknown one fails with the usage text. That is the whole probe, and it is what lets
# a row land in adapters.conf before the binary that answers to it is deployed.
supports_adapter() {
    local out
    out=$("$BIN_PATH" "$1" 2>&1 || true)
    case $out in *"pick a destination"*) return 0 ;; *) return 1 ;; esac
}

# ── Units ────────────────────────────────────────────────────────────────────────────────────
step "systemd units"
install -o root -g root -m 0644 "$SERVICE_TEMPLATE" "$UNIT_DIR/obc-wx-bake@.service"
enabled=(); skipped=()
while IFS=$'\t' read -r name cal delay note; do
    if supports_adapter "$name"; then
        timer_unit "$name" "$cal" "$delay" "$note" >"$UNIT_DIR/obc-wx-bake@$name.timer"
        chmod 0644 "$UNIT_DIR/obc-wx-bake@$name.timer"
        enabled+=("$name")
    else
        skipped+=("$name")
        rm -f "$UNIT_DIR/obc-wx-bake@$name.timer"
    fi
done < <(read_adapters)
[ ${#enabled[@]} -gt 0 ] || die "the installed binary knows none of the adapters in adapters.conf"

# Timers for adapters that left the table (or the binary) must go, or they keep firing forever.
listed=" ${enabled[*]} "
for unit in "$UNIT_DIR"/obc-wx-bake@*.timer; do
    [ -e "$unit" ] || continue
    name=$(basename "$unit"); name=${name#obc-wx-bake@}; name=${name%.timer}
    case $listed in *" $name "*) continue ;; esac
    say "retiring obc-wx-bake@$name.timer"
    systemctl disable --now "obc-wx-bake@$name.timer" >/dev/null 2>&1 || true
    rm -f "$unit"
done

systemctl daemon-reload
for name in "${enabled[@]}"; do
    # Enable always; start only when the credentials are real. Ticking against a placeholder env
    # file would just manufacture a failed bake every few minutes and bury the real first publish.
    if [ "$credentials_ready" = true ]; then
        systemctl enable --now "obc-wx-bake@$name.timer" >/dev/null
    else
        systemctl enable "obc-wx-bake@$name.timer" >/dev/null
    fi
done
if [ "$credentials_ready" = true ]; then
    say "enabled and started: ${enabled[*]}"
else
    say "enabled (NOT started — $ENV_FILE has no credentials yet): ${enabled[*]}"
fi
[ ${#skipped[@]} -gt 0 ] && say "skipped (this binary has no such subcommand): ${skipped[*]}"

# ── Bounded journal retention ────────────────────────────────────────────────────────────────
step "Journal retention"
install -d -m 0755 /etc/systemd/journald.conf.d
cat >/etc/systemd/journald.conf.d/obc-wx.conf <<'EOF'
# The bakery logs one short report per tick; at the tightest cadence that is a few thousand lines
# a day. Cap the journal so a chatty failure loop can never fill a 40 GB disk.
[Journal]
SystemMaxUse=200M
MaxRetentionSec=1month
EOF
systemctl restart systemd-journald
say "journal capped at 200M / 1 month"

# ── Verification ─────────────────────────────────────────────────────────────────────────────
if [ "$verify" = true ]; then
    step "Verification bake (dry run — fetches and decodes upstream, publishes nothing)"
    first=${enabled[0]}
    if runuser -u "$SERVICE_USER" -- "$BIN_PATH" "$first" --store "$STATE_DIR/dry-run" --dry-run; then
        say "$first fetched and decoded upstream cleanly"
    else
        say "WARNING: the $first dry run failed — see the output above (the timers are installed either way)"
    fi
fi

step "Installed"
systemctl list-timers --all 'obc-wx-bake@*' --no-pager || true
if [ "$credentials_ready" = true ]; then
    cat <<EOF

The timers are running. Next:
  1. Watch the first ticks:
       journalctl -u 'obc-wx-bake@*' -n 50 --no-pager
  2. Confirm the manifest is public:  curl -sI \$OBC_WX_BASE_URL/wx/v1/manifest.json
  3. The rest — bucket, lifecycle rule, token scope, freshness alerting — is in
     ops/weather/RUNBOOK.md.
EOF
else
    cat <<EOF

The timers are enabled but NOT started, because $ENV_FILE has no credentials yet. Next:
  1. Fill in $ENV_FILE (R2 account id + scoped token), then take the first publish by hand:
       systemctl start obc-wx-bake@${enabled[0]}.service
       journalctl -u obc-wx-bake@${enabled[0]}.service -n 50 --no-pager
  2. Start the timers:  systemctl start 'obc-wx-bake@*.timer'
     (or simply re-run this installer — it starts them once the credentials are there)
  3. Confirm the manifest is public:  curl -sI \$OBC_WX_BASE_URL/wx/v1/manifest.json
  4. The rest — bucket, lifecycle rule, token scope, freshness alerting — is in
     ops/weather/RUNBOOK.md.
EOF
fi
