//! The LS021B7DD02 display backend, driven through the FLPR coprocessor.
//!
//! The board's composition edge pairs [`Frame64`], the resident device-64 frame, with this module's
//! [`Ls021Flpr`] presenter, so no panel-specific code reaches the map plane's callers. The contract
//! impls are at the bottom of this file.
//!
//! What lives here is everything that talks to the FLPR: the cross-core [`Control`] block and its
//! dirty-row span list, which is normative with the C blob `src/flpr/flpr_scan.c` and static-asserts
//! to 96 bytes on both sides; [`launch_flpr`], which copies the blob into FLPR RAM, arms the control
//! block, releases the core and waits for its `ALIVE` stamp; and [`Ls021Flpr`] itself.
//!
//! The FLPR scans the framebuffer directly through `fb_addr`. A push publishes the span list and
//! rings one masked `CMD_RUN_FRAME`, and the FLPR packs each dirty row to the wire itself. The app
//! renders the whole frame each redraw, but the push — the dominant cost, about 44 ms full-frame —
//! scales to the changed-row span, because the FLPR fast-forwards the gate over unchanged rows and
//! stops after the last one. `Presenter::present` derives the spans from a per-row hash of the last
//! pushed frame.
//!
//! The push is async: it rings the doorbell and awaits the FLPR's EGU20 frame ack, so the scan costs
//! the M33 nothing. The wait is bounded by [`FRAME_DEADLINE`], and a timeout reads as a transport
//! fault: the caller keeps the last frame, re-arms the diff and retries. The overlay push
//! deliberately blocks ([`run_spans_blocking`](Ls021Flpr::run_spans_blocking)): its ~9 KB composite
//! and save scratch must stay stack transients, because alive across an `await` they become task
//! future state in a static and permanently shrink the residual stack.
//!
//! COM stays on the M33 and is not here. If the FLPR ever faults, COM must keep alternating so the
//! panel never takes a DC bias.
//!
//! The same coprocessor also runs the sEMMC soft peripheral, and [`crate::flpr_mux`] owns which
//! image has the hart. Two seams reach out of this module into it: every push funnels through
//! [`ring_spans`](Ls021Flpr::ring_spans), which calls
//! [`flpr_mux::ensure_display`](crate::flpr_mux::ensure_display) first, and a scan in flight must
//! never be parked ([`scan_in_flight`], [`wait_scan_settled`]), which is the one window in which
//! handing the FLPR to storage would abandon a half-drawn frame.

use core::ptr::{addr_of, addr_of_mut};
use core::sync::atomic::{AtomicU32, Ordering};

use defmt::{debug, error, info};
use embassy_nrf::interrupt;
use embassy_nrf::interrupt::{InterruptExt, Priority};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::signal::Signal;
use embassy_time::{with_deadline, Duration, Instant, Timer};
// The panel width the wire pack is defined over. The C blob's pack is a line-for-line port of
// `ls021_wire::pack_pair` and `pack_row`, so the seam geometry is pinned to it below.
use obc_display::ls021::wire::WIDTH;
// The LS021 pairing's shared substance: `RowDiff`, the self-diffing present store; the
// `RowDamage` and `RowWindow` vocabulary; and `composite_into_resident`, the shared overlay engine.
// The FLPR scans the resident frame directly, so a composited window must transiently live in it.
use obc_display::display_contracts::{Device64Frame, OverlayPresenter, PresentStats, Presenter};
use obc_display::ls021::{composite_into_resident, OverlayScratch, RowDamage, RowDiff, RowWindow};
use obc_display::Band;

use embedded_graphics::prelude::*;
use embedded_graphics::primitives::Rectangle;

/// The FLPR program image, cross-compiled by `build.rs` into `$OUT_DIR/flpr.bin`.
static FLPR_BLOB: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/flpr.bin"));

// The cross-core contract — the shared addresses, magic and status stamps, command codes and the
// span cap — is generated by build.rs, whose `contract` module is the single definition site: it
// also derives the carved memory.x and the FLPR's flpr.ld from the same values, so no side can
// fork. The C blob includes the equivalent generated `flpr_contract.h`.
include!(concat!(env!("OUT_DIR"), "/flpr_contract.rs"));

/// The shared control block at the `SHARED` page base. `fb_addr` is the resident framebuffer the
/// FLPR scans directly, with a stride of [`FB_W`] bytes per row by contract. The layout is normative
/// and identical to the C `flpr_control_t` in `src/flpr/flpr_scan.c`: keep them in sync. All fields
/// are little-endian `u32`, so `#[repr(C)]` gives deterministic offsets and no padding. It is
/// accessed only through raw volatile field reads and writes, never as a reference, because the FLPR
/// mutates it concurrently.
#[repr(C)]
#[allow(dead_code)] // fields are touched only through raw `addr_of` field projections, never as `.field`.
struct Control {
    magic: u32,                    // 0x00 M33: layout/version tag, checked by the FLPR before acting
    m33_seq: u32,                  // 0x04 M33: command sequence counter (the per-frame command doorbell)
    cmd: u32,                      // 0x08 M33: command word (a CMD_* code)
    flpr_seq: u32,                 // 0x0C FLPR: echoes the m33_seq it serviced (the ack the M33 awaits)
    status: u32,                   // 0x10 FLPR: ack/result (dirty rows scanned; boot: FLPR_ALIVE)
    frame_count: u32,              // 0x14 FLPR: frames drained (bumped per CMD_RUN_FRAME)
    fb_addr: u32,                  // 0x18 M33: resident device-64 framebuffer base (stride FB_W bytes/row)
    n_spans: u32,                  // 0x1C M33: #dirty-row spans (1 = a full frame `(0, FB_H)`)
    spans: [u32; MAX_DIRTY_SPANS], // 0x20 M33: packed `(start_row << 16) | count`, ascending + disjoint
}
/// Lock the cross-language contract: the C `flpr_control_t` `_Static_assert`s the same 96 bytes.
/// The two structs alias the same shared-RAM bytes, and `MAX_DIRTY_SPANS` is single-sourced, so this
/// guards field order and type drift.
const _: () = assert!(core::mem::size_of::<Control>() == 96);

const CONTROL: *mut Control = CONTROL_ADDR as *mut Control;

// VPR00 control, secure alias base 0x5004_C000. The M33 only launches the FLPR here.
const VPR00_INITPC: *mut u32 = 0x5004_C808 as *mut u32; // initial PC at core start
const VPR00_CPURUN: *mut u32 = 0x5004_C800 as *mut u32; // CPURUN.EN bit0 = run

// The VPR00 RISC-V Debug Module, the force-stop lever a wedged FLPR needs. `CPURUN.EN = 0` does not
// stop a running VPR core: it only parks one that reaches a WFI, which neither the scan blob's poll
// loop nor a hung core ever executes. The DM's `haltreq` halts the hart at the next instruction
// boundary whatever it is running, and `ndmreset` then resets it, so the relaunch can rebuild the
// blob under a genuinely stopped core. Standard RISC-V DM v0.13 register layout.
const VPR00_DMCONTROL: *mut u32 = 0x5004_C440 as *mut u32;
const VPR00_DMSTATUS: *mut u32 = 0x5004_C444 as *mut u32;
const DM_DMACTIVE: u32 = 1 << 0; // DMCONTROL: debug module enable (its own reset, active low-ish: 0 = DM reset)
const DM_NDMRESET: u32 = 1 << 1; // DMCONTROL: reset line to everything but the DM (the hart)
const DM_HALTREQ: u32 = 1 << 31; // DMCONTROL: halt the selected hart at the next instruction boundary
const DMSTATUS_ALLHALTED: u32 = 1 << 9; // DMSTATUS: the hart acknowledged the halt
/// How long a haltreq gets before the relaunch stops waiting and fires `ndmreset`. The halt is a
/// courtesy — a clean instruction boundary — and the reset is the guarantee.
const HALT_DEADLINE: Duration = Duration::from_millis(10);

// Frame geometry. The wire-word counts come from `obc_display::ls021::wire`, and the static asserts
// pin the frame geometry to the protocol constants it must equal, so the frame the app renders can
// never silently fork from the frame this backend scans.
/// Visible pixel rows the FLPR scans per frame. The blob's gate scan is hard-wired to 320 rows, so
/// the seam's `FRAME_H` must equal it, which is asserted below.
pub const ROWS_PER_FRAME: u32 = 320;
/// Framebuffer width, re-exported for the resident-plane sizing in the app.
pub const FB_W: usize = obc_display::ls021::FRAME_W;
/// Framebuffer height = the seam's frame height = the visible row count.
pub const FB_H: usize = obc_display::ls021::FRAME_H;
// The wire pack consumes exactly one row per framebuffer row, and the blob scans exactly
// `ROWS_PER_FRAME` gate lines, so the seam's frame must match both.
const _: () = assert!(FB_W == WIDTH, "ls021::FRAME_W diverged from the LS021 wire row width");
const _: () =
    assert!(FB_H == ROWS_PER_FRAME as usize, "ls021::FRAME_H diverged from the FLPR blob's 320-row gate scan");

/// The board's native frame: the one resident RGB222 plane, wrapped as the contracts'
/// [`Device64Frame`] at the panel geometry. The map plane owns it next to the [`Ls021Flpr`]
/// presenter: a render borrows it mutably, and a base present shares it for the whole FLPR scan,
/// which is the borrow that statically keeps a render off the bytes the coprocessor is reading.
pub type Frame64 = Device64Frame<'static, FB_W, FB_H>;

/// Composite scratch for a full-width strip containing both edge hints.
/// The RGB565 and saved RGB222 pixels stay on the overlay call's stack.
const MAX_OVERLAY_COLS: usize = FB_W;
const MAX_OVERLAY_ROWS: usize = 12;

// The EGU20 frame-ack doorbell. The blob pokes `EGU20.TASKS_TRIGGER[0]` after every frame, and the
// M33 arms `TRIGGERED[0]`'s IRQ and awaits it instead of busy-polling `flpr_seq`. Raw secure-alias
// MMIO, because embassy-nrf's `pac` re-export is `pub(crate)`.
const EGU20_EVENTS_TRIGGERED0: *mut u32 = 0x500C_9100 as *mut u32;
const EGU20_INTENSET: *mut u32 = 0x500C_9304 as *mut u32;

/// The frame ack the EGU20 ISR signals: what a push awaits instead of spinning. A `Signal` rather
/// than a waker, so an ack that lands before the await starts is not lost.
static FRAME_ACK: Signal<CriticalSectionRawMutex, ()> = Signal::new();

/// The EGU20 ISR, which is the FLPR's per-frame doorbell: clear the latched `TRIGGERED[0]` event,
/// or the IRQ re-fires forever, and signal the awaiting push. It runs at P1, below the P0 GRTC time
/// driver: the ack is a one-store wake, so the priority only has to stay under P0.
#[interrupt]
unsafe fn EGU20() {
    EGU20_EVENTS_TRIGGERED0.write_volatile(0);
    // The FLPR stamps `flpr_seq` before poking this doorbell, so the sequence this ack belongs to is
    // readable here. Publishing it is what lets [`scan_in_flight`] stay honest across the gap
    // between that stamp and this poke.
    ACKED_SEQ.store(addr_of!((*CONTROL).flpr_seq).read_volatile(), Ordering::Release);
    FRAME_ACK.signal(());
}

/// The sequence the EGU20 ISR has actually observed an ack for: the second gate of
/// [`scan_in_flight`].
///
/// `flpr_seq` alone cannot call a frame finished. The FLPR stamps it and only then pokes EGU20, so
/// between those two stores the frame looks done to the M33 while the doorbell is still in flight.
/// Parking the hart in that window destroys the poke, and the push then waits out the whole
/// [`FRAME_DEADLINE`] for an ack that can no longer come.
static ACKED_SEQ: AtomicU32 = AtomicU32::new(0);

/// The sequence of the scan on the wire, or 0 when the panel is idle.
///
/// A sequence rather than a flag, because the EGU20 ISR fires per frame and a late ack of frame N
/// can land after [`Ls021Flpr::ring_spans`] has rung N+1, so a boolean cleared by "an ack arrived"
/// would report the panel idle with a frame half-drawn. It is readable from any task, which is the
/// point: a task other than the one awaiting the ack asks the question.
static SCAN_SEQ: AtomicU32 = AtomicU32::new(0);

/// Is a frame on the wire right now? This is the one window in which the FLPR must not be handed to
/// storage, because parking here abandons a half-scanned frame. Every other instant is fair game:
/// the display side only touches the coprocessor from the map plane, and the storage side's
/// transfers are synchronous.
///
/// It reads the FLPR's `flpr_seq` echo directly instead of consulting the pushing task, so it stays
/// truthful while that task is suspended on [`FRAME_ACK`].
pub fn scan_in_flight() -> bool {
    let s = SCAN_SEQ.load(Ordering::Relaxed);
    if s == 0 {
        return false; // no push outstanding — both run paths clear this, success or timeout
    }
    // SAFETY: a volatile read of one `u32` in the SHARED handshake page, which no Rust object
    // aliases and the FLPR writes concurrently.
    let echoed = unsafe { addr_of!((*CONTROL).flpr_seq).read_volatile() };
    // Two gates, not one. `flpr_seq` goes idle one store early — the FLPR stamps it, then pokes
    // EGU20 — and parking the hart in that gap eats the doorbell (see [`ACKED_SEQ`]). The frame is
    // only over once the ISR has observed this sequence's ack.
    echoed != s || ACKED_SEQ.load(Ordering::Acquire) != s
}

/// Spin until [`scan_in_flight`] clears: the synchronous half of the mux's never-park-mid-scan
/// rule, for the paths that have no `await`.
///
/// It is bounded by [`FRAME_DEADLINE`], the same window the pushing task gives the ack. Past it the
/// coprocessor is wedged rather than busy, and the caller is better served by taking the hart.
/// Returns whether the scan settled.
///
/// It spins rather than yields on purpose: it is reached from synchronous storage code, and the task
/// it waits on cannot make progress by being polled anyway. Async callers should wait through
/// [`crate::flpr_mux::storage_session`] instead, which yields.
pub fn wait_scan_settled() -> bool {
    let deadline = Instant::now() + FRAME_DEADLINE;
    while scan_in_flight() {
        if Instant::now() >= deadline {
            error!(
                "LS021 FLPR: scan never settled within {=u64} ms — taking the hart anyway",
                FRAME_DEADLINE.as_millis()
            );
            return false;
        }
        core::hint::spin_loop();
    }
    true
}

/// Deadline for one frame ack. The worst full-frame scan is about 44 ms, so this only fires when
/// the FLPR has genuinely stalled, which turns a hang into a reported error the caller retries.
pub const FRAME_DEADLINE: Duration = Duration::from_millis(250);

/// Deadline for the boot and relaunch `ALIVE` stamp. The FLPR normally stamps within a few of its
/// 5 ms poll periods, so a full second only expires when the core did not come up at all.
const ALIVE_DEADLINE: Duration = Duration::from_millis(1000);

/// Why [`launch_flpr`] gave up, surfaced so a panel that cannot come up degrades to a heartbeat
/// idle rather than driving an un-launched FLPR.
#[derive(defmt::Format)]
pub enum FlprError {
    /// The FLPR booted but the control-block magic mismatched: a memory-map drift between
    /// [`Control`] here and `flpr_control_t` in the C blob.
    BadMagic,
    /// No `ALIVE` stamp within the boot window — the FLPR didn't boot or can't reach shared RAM.
    NoBoot,
}

/// Copy the blob into FLPR RAM, set the boot vector, and release the core from reset. `INITPC` is
/// the entry address, and `CPURUN.EN = 1` starts execution there.
///
/// The caller owns parking the hart first. Re-copying the blob under a live core is the one thing
/// this must never do.
fn start_flpr() {
    unsafe {
        core::ptr::copy_nonoverlapping(FLPR_BLOB.as_ptr(), FLPR_RAM_BASE as *mut u8, FLPR_BLOB.len());
        // Make the blob + the control block visible to the other core before we release it.
        cortex_m::asm::dsb();
        VPR00_INITPC.write_volatile(FLPR_RAM_BASE as u32);
        VPR00_CPURUN.write_volatile(1); // EN = 1 → FLPR runs from INITPC
    }
}

/// Zero and arm the control block — the layout magic the FLPR checks first — then release the core.
/// The shared front half of [`launch_flpr`] and [`launch_flpr_blocking`].
fn arm_and_start() {
    // SAFETY: CONTROL is the SHARED-page control block at a fixed address no Rust object aliases,
    // and the FLPR is not yet running, so this pre-launch zero and arm races nothing.
    unsafe {
        core::ptr::write_bytes(CONTROL as *mut u8, 0, core::mem::size_of::<Control>());
        addr_of_mut!((*CONTROL).magic).write_volatile(LAYOUT_MAGIC); // FLPR reads magic first thing
    }
    // A relaunch hands the core a control block whose `flpr_seq` has just been zeroed, so the
    // in-flight marker must go with it, or `scan_in_flight` would compare a live sequence against a
    // counter that will never reach it again. A stale `ACKED_SEQ` would outlive the core that set it.
    SCAN_SEQ.store(0, Ordering::Relaxed);
    ACKED_SEQ.store(0, Ordering::Relaxed);
    start_flpr();
}

/// Arm the frame-ack doorbell: EGU20 TRIGGERED[0], its IRQ, then [`FRAME_ACK`]. P1 is the default
/// peripheral lane, below the P0 GRTC time driver. It is armed before the first push so no ack is
/// missed, and re-run on every relaunch; every step is idempotent.
fn arm_frame_ack() {
    // SAFETY: fixed EGU20 secure-alias MMIO; set-mask writes only.
    unsafe {
        EGU20_INTENSET.write_volatile(1); // bit0 = TRIGGERED[0]
        interrupt::EGU20.set_priority(Priority::P1);
        interrupt::EGU20.enable();
    }
}

/// Bring the FLPR up: zero and arm the control block, launch the core, and poll for its `ALIVE`
/// stamp. After this the [`Ls021Flpr`] backend can drive frames.
///
/// This is the boot and recovery path. It yields between polls, because a panel that comes up late
/// may take a chunk of the 1 s [`ALIVE_DEADLINE`] and there is nothing to gain from holding the
/// executor for it. The per-switch path is [`launch_flpr_blocking`].
pub async fn launch_flpr() -> Result<(), FlprError> {
    arm_and_start();
    info!("LS021 FLPR: released (INITPC=0x{=u32:08x}) — waiting for alive", FLPR_RAM_BASE as u32);

    let deadline = Instant::now() + ALIVE_DEADLINE;
    loop {
        match unsafe { addr_of!((*CONTROL).status).read_volatile() } {
            FLPR_ALIVE => {
                arm_frame_ack();
                crate::flpr_mux::note_display_live();
                return Ok(());
            }
            FLPR_BADMAG => return Err(FlprError::BadMagic),
            _ if Instant::now() >= deadline => return Err(FlprError::NoBoot),
            _ => Timer::after_millis(5).await,
        }
    }
}

/// The mode-switch launch: [`launch_flpr`]'s contract with a spin instead of a yield.
///
/// [`crate::flpr_mux::ensure_display`] runs from synchronous code, so the storage-to-display half of
/// the mux cannot use the async launch. Spinning is also the right shape: the whole switch measures
/// 138 µs, so a yield would cost more in scheduler round trips than the wait itself. Reaching
/// [`ALIVE_DEADLINE`] means the coprocessor is gone rather than slow, and the caller's push then
/// fails into the existing relaunch escalation.
pub fn launch_flpr_blocking() -> Result<(), FlprError> {
    arm_and_start();
    let deadline = Instant::now() + ALIVE_DEADLINE;
    loop {
        match unsafe { addr_of!((*CONTROL).status).read_volatile() } {
            FLPR_ALIVE => {
                arm_frame_ack();
                return Ok(());
            }
            FLPR_BADMAG => return Err(FlprError::BadMagic),
            _ if Instant::now() >= deadline => return Err(FlprError::NoBoot),
            _ => core::hint::spin_loop(),
        }
    }
}

/// Full FLPR relaunch, the recovery step for a wedged coprocessor: force-halt the hart through its
/// Debug Module, hold it in `ndmreset`, then rerun the whole bring-up — re-copy the blob, because a
/// hung FLPR may have been executing corrupted instructions, zero and re-arm the control block,
/// release the core, and await a fresh `ALIVE`.
///
/// The Debug Module dance exists because `CPURUN.EN = 0` cannot stop a wedged core: it only parks
/// one that executes a WFI, which the busy-polling scan blob never does. `haltreq` stops the hart
/// wherever it is, and `ndmreset` then resets it, so the blob re-copy never races live execution.
/// The halt wait is deadline-bounded and advisory; the reset is the guarantee.
///
/// COM is unaffected either way, so the panel stays DC-bias-safe through a dead FLPR and through
/// this relaunch. COM never ran on the FLPR, and the M33 keeps every gate and source GPIO
/// configured, so the glass holds its last image while the FLPR is down. That property is
/// load-bearing: keep COM off the FLPR whatever else moves there.
///
/// After an `Ok(())` the caller must force a full repaint: the fresh FLPR has no history, and rows
/// the diff store thinks are on glass may have missed it while the old FLPR was wedged. The
/// M33-side `Ls021Flpr::seq` deliberately keeps counting across the relaunch, because the blob
/// services any `m33_seq` different from the last one it saw.
pub async fn relaunch_flpr() -> Result<(), FlprError> {
    // If storage holds the hart, quiesce the sEMMC peripheral first — latched completions cleared,
    // the shared VPR00 interrupt gate disarmed, the pads handed back — so the halt below lands on a
    // coprocessor nothing is still talking to.
    crate::flpr_mux::quiesce_storage_if_active();
    // Force-halt through the Debug Module, which works mid-busy-loop, then bounded-wait for the ack.
    unsafe {
        VPR00_DMCONTROL.write_volatile(DM_DMACTIVE); // wake the DM first (its fields gate on dmactive)
        VPR00_DMCONTROL.write_volatile(DM_DMACTIVE | DM_HALTREQ);
    }
    let deadline = Instant::now() + HALT_DEADLINE;
    while unsafe { VPR00_DMSTATUS.read_volatile() } & DMSTATUS_ALLHALTED == 0 {
        if Instant::now() >= deadline {
            debug!("LS021 FLPR: relaunch — hart ignored haltreq; proceeding to ndmreset");
            break; // the reset below is the real guarantee
        }
        Timer::after_micros(100).await;
    }
    // Park the start gate, then pulse the hart reset while it is down: the blob re-copy in
    // `launch_flpr` must never race a live core.
    unsafe {
        VPR00_CPURUN.write_volatile(0); // the reset release must not restart stale code
        VPR00_DMCONTROL.write_volatile(DM_DMACTIVE | DM_NDMRESET);
        cortex_m::asm::dsb();
        VPR00_DMCONTROL.write_volatile(DM_DMACTIVE); // release the hart reset (still parked: CPURUN=0)
        VPR00_DMCONTROL.write_volatile(0); // DM back off — leave the block as boot found it
    }
    launch_flpr().await
}

/// Start a frame: write `cmd = CMD_RUN_FRAME`, then a `dsb`, then bump `m33_seq`, which is the
/// command doorbell. The barrier sits between the payload and the doorbell so the FLPR can never
/// observe the new sequence before the command word, the span list, the `fb_addr` and the
/// framebuffer pixels it guards. The trailing `dsb` drains the doorbell store for the polling FLPR.
fn ring_cmd(seq: u32) {
    unsafe {
        addr_of_mut!((*CONTROL).cmd).write_volatile(CMD_RUN_FRAME);
        cortex_m::asm::dsb(); // cmd + spans + descriptors complete BEFORE the doorbell below
        addr_of_mut!((*CONTROL).m33_seq).write_volatile(seq); // seq last = the command doorbell guard
        cortex_m::asm::dsb();
    }
}

/// Publish the dirty-row span list the FLPR's masked scan reads: each span a packed
/// `(start_row << 16) | count`, written ascending, capped at `MAX_DIRTY_SPANS`. These plain volatile
/// stores carry no barrier of their own: they are ordered before the FLPR sees the frame by the
/// `dsb` [`ring_cmd`] issues between them and its doorbell bump.
fn set_spans(spans: &[(u16, u16)]) {
    let n = spans.len().min(MAX_DIRTY_SPANS);
    unsafe {
        for (s, &(start, count)) in spans.iter().take(n).enumerate() {
            let packed = ((start as u32) << 16) | count as u32;
            addr_of_mut!((*CONTROL).spans[s]).write_volatile(packed);
        }
        addr_of_mut!((*CONTROL).n_spans).write_volatile(n as u32);
    }
}

/// Total rows across `spans`: the dirty-row count `status` must echo back.
fn span_row_total(spans: &[(u16, u16)]) -> usize {
    spans.iter().take(MAX_DIRTY_SPANS).map(|&(_, count)| count as usize).sum()
}

/// Dump the cross-core handshake state when a frame stalls. `m33_seq` ought to equal the sequence
/// just rung; `flpr_seq` is where the FLPR's poll loop last got to, and far behind means it never
/// saw the doorbell; `magic` should still be `LAYOUT_MAGIC`, and a different value means the SHARED
/// page was clobbered; `frame_count` is how many frames the FLPR has ever run. Together these
/// separate a hang mid-loop from a reset or fault from corrupted shared RAM.
fn dump_flpr_state(seq: u32) {
    let (magic, m33_seq, flpr_seq, status, frames) = unsafe {
        (
            addr_of!((*CONTROL).magic).read_volatile(),
            addr_of!((*CONTROL).m33_seq).read_volatile(),
            addr_of!((*CONTROL).flpr_seq).read_volatile(),
            addr_of!((*CONTROL).status).read_volatile(),
            addr_of!((*CONTROL).frame_count).read_volatile(),
        )
    };
    let cpurun = unsafe { VPR00_CPURUN.read_volatile() };
    error!(
        "LS021 FLPR: state @ stall — magic=0x{=u32:08x} (want 0x{=u32:08x}) m33_seq={=u32} (rang {=u32}) flpr_seq={=u32} status={=u32} frame_count={=u32} CPURUN.EN={=u32}",
        magic, LAYOUT_MAGIC, m33_seq, seq, flpr_seq, status, frames, cpurun & 1
    );
}

/// A transport fault: the FLPR stalled, with no frame ack or a status mismatch inside the deadline.
/// The caller keeps the last frame and retries.
#[derive(Debug)]
pub struct Stalled;

/// The LS021-over-FLPR presenter. The resident frame plane lives next to it as [`Frame64`], and the
/// pushes hand its bytes to the FLPR to scan directly. The contract impls are at the bottom of this
/// file.
pub struct Ls021Flpr<'b> {
    /// The self-diffing present store: a per-row hash of the last pushed framebuffer, so a present
    /// pushes only the rows that changed. The hashes track the clean frame and never the composited
    /// bulge, which rides its own overlay plane, so the store stays the source of truth for what the
    /// map present last put on glass.
    diff: &'b mut RowDiff<FB_H>,
    /// Per-frame command sequence, bumped each push and echoed back by the FLPR as the ack.
    seq: u32,
}

impl<'b> Ls021Flpr<'b> {
    /// Build the presenter for the resident device-64 plane. The app quantises to the device-64
    /// gamut itself and renders straight into the frame. The FLPR packs the frame straight to the
    /// wire, so there is no RGB565 band scratch.
    pub fn new(diff: &'b mut RowDiff<FB_H>) -> Self {
        Self { diff, seq: 0 }
    }

    /// Drive a span-masked frame to glass: publish the span list and the framebuffer address, ring
    /// the FLPR, and await the EGU20 frame ack. That is the M33's entire per-frame work; the FLPR
    /// packs every dirty row to the wire itself while thread mode runs other futures. The frame must
    /// not be written until the ack returns, which the shared borrow held across the present's await
    /// guarantees statically. Returns `true` if the ack checks out within [`FRAME_DEADLINE`].
    async fn run_spans(&mut self, fb: &[u8], spans: &[(u16, u16)]) -> bool {
        let total = span_row_total(spans);
        if total == 0 {
            return true; // nothing dirty — a no-op frame (defensive; callers pass ≥1 row)
        }
        let (s, t_frame) = self.ring_spans(fb, spans);
        let deadline = t_frame + FRAME_DEADLINE;

        // Await the frame ack. On a stale echo — a late ack of an older frame racing the reset in
        // `ring_spans` — keep waiting for ours until the deadline.
        loop {
            if with_deadline(deadline, FRAME_ACK.wait()).await.is_err() {
                error!(
                    "LS021 FLPR: frame TIMEOUT — no EGU20 ack for seq {=u32} within {=u64} ms (the scan stalled)",
                    s,
                    FRAME_DEADLINE.as_millis()
                );
                dump_flpr_state(s);
                SCAN_SEQ.store(0, Ordering::Relaxed); // the panel is wedged, not scanning — release storage
                return false;
            }
            // The FLPR writes `status` and `frame_count` before the `flpr_seq` ack, and its fence
            // orders them, so mirror that on the read side: the ack must never be reordered ahead of
            // the values it guards.
            cortex_m::asm::dmb();
            if unsafe { addr_of!((*CONTROL).flpr_seq).read_volatile() } == s {
                break;
            }
        }
        SCAN_SEQ.store(0, Ordering::Relaxed); // the frame is on glass — storage may take the hart
        self.check_ack(total, t_frame)
    }

    /// The blocking twin of [`run_spans`](Self::run_spans), for the overlay path only: the same ring
    /// and ack contract, but it spin-waits `flpr_seq` inside the deadline instead of awaiting EGU20.
    ///
    /// The overlay present's composite scratch and save window, about 9 KB, must stay stack
    /// transients: alive across an `await` they become part of the map-plane task's static future
    /// and permanently shrink the residual stack, which overflowed the first deep map render into
    /// `.bss`. An overlay push is a few milliseconds, so spinning is cheap. The EGU20 ISR still fires
    /// per frame, and the stale signal it leaves is dropped by the next async push's reset.
    fn run_spans_blocking(&mut self, fb: &[u8], spans: &[(u16, u16)]) -> bool {
        let total = span_row_total(spans);
        if total == 0 {
            return true;
        }
        let (s, t_frame) = self.ring_spans(fb, spans);
        let deadline = t_frame + FRAME_DEADLINE;
        while unsafe { addr_of!((*CONTROL).flpr_seq).read_volatile() } != s {
            if Instant::now() > deadline {
                error!(
                    "LS021 FLPR: overlay frame TIMEOUT — no ack for seq {=u32} within {=u64} ms (the scan stalled)",
                    s,
                    FRAME_DEADLINE.as_millis()
                );
                dump_flpr_state(s);
                SCAN_SEQ.store(0, Ordering::Relaxed);
                return false;
            }
            core::hint::spin_loop();
        }
        SCAN_SEQ.store(0, Ordering::Relaxed);
        cortex_m::asm::dmb(); // ack-read ordering, as in the async path (issue #346)
        self.check_ack(total, t_frame)
    }

    /// Publish the span list and the framebuffer address, drop any stale ack signal, and ring one
    /// `CMD_RUN_FRAME`. Returns the rung sequence and the frame's start time.
    ///
    /// This is the display side's single seam onto the mode mux: both pushes go through here, so
    /// taking the coprocessor back from storage is one call in one place. It is deliberately not
    /// fallible — a failed relaunch rings the doorbell at a dead core, the ack times out, and the
    /// existing `MapDisplay` escalation handles it, rather than this growing a second recovery
    /// ladder.
    fn ring_spans(&mut self, fb: &[u8], spans: &[(u16, u16)]) -> (u32, Instant) {
        crate::flpr_mux::ensure_display();
        self.seq += 1;
        let s = self.seq;
        // Publish before the doorbell: from here until the ack the FLPR owns the hart and storage
        // must wait. Both run paths clear it, on success and on timeout.
        SCAN_SEQ.store(s, Ordering::Relaxed);
        set_spans(spans);
        // SAFETY: a plain volatile store into the SHARED-page control block, which no Rust object
        // aliases; the FLPR reads it only after the `ring_cmd` doorbell below orders it.
        unsafe { addr_of_mut!((*CONTROL).fb_addr).write_volatile(fb.as_ptr() as u32) };
        // Drop any stale ack, so an async wait cannot be satisfied by history.
        FRAME_ACK.reset();
        let t_frame = Instant::now();
        ring_cmd(s);
        (s, t_frame)
    }

    /// The shared back half of a push: cross-check the FLPR's `status` against the dirty-row total.
    /// The caller has already matched `flpr_seq`.
    fn check_ack(&self, total: usize, t_frame: Instant) -> bool {
        let frame_us = t_frame.elapsed().as_micros();
        let status = unsafe { addr_of!((*CONTROL).status).read_volatile() };
        let frames = unsafe { addr_of!((*CONTROL).frame_count).read_volatile() };
        if status != total as u32 {
            error!("LS021 FLPR: frame MISMATCH — status={=u32} (want {=usize} dirty rows)", status, total);
            return false;
        }
        // The ride loop's own frame line reports the push time; this is the per-push internal
        // breakdown, kept at `debug` so a build can opt into it without flooding the log.
        debug!(
            "LS021 FLPR: frame OK — FLPR scanned {=usize} dirty rows (frame #{=u32}) in {=u64} µs (~{=u64} µs/row)",
            total,
            frames,
            frame_us,
            frame_us / total as u64,
        );
        true
    }

    /// Drive only the rows in `spans` to glass. The FLPR packs each straight from the resident
    /// framebuffer, fast-forwards the gate over the gaps and stops after the last dirty row, so a
    /// vertically compact region costs a fraction of a full frame. Spans are `(start_row, count)`,
    /// ascending and disjoint, and at most `MAX_DIRTY_SPANS` of them.
    pub async fn push_spans(&mut self, frame: &Frame64, spans: &[(u16, u16)]) -> bool {
        self.run_spans(frame.bytes(), spans).await
    }

    /// Drive the whole resident frame to glass. It does not touch the [`RowDiff`] store, because it
    /// is a raw push and not a diff, so the first self-diffing present still re-seeds the store and
    /// pushes the whole frame, which is what the datasheet's Initial #0 sequence relies on.
    pub async fn push_frame(&mut self, frame: &Frame64) -> bool {
        self.push_spans(frame, &[(0, FB_H as u16)]).await
    }

    /// Re-arm the self-diffing present so the next present pushes the whole frame again and re-seeds
    /// the store: the recovery path when a push failed to reach glass. The present advances the
    /// row-hash store before the push, so after a fault the store already records the un-pushed
    /// frame, and a plain retry would diff an identical frame against an up-to-date store and push
    /// nothing, stranding the rows that missed glass.
    pub fn reset_diff(&mut self) {
        self.diff.reset();
    }
}

// The display contracts, as thin adapters over the panel methods above. The FLPR launch and the
// direct-framebuffer transport stay this module's business, but the app reaches glass only through
// the (`Frame64`, `Ls021Flpr`) pairing, which is the panel-swap point. The only LS021-specific code
// is the wire pack the pushes drive on the FLPR; the diff, clip and overlay composite are the
// shared, conformance-tested `obc_display::ls021` pieces.

impl Presenter<Frame64> for Ls021Flpr<'_> {
    type Damage = RowDamage;
    type Error = Stalled;

    fn damage_full() -> RowDamage {
        RowDamage::Full
    }

    fn damage_unknown() -> RowDamage {
        RowDamage::SelfDiff { exclude: None }
    }

    /// The self-diffing present: re-hash every frame row against the [`RowDiff`] store and push only
    /// the rows that changed, optionally clipping the live hold bulge's rows out so the overlay
    /// present owns them. `RowDamage::Full` re-seeds the store and pushes the whole frame, and the
    /// first present after boot or a [`reset_diff`](Ls021Flpr::reset_diff) does the same through the
    /// store's priming flag.
    ///
    /// The diff, clip and fallback skeleton is the shared [`RowDiff::diff_clipped`]. The shared
    /// borrow of the frame held across the ack is what statically keeps the renderer off the bytes
    /// the FLPR is scanning. `Err(Stalled)` is a transport fault: the caller keeps the last frame.
    async fn present(&mut self, frame: &Frame64, damage: RowDamage) -> Result<PresentStats, Stalled> {
        let exclude = match damage {
            RowDamage::Full => {
                self.diff.reset(); // full = re-seed the store + push every row (recovery/re-init)
                None
            }
            RowDamage::SelfDiff { exclude } => exclude,
        };
        let mut scratch = [(0u16, 0u16); MAX_DIRTY_SPANS];
        let spans = self.diff.diff_clipped(frame.bytes(), FB_W, exclude, &mut scratch);
        if spans.is_empty() {
            // Nothing changed outside the bulge, so push nothing.
            return Ok(PresentStats { pushed_units: 0, total_units: FB_H as u32, regions: 0 });
        }
        let pushed: u32 = spans.iter().map(|&(_, n)| n as u32).sum();
        let regions = spans.len() as u32;
        if self.run_spans(frame.bytes(), spans).await {
            Ok(PresentStats { pushed_units: pushed, total_units: FB_H as u32, regions })
        } else {
            Err(Stalled)
        }
    }
}

impl OverlayPresenter<Frame64> for Ls021Flpr<'_> {
    type Region = RowWindow;
    type OverlayTarget<'t> = Band<'t>;

    fn region(rect: Rectangle) -> RowWindow {
        RowWindow::from_rect(rect, FB_W as u32, FB_H as u32)
    }

    fn damage_around(region: RowWindow) -> RowDamage {
        RowDamage::SelfDiff { exclude: Some(region.exclude_span()) }
    }

    /// Re-present only the rows of the overlay region, with `draw` composited over the clean frame
    /// backdrop: the few-millisecond partial push the hold bulge rides over a static map. The LS021
    /// is row-addressed, so touching a row re-latches all 240 columns; this rewrites the full-width
    /// rows `[y0, y0+rows)` while only the `[x0, x0+w)` columns carry the overlay, and the FLPR
    /// fast-forwards the gate to `y0` and stops after `y0+rows`.
    ///
    /// The FLPR scans the frame directly, so the composited window must transiently be in it. The
    /// shared [`composite_into_resident`] engine saves the clean window bytes, writes the composited
    /// window in, re-quantised to device-64 by the same packer the frame was rendered with, pushes
    /// the rows, and restores. That is sound because the map plane owns the frame and is inside this
    /// call for the whole push, and the input plane never touches the frame. The [`RowDiff`] store
    /// keeps tracking the clean frame throughout: after the restore the frame is byte-identical, so
    /// the store is never touched. On a push fault the window is still restored.
    ///
    /// The overlay is rendered into a small RGB565 window scratch once, so the caller's `InputPlane`
    /// lock is taken once per strip and not once per row.
    ///
    /// Deliberately blocking, with no await point in this body: the scratches stay poll-stack
    /// transients. Across an `await` those 9 KB would move into the map-plane task's static future
    /// and permanently shrink the residual stack.
    async fn present_overlay(
        &mut self,
        frame: &mut Frame64,
        region: RowWindow,
        draw: impl for<'t> FnOnce(&mut Band<'t>),
    ) -> Result<PresentStats, Stalled> {
        let (x0, y0, w, rows) = (region.x0 as usize, region.y0 as usize, region.w as usize, region.rows as usize);
        assert!(
            w <= MAX_OVERLAY_COLS && rows <= MAX_OVERLAY_ROWS && x0 + w <= FB_W && y0 + rows <= FB_H,
            "overlay region out of bounds / larger than the composite scratch"
        );
        let mut win = [0u16; MAX_OVERLAY_COLS * MAX_OVERLAY_ROWS];
        let mut save = [0u8; MAX_OVERLAY_COLS * MAX_OVERLAY_ROWS];
        let mut draw = Some(draw);
        composite_into_resident(
            frame.bytes_mut(),
            Size::new(FB_W as u32, FB_H as u32),
            region,
            OverlayScratch { win: &mut win, save: &mut save },
            &mut |band| {
                if let Some(d) = draw.take() {
                    d(band)
                }
            },
            |fb| if self.run_spans_blocking(fb, &[(region.y0, region.rows)]) { Ok(()) } else { Err(Stalled) },
        )
        .map(|()| PresentStats { pushed_units: region.rows as u32, total_units: FB_H as u32, regions: 1 })
    }
}
