//! The microSD host: Nordic's sEMMC soft peripheral on the FLPR.
//!
//! The nRF54L has no SD host controller. Nordic ships one as a soft peripheral: a small
//! position-independent RISC-V image that the FLPR (the VPR00 coprocessor) executes, turning six
//! GPIOs into a 4-bit SD bus. The M33 fills in a register block, the VRI, that lives in the image's
//! own RAM carve, and pokes VPR tasks; the FLPR does the clocking, CRC and framing. Measured on
//! glass: 14.7 MB/s read (CMD18, 256 blocks, 32 MHz, 4-bit) and 8.2 MB/s write (CMD25, 21.3 MHz).
//!
//! The image is vendored at `vendor/semmc/`. Its carve is defined once in `build.rs`'s `contract`
//! module, which emits the constants included below, shrinks the M33's RAM region to match, and
//! cross-checks both against the image's own metadata header, so a blob update cannot silently
//! mis-size the carve.
//!
//! The public surface is the whole sequence and nothing below it: [`Semmc::start`] once per
//! power-on, then `enter_storage_mode` and `leave_storage_mode` per handover, and the two transfer
//! calls. Every one of them is synchronous. `start` waits in milliseconds but blocks rather than
//! yields, because awaiting it from `main` flattens the whole chain into `main`'s permanent
//! task-body poll frame. Boot, enable and card identification are private: law 1 is only a law if a
//! caller cannot boot the firmware without powering it on.
//!
//! ## The three laws (violating any one gives a silent hang)
//!
//! 1. Boot leaves the firmware INITIALIZED, not powered on. It ignores start triggers until
//!    `ENABLE = 1` is followed by an `__ASB` barrier ([`Semmc::enable`]). Skipping it gives a dead
//!    bus with no clock activity and nothing to see in the VRI.
//! 2. Every completion needs the transaction-close ack: `CONFIG.READYTOTRANSFER = 0` plus an
//!    `__ASB` ([`Semmc::close_transaction`]). Skipping it makes the first command after a boot work
//!    and the second time out, forever.
//! 3. R2 responses land LSW-first: `RESPONSE[0]` is bits 31:0 and `RESPONSE[3]` is bits 127:96.
//!    Every CID and CSD decode here is written against that order.
//!
//! ## The barrier
//!
//! Every state change is fenced by one of the soft-peripheral `__XSBx` macros: write the host
//! counter into `SPSYNC.AUX[0]`, trigger the matching VPR task (`__CSB` 17 for config, `__ASB` 18
//! for action, `__SSB` 19 for stop), then spin until the firmware echoes the counter into `AUX[1]`.
//! It takes about 2.2 µs. Start is task 16, and completion raises the VRI's
//! `EVENTS_XFERCOMPLETE` or `ABORTED` plus VEVIF event 20, which is `VPR00_IRQn` (see
//! [`on_vpr00_irq`]).
//!
//! ## The two blob warts, and the workarounds that beat them
//!
//! The image's per-index transfer table is hard-coded to eMMC semantics, and data descriptors on
//! indexes it thinks carry no data are ignored. Two SD commands fall in the gap:
//!
//! - CMD8: eMMC index 8 is `SEND_EXT_CSD`, a 512 B read, while SD's `SEND_IF_COND` is
//!   response-only, so the host wait never completes. Deliver and abort: send it, wait about 3 ms
//!   so the card's R7 reaches the wire, abandon the wait with `__SSB`, ack, continue. See
//!   [`Semmc::cmd8_deliver_abort`].
//! - CMD6: eMMC index 6 is `SWITCH`, an R1b with no data, while SD's `SWITCH_FUNC` streams a 64 B
//!   status block that is then orphaned, which leaves the card stuck in `data`. Drain read: follow
//!   it with a CMD17 at `NUMRETRIES = 0`, or the firmware's retry hunts for a second start bit
//!   forever. The card ignores the CMD17, because it is illegal in `data`, while the firmware's
//!   512 B read engine supplies exactly the clocks the orphaned block needs and lands it in our
//!   buffer, where `byte16 & 0xF == 1` is the card's own High-Speed confirmation. See
//!   [`Semmc::cmd6_high_speed`].
//!
//! Both disappear if Nordic ships a VRI data-phase override that beats the index table.
//!
//! This module never panics and never waits without a deadline, and the deadline is reachable with
//! no interrupts arriving at all, which is why [`Semmc::wait_completion`] is a bounded poll with an
//! interrupt fast path and not the `WFE` sleep it looks like it should be. Every failure is a
//! [`SemmcError`].

use core::sync::atomic::{AtomicBool, Ordering};

use defmt::warn;
use embassy_nrf::pac;
use embassy_nrf::pac::gpio::vals::{Ctrlsel, Dir, Drive, Input, Pull};
use embassy_time::{block_for, Duration, Instant};

// The sEMMC carve, generated by build.rs's `contract` module, which is the single definition site:
// it also derives the carved `memory.x` RAM shrink from these values and asserts them against the
// vendored image's metadata header.
include!(concat!(env!("OUT_DIR"), "/semmc_contract.rs"));

/// Nordic's sEMMC image: position-independent RISC-V for the FLPR. `LicenseRef-Nordic-5-Clause`;
/// see `vendor/semmc/README.md` for provenance and regeneration.
static SEMMC_FW: &[u8] = include_bytes!("../vendor/semmc/semmc_firmware_v0.1.1.bin");

/// The vendored image's bytes: what the DFU armer stages into the `SEMMC_STAGE` RRAM carve for the
/// bootloader. The armer and this driver must agree on it, so both read this accessor rather than a
/// second `include_bytes!`.
pub fn firmware_image() -> &'static [u8] {
    SEMMC_FW
}

const _: () = assert!(SEMMC_IMAGE_BYTES <= SEMMC_CARVE_BYTES);
const _: () = assert!(SEMMC_VRI_OFFSET >= SEMMC_CODE_BYTES, "the VRI window must sit above the image's code region");
const _: () = assert!(SEMMC_RAM_BASE.is_multiple_of(4096), "the image base must stay 4 KiB aligned");

// VRI register offsets, from nrfxlib's `nrf_sp_emmc.h` `NRF_SP_EMMC_Type`.
const VRI_EV_XFERCOMPLETE: usize = 0x10;
const VRI_EV_ABORTED: usize = 0x14;
const VRI_EV_READYTOTRANSFER: usize = 0x18;
const VRI_INTEN: usize = 0x28;
const VRI_ENABLE: usize = 0x2C;
const VRI_CFG_READYTOTRANSFER: usize = 0x30;
const VRI_CFG_CLKFREQHZ: usize = 0x34;
const VRI_CFG_BUSWIDTH: usize = 0x38;
const VRI_CFG_NUMRETRIES: usize = 0x3C;
const VRI_CFG_READDELAY: usize = 0x40;
const VRI_CMD_CMD: usize = 0x44; // IDX | RESPTYPE << 16 | RESPPROC << 24
const VRI_CMD_ARG: usize = 0x48;
const VRI_CMD_RESPONSEADDR: usize = 0x4C;
const VRI_CMD_RESPONSE0: usize = 0x50; // [4] processed response words, **LSW first** (law 3)
const VRI_DATA_BUFFERADDR: usize = 0x64;
const VRI_DATA_BLOCKSIZE: usize = 0x68;
const VRI_DATA_BLOCKNUM: usize = 0x6C;
const VRI_STATUS: usize = 0x70;
const VRI_SPSYNC_AUX: usize = 0x74; // [6]; barrier: host counter in [0], firmware echo in [1]

/// `INTEN` mask: XFERCOMPLETE | ABORTED | READYTOTRANSFER → VEVIF event 20.
const VRI_INTEN_ALL: u32 = 0x7;

// `STATUS.STATUS` bit positions, which are the diagnosis carried out of an abort.
const STATUS_CMDTIMEOUT: u32 = 1 << 0;
const STATUS_CMDCRCERROR: u32 = 1 << 1;
const STATUS_DATACRCERROR: u32 = 1 << 2;
const STATUS_RETRYEXCEEDED: u32 = 1 << 3;
const STATUS_PROTOCOLERR: u32 = 1 << 4;

// Response types (`SP_EMMC_COMMAND_CMD_RESPTYPE_*`). SD's R6 and R7 are R1-shaped on the wire, so
// they ride `RESP_R1`.
const RESP_NONE: u32 = 0;
const RESP_R1: u32 = 1;
const RESP_R1B: u32 = 2;
const RESP_R2: u32 = 3;
const RESP_R3: u32 = 4;
// Response processing. `IGNORE` exists because the firmware cannot process a response and a data
// phase at the same time, so reads ignore the response and ask again with CMD13.
const PROC_PROCESS: u32 = 0;
const PROC_IGNORE: u32 = 1;

// Soft-peripheral VPR task and event indices, from `softperipheral_regif.h`'s nRF54L row.
const T_START: usize = 16; // start a prepared transfer (the DPPI start task)
const T_CONFIG: usize = 17; // __CSB — configuration barrier
const T_ACTION: usize = 18; // __ASB — action barrier
const T_STOP: usize = 19; // __SSB — stop/abort barrier
const EV_COMPLETION: usize = 20; // VEVIF completion event → VPR00_IRQn

// VPR00, the secure alias. Raw MMIO, because these registers are not in embassy-nrf's PAC surface.
const VPR00_TASKS_TRIGGER: *mut u32 = 0x5004_C000 as *mut u32;
const VPR00_EVENTS_TRIGGERED: *mut u32 = 0x5004_C100 as *mut u32;
const VPR00_INTENSET: *mut u32 = 0x5004_C304 as *mut u32;
const VPR00_INTENCLR: *mut u32 = 0x5004_C308 as *mut u32;
const VPR00_CPURUN: *mut u32 = 0x5004_C800 as *mut u32;
const VPR00_INITPC: *mut u32 = 0x5004_C808 as *mut u32;
const VPR00_DMCONTROL: *mut u32 = 0x5004_C440 as *mut u32;
const DM_DMACTIVE: u32 = 1 << 0;
const DM_NDMRESET: u32 = 1 << 1;

// Pins. The order is Nordic's, not sequential.
/// `(P2 pin, sEMMC role)` for the six card pads.
const SD_PADS: [(usize, &str); 6] = [(0, "D3"), (1, "CLK"), (2, "D0"), (3, "D2"), (4, "D1"), (5, "CMD")];
/// The two pads time-shared with the display's B0/B1 data lines. They are the only ones the
/// display side drives, and the only ones that need an internal pull-up in storage mode: this
/// breakout carries its own resistors on CLK/D0/D2/CMD, and the production board fits external
/// pull-ups on CMD and DAT0-3 and then runs all internal pulls off.
const SHARED_PADS: [usize; 2] = [0, 4];
/// The four pads only storage uses. They are parked as inputs in display mode, where the external
/// pull-ups hold the bus in its SD idle-high state.
const CARD_ONLY_PADS: [usize; 4] = [1, 2, 3, 5];

// Clocks. Legal values are 128 MHz over an even divisor of 4 or more.
/// SD card-identification clock, at divisor 320.
const CLK_INIT_HZ: u32 = 400_000;
/// Default Speed data clock: what the card runs at before the High-Speed switch, and the write
/// clock afterwards.
const CLK_DS_HZ: u32 = 21_333_333;
/// High Speed read clock, after CMD6.
const CLK_HS_HZ: u32 = 32_000_000;
/// Writes cap at 21.3 MHz. 32 MHz writes fail card-side CRC on the jumper harness, which is a
/// clean failure that programs nothing, while 32 MHz reads are spotless. The clock is
/// per-transaction config, so a mixed rate is free.
const CLK_WRITE_MAX_HZ: u32 = CLK_DS_HZ;

/// Retries the firmware makes per transaction. Zero only for the CMD6 drain read, where a retry
/// would hunt for a second start bit forever.
const NUM_RETRIES: u32 = 3;
/// Additional whole-command attempts after a transient read abort. The firmware's internal retries
/// do not cover the observed RF-correlated `EVENTS_ABORTED` result, and replaying a read is free of
/// side effects once the failed transfer has been stopped.
const READ_ABORT_RETRIES: usize = 2;

// Deadlines. Every wait in this module is bounded by one of these, and none of them is hit in
// normal operation: their job is to turn a wedge into a reported error.
const BARRIER_DEADLINE: Duration = Duration::from_millis(50);
const BOOT_DEADLINE: Duration = Duration::from_millis(500);
const CMD_DEADLINE: Duration = Duration::from_millis(500);
const STATUS_DEADLINE: Duration = Duration::from_millis(250);
const READ_DEADLINE: Duration = Duration::from_millis(2000);
const WRITE_DEADLINE: Duration = Duration::from_millis(4000);
/// How long the card may stay in `prg` after a write before we call it stuck.
const PROGRAM_DEADLINE: Duration = Duration::from_millis(1000);
/// ACMD41 power-up poll window.
const POWERUP_DEADLINE: Duration = Duration::from_millis(1500);
/// How long the card's R7 gets to reach the wire in the CMD8 deliver-and-abort workaround.
const CMD8_DELIVER: Duration = Duration::from_micros(3000);
/// Card power-up settle before the first CMD0. The SD spec wants at least 1 ms of stable supply
/// plus 74 clocks. This runs only at [`Semmc::start`], and is deliberately absent from the
/// per-switch [`Semmc::enter_storage_mode`] path, where the card needs nothing.
const CARD_SETTLE: Duration = Duration::from_millis(10);
/// ACMD41 poll interval while the card powers up.
const POWERUP_POLL: Duration = Duration::from_millis(10);
/// Re-check granularity in [`Semmc::wait_completion`]: about 5 µs at the core clock. See that
/// function for why this is a bounded slice rather than a `WFE`.
const WAIT_SLICE_CYCLES: u32 = 640;

/// SD bytes per block. Fixed: the layers above assume it and SDHC and SDXC cards cannot be told
/// otherwise.
pub const BLOCK_BYTES: usize = 512;
/// `CURRENT_STATE` in an R1: the transfer state. Anything else means a transfer must not start.
pub const CARD_STATE_TRAN: u8 = 4;
/// `CURRENT_STATE`: the card is programming (the completion signal for a write).
const CARD_STATE_PRG: u8 = 7;
/// R1 error bits, per the SD Physical Layer spec's card-status table, derived per bit rather than
/// copied, because the difference between an error and a status flag is the difference between a
/// failed read and a working one.
///
/// Deliberately excluded, for two different reasons. `CARD_ECC_DISABLED` (14), `ERASE_RESET` (13)
/// and `CARD_IS_LOCKED` (25) are status bits or a state in the spec's own classification, so
/// failing a read on them would be a bug. `AKE_SEQ_ERROR` (3) is an error bit, but this driver
/// never runs the authentication sequence it reports on, so failing every later read over a feature
/// we do not use would be the worse outcome.
const R1_ERROR_MASK: u32 = (1 << 31)  // OUT_OF_RANGE
    | (1 << 30)                       // ADDRESS_ERROR
    | (1 << 29)                       // BLOCK_LEN_ERROR
    | (1 << 28)                       // ERASE_SEQ_ERROR
    | (1 << 27)                       // ERASE_PARAM
    | (1 << 26)                       // WP_VIOLATION
    | (1 << 24)                       // LOCK_UNLOCK_FAILED
    | (1 << 23)                       // COM_CRC_ERROR
    | (1 << 22)                       // ILLEGAL_COMMAND
    | (1 << 21)                       // CARD_ECC_FAILED
    | (1 << 20)                       // CC_ERROR (internal controller error)
    | (1 << 19)                       // ERROR (generic, unknown)
    | (1 << 16)                       // CSD_OVERWRITE
    | (1 << 15); // WP_ERASE_SKIP

/// Set by [`on_vpr00_irq`]. The completion wait sleeps on this rather than spinning on the VRI, but
/// the VRI events stay the authority (see [`Semmc::wait_completion`]).
static COMPLETION: AtomicBool = AtomicBool::new(false);
/// One-shot latch so "no completion interrupt ever arrived" is diagnosed once, not per block.
static WARNED_NO_IRQ: AtomicBool = AtomicBool::new(false);

/// The `VPR00_IRQn` handler body: call this from the vector.
///
/// It is a plain function so the transfer-state mutation stays with the sEMMC driver while
/// `board.rs` owns the hardware vector binding. `main.rs` arms the NVIC line once. The VRI-side
/// gate (`INTEN`) and the VEVIF gate (`VPR00.INTENSET` bit 20) are armed by
/// [`Semmc::boot_firmware`] on every boot, because `INTENSET` writes are silently dropped while the
/// VPR core is stopped.
///
/// The latched VEVIF event must be cleared, or the level-triggered IRQ re-fires forever.
pub fn on_vpr00_irq() {
    // SAFETY: a fixed MMIO address in the VPR00 secure alias; no Rust object aliases it.
    unsafe { VPR00_EVENTS_TRIGGERED.add(EV_COMPLETION).write_volatile(0) };
    COMPLETION.store(true, Ordering::Release);
}

/// Why a storage operation failed. Every variant is returned, never panicked or hung on.
///
/// `Debug` is not decoration: `embedded_sdmmc::BlockDevice::Error` requires it. The real
/// diagnostics stay `defmt::Format`.
#[derive(Clone, Copy, PartialEq, Eq, Debug, defmt::Format)]
pub enum SemmcError {
    /// A second command tried to start while a deferred write still owned the peripheral.
    Busy,
    /// The firmware never echoed a barrier counter — it is wedged (or was never booted).
    Barrier,
    /// The image never stamped ready after a boot.
    NoBoot,
    /// No completion within the operation's deadline. The firmware has been recovered — a warm
    /// reboot and power-on — before this returns, so the next command starts from a known state.
    Timeout,
    /// The firmware raised `EVENTS_ABORTED`; the payload is its `STATUS` register
    /// (`CMDTIMEOUT` / `CMDCRCERROR` / `DATACRCERROR` / `RETRYEXCEEDED` / `PROTOCOLERR`).
    Aborted(u32),
    /// The card answered, but its R1 carries error bits.
    CardStatus(u32),
    /// The card did not leave `prg` (or reach `tran`) within the deadline.
    CardBusy,
    /// Card identification did not complete — no card, an unpowered socket, or a broken bus.
    NoCard,
    /// The card is not an SDHC or SDXC card. SDSC is byte-addressed and caps at 2 GB, and nothing
    /// this device stores fits on one, so it is rejected rather than half-supported.
    UnsupportedCard,
    /// The caller's buffer is not a whole number of 512 B blocks, is empty, or is not 32-bit
    /// aligned — the firmware's DMA requires all three.
    BadBuffer,
    /// The requested block span runs past the card's capacity.
    OutOfRange,
    /// A transfer was attempted before [`Semmc::init_card`] succeeded.
    NotInitialised,
    /// The transport's failure latch is open, so the operation was refused without touching the
    /// device. See [`crate::flpr_mux::with_storage`].
    Unhealthy,
}

impl SemmcError {
    /// Whether the device was actually attempted, which is what the transport's health latch
    /// counts. A caller-side refusal costs microseconds and says nothing about the card, so it must
    /// neither extend a failure run nor clear one.
    ///
    /// The match is exhaustive on purpose: a new variant has to be classified here or the board
    /// does not build. The refusals are `check_request`'s three, `start_write_blocks`'s deferred
    /// write, and the latch's own answer; everything else reached the bus or the soft peripheral.
    pub const fn is_transport_fault(self) -> bool {
        match self {
            SemmcError::BadBuffer
            | SemmcError::OutOfRange
            | SemmcError::NotInitialised
            | SemmcError::Busy
            | SemmcError::Unhealthy => false,
            SemmcError::Barrier
            | SemmcError::NoBoot
            | SemmcError::Timeout
            | SemmcError::Aborted(_)
            | SemmcError::CardStatus(_)
            | SemmcError::CardBusy
            | SemmcError::NoCard
            | SemmcError::UnsupportedCard => true,
        }
    }

    /// Decode an [`Aborted`](Self::Aborted) status word for the log.
    pub fn abort_reason(status: u32) -> &'static str {
        if status & STATUS_CMDTIMEOUT != 0 {
            "command timeout (card silent)"
        } else if status & STATUS_CMDCRCERROR != 0 {
            "command CRC"
        } else if status & STATUS_DATACRCERROR != 0 {
            "data CRC (clock too high for the wiring?)"
        } else if status & STATUS_RETRYEXCEEDED != 0 {
            "retries exceeded"
        } else if status & STATUS_PROTOCOLERR != 0 {
            "protocol error"
        } else {
            "unclassified"
        }
    }
}

#[derive(Clone, Copy, defmt::Format)]
pub struct CardInfo {
    /// Relative card address, from CMD3.
    pub rca: u16,
    /// Capacity in 512 B blocks, from the CSD.
    pub blocks: u32,
    /// Whether the CMD6 High-Speed switch took (and the bus therefore reads at 32 MHz).
    pub high_speed: bool,
    pub read_clk_hz: u32,
}

const VRI_BASE: usize = SEMMC_RAM_BASE + SEMMC_VRI_OFFSET;

#[inline(always)]
fn vri_read(off: usize) -> u32 {
    // SAFETY: the VRI page is inside the carve, which is RAM the linker does not hand to the M33,
    // so no Rust object aliases it. The firmware mutates it concurrently, hence volatile.
    unsafe { ((VRI_BASE + off) as *const u32).read_volatile() }
}

#[inline(always)]
fn vri_write(off: usize, v: u32) {
    // SAFETY: as above.
    unsafe { ((VRI_BASE + off) as *mut u32).write_volatile(v) }
}

/// Stop the FLPR hart, whatever it is doing.
///
/// `CPURUN = 0` alone does not stop a running VPR core — it only parks one that reaches a WFI, which
/// neither soft-peripheral image ever executes. The pulsed `ndmreset` through the RISC-V Debug
/// Module is the actual guarantee.
///
/// This is Nordic's `nrf_semmc_uninit` recipe, and it is not the same sequence as
/// `ls021_flpr::relaunch_flpr`, which additionally issues a `haltreq` and waits for
/// `DMSTATUS.allhalted` before resetting. Both stop the hart; this is the 29 µs one the mode-switch
/// numbers were measured with.
pub fn park_hart() {
    // SAFETY: fixed VPR00 MMIO; parking the coprocessor cannot corrupt M33 state.
    unsafe {
        VPR00_CPURUN.write_volatile(0);
        VPR00_DMCONTROL.write_volatile(DM_NDMRESET | DM_DMACTIVE);
        VPR00_DMCONTROL.write_volatile(DM_DMACTIVE);
        VPR00_DMCONTROL.write_volatile(0);
    }
}

fn cfg_pad(pin: usize, dir: Dir, input: Input, pull: Pull, drive: Drive, ctrl: Ctrlsel) {
    pac::P2_S.pin_cnf(pin).modify(|w| {
        w.set_dir(dir);
        w.set_input(input);
        w.set_pull(pull);
        w.set_drive0(drive);
        w.set_drive1(drive);
        w.set_ctrlsel(ctrl);
    });
}

/// The high-speed pad bias: one constant global value, deliberately.
///
/// `GPIOHSPADCTRL.BIAS` is a port-wide trim, not a per-pin field, so the two modes cannot each own
/// one: whatever the last writer set is what both buses run at. So both pad configurations apply
/// the same value instead of restoring per mode. 2 is Nordic's porting-guide value for the card at
/// 32 MHz, and it is the binding constraint: the panel's source bus is three orders of magnitude
/// below anything the bias trim helps with. Setting it in both places is what makes it constant
/// rather than a value that depends on session history.
const HS_PAD_BIAS: u8 = 2;

/// Storage mode pads: all six card pads become VPR-controlled outputs with the input buffer
/// disconnected and the extra-high E0/E1 drive that 32 MHz needs, plus the high-speed pad bias.
/// Internal pull-ups go on D3 and D1 only: the other four carry the breakout's own resistors, and
/// 13 kΩ in parallel with 10 kΩ would sit under the SD spec's 10 kΩ floor.
pub fn configure_storage_pads() {
    for (pin, _) in SD_PADS {
        let pull = if SHARED_PADS.contains(&pin) { Pull::Pullup } else { Pull::Disabled };
        cfg_pad(pin, Dir::Output, Input::Disconnect, pull, Drive::E, Ctrlsel::Vpr);
    }
    pac::GPIOHSPADCTRL_S.bias().modify(|w| w.set_hsbias(HS_PAD_BIAS));
}

/// Display mode pads: hand the two shared pads back to the display blob, which drives them as B0
/// and B1 through plain `OUTSET` and `OUTCLR`, and park the four card-only pads as high-Z inputs,
/// where the external pull-ups hold the bus in the SD idle-high state. The card keeps its `tran`
/// and High-Speed state across the whole excursion; nothing here re-initialises it.
pub fn configure_display_pads() {
    for pin in SHARED_PADS {
        cfg_pad(pin, Dir::Output, Input::Disconnect, Pull::Disabled, Drive::S, Ctrlsel::Gpio);
    }
    for pin in CARD_ONLY_PADS {
        cfg_pad(pin, Dir::Input, Input::Disconnect, Pull::Disabled, Drive::S, Ctrlsel::Gpio);
    }
    // The same port-global bias as storage mode, set here too on purpose (see [`HS_PAD_BIAS`]).
    // This is what takes the panel off the reset default at the first display-pad configuration,
    // rather than at whenever the first card access happens to land.
    pac::GPIOHSPADCTRL_S.bias().modify(|w| w.set_hsbias(HS_PAD_BIAS));
}

/// Response landing zone. Nordic documents four words; twice that is 32 B of `.bss` bought as
/// insurance against a firmware that writes past its own contract.
#[repr(C, align(4))]
struct RespRaw([u32; 8]);
static mut RESP_RAW: RespRaw = RespRaw([0; 8]);

/// A 32-bit-aligned single block — the shape every buffer handed to the firmware must have.
#[repr(C, align(4))]
struct AlignedBlock([u8; BLOCK_BYTES]);

/// The sEMMC host. One instance owns the FLPR while it is in storage mode; `flpr_mux`'s mode
/// scheduler owns *when* that is.
pub struct Semmc {
    clk_hz: u32,
    /// 1 or 4. Mirrors `CONFIG.BUSWIDTH`.
    bus_width: u32,
    /// Firmware data-sampling offset in FLPR clock cycles. 0 is enough on the jumper harness at
    /// 32 MHz; a marginal harness may need 1 to 3. It is exposed through
    /// [`set_read_delay`](Self::set_read_delay) rather than auto-tuned, because a silent retune
    /// would hide a wiring fault.
    read_delay: u32,
    num_retries: u32,
    /// Barrier handshake counter (wraps; only equality with the firmware's echo matters).
    counter: u32,
    rca: u32,
    card: Option<CardInfo>,
    read_clk_hz: u32,
    write_clk_hz: u32,
    /// Whether this card accepted SD's optional pre-erase hint (ACMD23). It starts optimistic and
    /// falls back permanently after the first refusal; the hint affects throughput, never
    /// correctness.
    preerase_supported: bool,
    /// Block count of a write whose data phase is running on the FLPR. Zero means idle.
    ///
    /// Normal callers use [`write_blocks`](Self::write_blocks), which starts and finishes in one
    /// call. The USB map uploader splits the halves, so the M33 can receive into one arena half
    /// while the coprocessor clocks the other.
    pending_write_blocks: u32,
}

impl Default for Semmc {
    fn default() -> Self {
        Self::new()
    }
}

impl Semmc {
    /// A host that has not booted the firmware yet.
    pub const fn new() -> Self {
        Self {
            clk_hz: CLK_INIT_HZ,
            bus_width: 1,
            read_delay: 0,
            num_retries: NUM_RETRIES,
            counter: 0,
            rca: 0,
            card: None,
            read_clk_hz: CLK_DS_HZ,
            write_clk_hz: CLK_WRITE_MAX_HZ,
            preerase_supported: true,
            pending_write_blocks: 0,
        }
    }

    /// What [`init_card`](Self::init_card) found, once it has run. The bring-up path gets this back
    /// from [`start`](Self::start); this is the after-the-fact accessor for diagnostics.
    #[allow(dead_code)]
    pub fn card(&self) -> Option<CardInfo> {
        self.card
    }

    /// Capacity in 512 B blocks — what `embedded_sdmmc::BlockDevice::num_blocks` reports.
    pub fn num_blocks(&self) -> Result<u32, SemmcError> {
        self.card.map(|c| c.blocks).ok_or(SemmcError::NotInitialised)
    }

    /// Override the firmware's data-sampling delay, which defaults to 0. See
    /// [`read_delay`](Self::read_delay). There is no caller: 0 is correct on every harness measured
    /// so far, and the knob exists so a marginal one is a one-line change at the bring-up site.
    #[allow(dead_code)]
    pub fn set_read_delay(&mut self, cycles: u32) {
        self.read_delay = cycles;
    }

    /// The one-call bring-up: pads to storage, cold-boot the image, power it on, let the card's
    /// supply settle, identify it. Run it once per power-on, with the FLPR already parked and the
    /// display side idle. Every later handover is
    /// [`enter_storage_mode`](Self::enter_storage_mode) and
    /// [`leave_storage_mode`](Self::leave_storage_mode), which never re-identify the card.
    ///
    /// Synchronous, and that is a contract. The storage mode must be held across the whole
    /// sequence: an `async` version yields at the card settle, at the CMD8 deliver-and-abort wait
    /// and at each ACMD41 poll, with the image live, all six pads on `CTRLSEL = VPR` and, at the
    /// CMD8 yield, a command on the wire that the function is about to abort by hand. A scheduler
    /// that treated one of those yields as a handover would repoint `INITPC`, reset the hart and
    /// flip B0/B1 out from under a transaction, which leaves the card mid-command with no host to
    /// finish it: the one failure this driver cannot recover from. Here there is no yield at all.
    ///
    /// Blocking costs nothing here. The panel's anti-DC-bias COM wave runs on the SWI01 interrupt
    /// executor at P3, which preempts thread mode, and on a `com-hw` build it is a TIMER, DPPI and
    /// GPIOTE chain that uses no CPU. `async` cost 6,464 B of permanently allocated stack, because
    /// awaited from `main` this chain's coroutine flattens into `main`'s task-body poll frame, whose
    /// slot set is allocated on every poll for the life of the program. `#[inline(never)]` does not
    /// fix that: it governs the future constructor, not the coroutine body.
    ///
    /// The waits are unchanged in duration — [`block_for`] busy-waits the same ticks a `Timer`
    /// would have slept — and they only run at boot, before the ride loop, the BLE stack or the USB
    /// plane exist.
    pub fn start(&mut self) -> Result<CardInfo, SemmcError> {
        park_hart();
        configure_storage_pads();
        self.cold_boot()?;
        self.enable()?;
        block_for(CARD_SETTLE);
        self.init_card()
    }

    /// Cold boot: copy the vendored image into the carve and start it. About 47 µs.
    fn cold_boot(&mut self) -> Result<(), SemmcError> {
        self.boot_firmware(true)
    }

    /// Warm boot: the image is already resident, so this is park, `INITPC`, `CPURUN`, ready stamp.
    /// About 12 µs; the whole storage-ward mode switch measures 29 µs.
    fn warm_boot(&mut self) -> Result<(), SemmcError> {
        self.boot_firmware(false)
    }

    /// Take the FLPR for storage: pads to VPR, warm-boot the resident image, power it on.
    ///
    /// The caller must already have brought the display side to a safe point. Never park mid-scan:
    /// await the EGU20 frame ack first. The card's own state survives untouched, so there is
    /// deliberately no re-initialisation here.
    pub fn enter_storage_mode(&mut self) -> Result<(), SemmcError> {
        park_hart();
        configure_storage_pads();
        self.warm_boot()?;
        self.enable()
    }

    /// Hand the FLPR back to the display: quiesce the peripheral, park the hart, flip the pads.
    ///
    /// Infallible by construction, because every transfer path closes its own transaction before it
    /// returns, so this only has to clear latched events and stop the core.
    pub fn leave_storage_mode(&mut self) {
        // A deferred map write is normally joined before the store lock is released. Keep the mux
        // total on error and abort paths too: the display must never park the FLPR while its DMA
        // still owns a staging half.
        if self.pending_write_blocks != 0 {
            let _ = self.finish_write_blocks();
        }
        // Plain VRI writes, no barrier: nothing is in flight, and the hart is about to be reset.
        vri_write(VRI_CFG_READYTOTRANSFER, 0);
        vri_write(VRI_EV_XFERCOMPLETE, 0);
        vri_write(VRI_EV_ABORTED, 0);
        vri_write(VRI_EV_READYTOTRANSFER, 0);
        COMPLETION.store(false, Ordering::Relaxed);
        // Disarm our VEVIF gate and drop any latched event before the display blob owns the hart:
        // the two images share one VPR00 interrupt line, and a completion event left pending would
        // fire `on_vpr00_irq` against a peripheral that no longer exists. The next `boot_firmware`
        // re-arms it, which is where it has to be, because `INTENSET` writes are dropped while the
        // core is stopped.
        // SAFETY: fixed VPR00 MMIO; `INTENCLR` is a clear-mask write.
        unsafe {
            VPR00_INTENCLR.write_volatile(1 << EV_COMPLETION);
            VPR00_EVENTS_TRIGGERED.add(EV_COMPLETION).write_volatile(0);
        }
        park_hart();
        configure_display_pads();
    }

    /// Boot or re-boot the firmware: park, optionally re-copy the image, zero the VRI, set
    /// `ENABLE`, point `INITPC` at the carve, run, and wait for the firmware to clear `ENABLE`,
    /// which is its ready stamp.
    ///
    /// The cold path zeroes the whole [`SEMMC_IMAGE_BYTES`]. The firmware clears its own `.bss`, so
    /// this is not load-bearing, but starting the coprocessor on RAM of known content costs one
    /// `memset` at boot and nothing thereafter.
    fn boot_firmware(&mut self, copy_image: bool) -> Result<(), SemmcError> {
        park_hart();
        if copy_image {
            // SAFETY: the carve is RAM outside the M33's linked region, so nothing aliases it, and
            // the hart is parked.
            unsafe {
                core::ptr::write_bytes(SEMMC_RAM_BASE as *mut u8, 0, SEMMC_IMAGE_BYTES);
                core::ptr::copy_nonoverlapping(SEMMC_FW.as_ptr(), SEMMC_RAM_BASE as *mut u8, SEMMC_FW.len());
            }
        }
        // SAFETY: as above — the VRI page, with the hart parked.
        unsafe { core::ptr::write_bytes(VRI_BASE as *mut u8, 0, SEMMC_VRI_BYTES) };
        vri_write(VRI_ENABLE, 1);
        // SAFETY: fixed VPR00 MMIO. The `dsb` publishes the image + VRI before the core is released.
        unsafe {
            cortex_m::asm::dsb();
            VPR00_INITPC.write_volatile(SEMMC_RAM_BASE as u32);
            VPR00_CPURUN.write_volatile(1);
        }
        let deadline = Instant::now() + BOOT_DEADLINE;
        while vri_read(VRI_ENABLE) != 0 {
            if Instant::now() >= deadline {
                warn!("sEMMC: firmware never stamped ready (ENABLE stayed 1)");
                return Err(SemmcError::NoBoot);
            }
        }
        vri_write(VRI_INTEN, VRI_INTEN_ALL);
        // Arm the VEVIF gate for the completion event. This must happen with the core RUNNING:
        // `INTENSET` writes are silently dropped while the VPR is stopped, which is why this re-runs
        // on every boot instead of once at init.
        // SAFETY: fixed VPR00 MMIO; `INTENSET` is a set-mask write, so it is idempotent.
        unsafe { VPR00_INTENSET.write_volatile(1 << EV_COMPLETION) };
        COMPLETION.store(false, Ordering::Relaxed);
        Ok(())
    }

    /// Law 1, `nrf_semmc_enable()`. After a boot the firmware is initialised but not powered on,
    /// and it ignores start triggers until `ENABLE = 1` is followed by an `__ASB`.
    ///
    /// Private, and the boot entry points are too: law 1 is only a law if it cannot be skipped. The
    /// two public sequences both end here.
    fn enable(&mut self) -> Result<(), SemmcError> {
        vri_write(VRI_ENABLE, 1);
        let r = self.barrier(T_ACTION);
        vri_write(VRI_EV_XFERCOMPLETE, 0);
        vri_write(VRI_EV_ABORTED, 0);
        vri_write(VRI_EV_READYTOTRANSFER, 0);
        r
    }

    /// Wedge recovery: try a stop barrier, warm re-boot the resident image, power back on, and if
    /// even that fails, re-copy the image. The card is untouched — it keeps its RCA, bus width and
    /// speed mode — so the caller can simply retry the failed command.
    ///
    /// It stays synchronous even though [`BOOT_DEADLINE`] is 500 ms: it is the rare error path,
    /// reached from sync transfer code, and the normal cost is the 600 µs a warm reboot takes.
    fn recover(&mut self) {
        let _ = self.barrier(T_STOP);
        if self.boot_firmware(false).is_err() {
            warn!("sEMMC: warm re-boot failed — re-copying the image");
            if self.boot_firmware(true).is_err() {
                warn!("sEMMC: firmware will not boot at all");
                return;
            }
        }
        let _ = self.enable();
    }

    /// A barrier on the command path, with the recovery a failed one has earned.
    ///
    /// [`SemmcError::Barrier`] is "the firmware is wedged", and leaving it unrecovered kills storage
    /// for the rest of the session. The second barrier in [`cmd_start`] can additionally fail with
    /// `CONFIG.READYTOTRANSFER` already set and no start trigger issued, which is the law-2 poison
    /// state where the firmware considers a transaction open forever. A warm reboot costs 600 µs
    /// against a 50 ms barrier timeout. [`recover`](Self::recover) uses the raw
    /// [`barrier`](Self::barrier), so this cannot recurse.
    fn barrier_or_recover(&mut self, task: usize) -> Result<(), SemmcError> {
        match self.barrier(task) {
            Ok(()) => Ok(()),
            Err(e) => {
                warn!("sEMMC: barrier timeout — warm-rebooting the firmware");
                self.recover();
                Err(e)
            }
        }
    }

    /// One `__XSBx` barrier: publish the counter into `SPSYNC.AUX[0]`, trigger the task, wait for
    /// the firmware's echo in `AUX[1]`. About 2.2 µs; the deadline only fires on a wedge.
    fn barrier(&mut self, task: usize) -> Result<(), SemmcError> {
        self.counter = self.counter.wrapping_add(1);
        vri_write(VRI_SPSYNC_AUX, self.counter);
        // SAFETY: fixed VPR00 MMIO; the task index is one of the four soft-peripheral constants.
        unsafe { VPR00_TASKS_TRIGGER.add(task).write_volatile(1) };
        let deadline = Instant::now() + BARRIER_DEADLINE;
        while vri_read(VRI_SPSYNC_AUX) != vri_read(VRI_SPSYNC_AUX + 4) {
            if Instant::now() >= deadline {
                return Err(SemmcError::Barrier);
            }
        }
        Ok(())
    }

    /// Law 2: close the transaction with `CONFIG.READYTOTRANSFER = 0` plus the `__ASB` ack. Without
    /// the barrier the firmware still considers the old transaction open and ignores the next start
    /// trigger, which is the "first command works, second times out" alternation.
    fn close_transaction(&mut self) -> Result<(), SemmcError> {
        vri_write(VRI_CFG_READYTOTRANSFER, 0);
        self.barrier_or_recover(T_ACTION)
    }

    /// The front half of `nrf_semmc_cmd()`: fill CONFIG + COMMAND + DATA, `__CSB`, arm
    /// `READYTOTRANSFER`, `__ASB`, trigger the start task.
    fn cmd_start(
        &mut self,
        idx: u32,
        arg: u32,
        resp: u32,
        proc: u32,
        data: Option<(u32, u32, u32)>,
    ) -> Result<(), SemmcError> {
        vri_write(VRI_CFG_CLKFREQHZ, self.clk_hz);
        vri_write(VRI_CFG_BUSWIDTH, self.bus_width);
        vri_write(VRI_CFG_NUMRETRIES, self.num_retries);
        vri_write(VRI_CFG_READDELAY, self.read_delay);
        vri_write(VRI_CMD_CMD, (idx & 0xFFFF) | (resp << 16) | (proc << 24));
        vri_write(VRI_CMD_ARG, arg);
        vri_write(VRI_CMD_RESPONSEADDR, &raw const RESP_RAW as u32);
        let (buf, block_size, block_num) = data.unwrap_or((0, 0, 0));
        vri_write(VRI_DATA_BUFFERADDR, buf);
        vri_write(VRI_DATA_BLOCKSIZE, block_size);
        vri_write(VRI_DATA_BLOCKNUM, block_num);
        self.barrier_or_recover(T_CONFIG)?;
        vri_write(VRI_CFG_READYTOTRANSFER, 1);
        self.barrier_or_recover(T_ACTION)?;
        COMPLETION.store(false, Ordering::Relaxed);
        // SAFETY: fixed VPR00 MMIO.
        unsafe { VPR00_TASKS_TRIGGER.add(T_START).write_volatile(1) };
        Ok(())
    }

    /// Wait for the transfer to end, and close the transaction (law 2) either way.
    ///
    /// Bounded polling with an interrupt fast path, not a sleep. `WFE` woken by [`on_vpr00_irq`] is
    /// not sound here: WFE only returns when the event register is set, and nothing guarantees that
    /// ever happens. Embassy's cortex-m platform does not set `SCB.SCR.SEVONPEND`, the GRTC time
    /// driver only interrupts when a timer is scheduled, and the two cases this wait exists to
    /// survive — a `VPR00` vector that is unbound or disarmed, and a firmware that wedged
    /// mid-transfer — are exactly the cases where no interrupt arrives at all. The deadline would
    /// then never be evaluated.
    ///
    /// So the loop re-checks on a fixed [`WAIT_SLICE_CYCLES`] slice, which makes the deadline
    /// reachable with zero interrupts. The core spins for the duration of a transfer instead of
    /// idling, which is the same profile the SPI transport had, and the transfers are far shorter.
    ///
    /// The completion interrupt is therefore diagnostic, not load-bearing: the VRI events are read
    /// unconditionally on every slice, and [`COMPLETION`] only records whether an interrupt
    /// accompanied the completion, so "the vector is not bound" can be reported once.
    fn wait_completion(&mut self, timeout: Duration) -> Result<(), SemmcError> {
        let deadline = Instant::now() + timeout;
        loop {
            let signalled = COMPLETION.swap(false, Ordering::Acquire);
            if let Some(outcome) = self.take_completion() {
                // The second load closes the race where the interrupt lands between the swap and the
                // event read; otherwise a healthy vector could earn the warning.
                if !signalled && !COMPLETION.load(Ordering::Relaxed) && !WARNED_NO_IRQ.swap(true, Ordering::Relaxed) {
                    warn!("sEMMC: completion seen without a VPR00 interrupt — is the vector bound?");
                }
                return outcome;
            }
            if Instant::now() >= deadline {
                vri_write(VRI_CFG_READYTOTRANSFER, 0);
                self.recover();
                return Err(SemmcError::Timeout);
            }
            // A bounded slice, not a sleep. It also keeps the M33 off the SRAM bus the FLPR is
            // DMA-ing across, which a tight re-read loop would not.
            cortex_m::asm::delay(WAIT_SLICE_CYCLES);
        }
    }

    /// Read the VRI completion events. `Some` once the transfer has ended, with the transaction
    /// already closed.
    ///
    /// Every raised event is serviced and cleared in one pass: clearing only the one we matched
    /// would leave a latched `ABORTED` behind, to be mistaken for the next command's outcome. An
    /// abort wins over a completion when both are set, because the transfer did not deliver what was
    /// asked for.
    fn take_completion(&mut self) -> Option<Result<(), SemmcError>> {
        let complete = vri_read(VRI_EV_XFERCOMPLETE) != 0;
        let aborted = vri_read(VRI_EV_ABORTED) != 0;
        if !complete && !aborted {
            return None;
        }
        let status = vri_read(VRI_STATUS);
        vri_write(VRI_EV_XFERCOMPLETE, 0);
        vri_write(VRI_EV_ABORTED, 0);
        vri_write(VRI_EV_READYTOTRANSFER, 0);
        // The FLPR's DMA writes into the caller's buffer are finished as of the completion event.
        // `dsb` orders this core's accesses behind the event reads above, and the compiler fence
        // stops LLVM hoisting a buffer load past them. There is no data cache to invalidate here.
        cortex_m::asm::dsb();
        core::sync::atomic::compiler_fence(Ordering::Acquire);
        // Nordic's abort path closes the transaction the same way a completion does; without the
        // barrier the firmware never re-arms.
        let closed = self.close_transaction();
        if aborted {
            return Some(Err(SemmcError::Aborted(status)));
        }
        Some(closed)
    }

    /// Run one SD command to completion. `data` is `(buffer, block_size, block_count)`; the
    /// direction comes from the firmware's command-index table. Returns the four response words,
    /// LSW first (law 3).
    fn cmd(
        &mut self,
        idx: u32,
        arg: u32,
        resp: u32,
        proc: u32,
        data: Option<(u32, u32, u32)>,
        timeout: Duration,
    ) -> Result<[u32; 4], SemmcError> {
        self.cmd_start(idx, arg, resp, proc, data)?;
        self.wait_completion(timeout)?;
        Ok([
            vri_read(VRI_CMD_RESPONSE0),
            vri_read(VRI_CMD_RESPONSE0 + 4),
            vri_read(VRI_CMD_RESPONSE0 + 8),
            vri_read(VRI_CMD_RESPONSE0 + 12),
        ])
    }

    /// An application command: CMD55 with the current RCA, then the ACMD itself.
    fn acmd(&mut self, idx: u32, arg: u32, resp: u32, timeout: Duration) -> Result<[u32; 4], SemmcError> {
        self.cmd(55, self.rca << 16, RESP_R1, PROC_PROCESS, None, timeout)?;
        self.cmd(idx, arg, resp, PROC_PROCESS, None, timeout)
    }

    /// CMD13 for the card's `CURRENT_STATE`. It is also the read path's response fetch, because the
    /// firmware cannot process a response and a data phase at the same time.
    pub fn card_state(&mut self) -> Result<u8, SemmcError> {
        self.card_status().map(|(_, state)| state)
    }

    /// CMD13 → `(raw R1, state)`.
    fn card_status(&mut self) -> Result<(u32, u8), SemmcError> {
        let r = self.cmd(13, self.rca << 16, RESP_R1, PROC_PROCESS, None, STATUS_DEADLINE)?;
        Ok((r[0], ((r[0] >> 9) & 0xF) as u8))
    }

    /// The CMD8 workaround. Deliver `SEND_IF_COND`, give the card time to put its R7 on the wire,
    /// then abandon the host-side wait with Nordic's own abort barrier (`__SSB`) rather than a
    /// reboot. The R7 payload is never read: the card's side of CMD8 is complete the moment it
    /// answers, and that is what arms ACMD41's HCS handling.
    fn cmd8_deliver_abort(&mut self) -> Result<(), SemmcError> {
        // A blob with a fixed index table would simply complete this, so try that first.
        if let Ok(r) = self.cmd(8, 0x1AA, RESP_R1, PROC_PROCESS, None, Duration::from_millis(100)) {
            if r[0] & 0xFFF == 0x1AA {
                return Ok(());
            }
        }
        self.cmd_start(8, 0x1AA, RESP_R1, PROC_PROCESS, None)?;
        block_for(CMD8_DELIVER);
        let stopped = self.barrier(T_STOP).is_ok();
        let mut acked = false;
        if stopped {
            let deadline = Instant::now() + BARRIER_DEADLINE;
            while Instant::now() < deadline {
                if vri_read(VRI_EV_ABORTED) != 0 || vri_read(VRI_EV_XFERCOMPLETE) != 0 {
                    acked = true;
                    break;
                }
            }
        }
        vri_write(VRI_EV_ABORTED, 0);
        vri_write(VRI_EV_XFERCOMPLETE, 0);
        if stopped && acked {
            // `close_transaction` recovers itself if its barrier times out.
            let _ = self.close_transaction();
        } else {
            // The firmware ignored the stop: a warm re-boot cleans up, and the card is unaffected.
            self.recover();
        }
        Ok(())
    }

    /// The CMD6 workaround. Ask for High Speed as the firmware expects (`SWITCH`, R1b, no data
    /// descriptor), then drain the orphaned 64 B status block with a CMD17 the card ignores.
    /// `byte16 & 0xF == 1` in what lands is the card's own confirmation that it switched.
    ///
    /// Returns whether the switch is confirmed. A failure here is not fatal: the bus stays at
    /// Default Speed.
    fn cmd6_high_speed(&mut self) -> Result<bool, SemmcError> {
        // A plain `?` here would leave by the one door that skips the whole rescue. CMD6 is an R1b,
        // so the card holds D0 low while it applies the switch, and a card that never releases busy
        // times out, `wait_completion` warm-reboots the host, and the early return sails past the
        // drain, the tolerant loop and the CMD12. The card is meanwhile in `data` with its status
        // block undelivered, and every later read is illegal.
        if let Err(e) = self.cmd(6, 0x80FF_FFF1, RESP_R1B, PROC_PROCESS, None, CMD_DEADLINE) {
            let _ = self.stop_transmission();
            return Err(e);
        }

        let mut drain = AlignedBlock([0xEE; BLOCK_BYTES]);
        let addr = drain.0.as_mut_ptr() as u32;
        self.num_retries = 0; // a retry would hunt for a second start bit forever
        let data = Some((addr, BLOCK_BYTES as u32, 1));
        // Expected to end in an abort: the orphan is 64 B, not 512. The drain is the point.
        let _ = self.cmd(17, self.block_arg(0), RESP_R1, PROC_IGNORE, data, Duration::from_millis(300));
        self.num_retries = NUM_RETRIES;

        let landed = drain.0[..64].iter().any(|&b| b != 0xEE);
        let switched = !landed || drain.0[16] & 0xF == 1;

        // Let the card finish and come back to `tran`. CMD13 also clears the CMD17 illegal flag.
        //
        // Tolerant on purpose: do not `?` this loop. The drain read ends in an abort by design, and
        // it can also time out and warm-reboot the host, so the CMD13 right after it is the command
        // most likely to return an error. An early return would skip the CMD12 below and leave the
        // card stranded in `data`, where every later read is illegal, and no host-side recovery
        // fixes a card-side state.
        let mut in_tran = false;
        for _ in 0..4 {
            if let Ok(state) = self.card_state() {
                if state == CARD_STATE_TRAN {
                    in_tran = true;
                    break;
                }
            }
        }
        if !in_tran {
            // The rescue, and it must be unconditional: STOP_TRANSMISSION is what walks a card out
            // of `data` when the drain did not.
            let _ = self.cmd(12, 0, RESP_R1B, PROC_PROCESS, None, CMD_DEADLINE);
            return Ok(false);
        }
        Ok(switched)
    }

    /// Bring the card from power-on to ready: 4-bit, High Speed if it takes, 32 MHz reads.
    ///
    /// The ladder is CMD0 twice at 400 kHz, CMD8 deliver-and-abort, CMD55 and ACMD41, CMD2, CMD3,
    /// CMD9, CMD7, ACMD6 with `CONFIG.BUSWIDTH = 4`, the CMD6 drain read, then 32 MHz, verified
    /// against a Default-Speed golden read of sector 0 before it is trusted.
    ///
    /// It runs once per power-on, not per mode switch: the card keeps its state across a park.
    fn init_card(&mut self) -> Result<CardInfo, SemmcError> {
        self.card = None;
        self.rca = 0;
        self.bus_width = 1;
        self.clk_hz = CLK_INIT_HZ;
        self.num_retries = NUM_RETRIES;

        // CMD0 GO_IDLE_STATE, twice: the card may miss the first while its supply is still settling,
        // and it carries no response to tell us so.
        let mut idle = false;
        for _ in 0..2 {
            idle |= self.cmd(0, 0, RESP_NONE, PROC_PROCESS, None, CMD_DEADLINE).is_ok();
        }
        if !idle {
            return Err(SemmcError::NoCard);
        }

        self.cmd8_deliver_abort()?;

        // ACMD41 until the card reports powered up. HCS asks for block addressing, and 0xFF8000 is
        // the full 2.7 to 3.6 V window.
        let deadline = Instant::now() + POWERUP_DEADLINE;
        let ocr = loop {
            match self.acmd(41, 0x4030_0000 | 0x00FF_8000, RESP_R3, CMD_DEADLINE) {
                Ok(r) if r[0] & 0x8000_0000 != 0 => break r[0],
                Ok(_) => {}
                Err(e) => return Err(e),
            }
            if Instant::now() >= deadline {
                return Err(SemmcError::NoCard);
            }
            block_for(POWERUP_POLL); // a poll interval
        };
        if ocr & 0x4000_0000 == 0 {
            // CCS = 0 is a byte-addressed SDSC card. Rejected; see `UnsupportedCard`.
            return Err(SemmcError::UnsupportedCard);
        }

        self.cmd(2, 0, RESP_R2, PROC_PROCESS, None, CMD_DEADLINE)?; // CID
        let r = self.cmd(3, 0, RESP_R1, PROC_PROCESS, None, CMD_DEADLINE)?; // RCA (R6)
        self.rca = (r[0] >> 16) & 0xFFFF;
        let csd = self.cmd(9, self.rca << 16, RESP_R2, PROC_PROCESS, None, CMD_DEADLINE)?;
        let blocks = csd_v2_blocks(&csd)?;
        self.cmd(7, self.rca << 16, RESP_R1B, PROC_PROCESS, None, CMD_DEADLINE)?; // select
        if self.card_state()? != CARD_STATE_TRAN {
            return Err(SemmcError::CardBusy);
        }

        // 4-bit: the card first (ACMD6 argument 2), then the host. In that order, or the next
        // command is spoken on a bus the two sides disagree about.
        self.acmd(6, 0b10, RESP_R1, CMD_DEADLINE)?;
        self.bus_width = 4;
        self.clk_hz = CLK_DS_HZ;
        self.read_clk_hz = CLK_DS_HZ;
        self.write_clk_hz = CLK_WRITE_MAX_HZ;

        // A Default-Speed golden read is what the High-Speed rung is checked against: 32 MHz that
        // returns different bytes is worse than 21.3 MHz that returns the right ones.
        let mut golden = AlignedBlock([0; BLOCK_BYTES]);
        self.read_one(0, &mut golden)?;

        if self.cmd6_high_speed().unwrap_or(false) {
            self.clk_hz = CLK_HS_HZ;
            let mut check = AlignedBlock([0; BLOCK_BYTES]);
            if self.read_one(0, &mut check).is_ok() && check.0 == golden.0 {
                self.read_clk_hz = CLK_HS_HZ;
            } else {
                warn!("sEMMC: High Speed accepted but 32 MHz reads are not stable — staying at 21.3 MHz");
                self.clk_hz = CLK_DS_HZ;
            }
        }

        let info = CardInfo {
            rca: self.rca as u16,
            blocks,
            high_speed: self.read_clk_hz == CLK_HS_HZ,
            read_clk_hz: self.read_clk_hz,
        };
        self.card = Some(info);
        Ok(info)
    }

    /// Block address for `lba`. SDHC and SDXC only, so this is the identity, kept as a named step
    /// because the byte-addressed alternative is where every "reads land 512 times too far in" bug
    /// comes from.
    fn block_arg(&self, lba: u32) -> u32 {
        lba
    }

    /// Best-effort STOP_TRANSMISSION after a failed transfer.
    ///
    /// It is needed on every failed data command, not only the multi-block ones: the recovery path
    /// resets the host, and a card that was mid-block sits in `data` or `rcv` waiting for clocks
    /// that are not coming. The card is the one piece of state a warm reboot cannot repair.
    fn stop_transmission(&mut self) -> Result<(), SemmcError> {
        self.cmd(12, 0, RESP_R1B, PROC_PROCESS, None, CMD_DEADLINE).map(|_| ())
    }

    fn read_one(&mut self, lba: u32, block: &mut AlignedBlock) -> Result<(), SemmcError> {
        let addr = block.0.as_mut_ptr() as u32;
        let data = Some((addr, BLOCK_BYTES as u32, 1));
        if let Err(e) = self.cmd(17, self.block_arg(lba), RESP_R1, PROC_IGNORE, data, READ_DEADLINE) {
            let _ = self.stop_transmission();
            return Err(e);
        }
        self.check_after_transfer()
    }

    /// Read `buf.len() / 512` blocks starting at `lba`.
    ///
    /// CMD17 for one block, CMD18 and CMD12 for more. Reads run with `PROC_IGNORE` and a following
    /// CMD13, because the firmware cannot process a response and a data phase at the same time, so
    /// the card's R1 for the transfer is fetched afterwards and its error bits surfaced as
    /// [`SemmcError::CardStatus`].
    ///
    /// `buf` must be a non-empty whole number of 512 B blocks and 32-bit aligned, which is the
    /// firmware's DMA requirement; otherwise [`SemmcError::BadBuffer`]. `embedded_sdmmc::Block`
    /// carries no alignment attribute and cannot gain one, so `sd::SemmcCard` meets the requirement
    /// by bouncing through the aligned `sd::BOUNCE` in 4-block batches.
    ///
    /// Blocking, and it holds the core while the transfer runs. See
    /// [`wait_completion`](Self::wait_completion) for why the wait is a bounded poll. Read and
    /// cleanup commands each get two retries after a controller abort, and a new read starts only
    /// after cleanup succeeds.
    pub fn read_blocks(&mut self, lba: u32, buf: &mut [u8]) -> Result<(), SemmcError> {
        let n = self.check_request(buf.as_ptr() as usize, buf.len(), lba)?;
        self.clk_hz = self.read_clk_hz;
        let data = Some((buf.as_mut_ptr() as u32, BLOCK_BYTES as u32, n));
        let mut retries_remaining = READ_ABORT_RETRIES;
        loop {
            let command = if n == 1 { 17 } else { 18 };
            let transfer = self.cmd(command, self.block_arg(lba), RESP_R1, PROC_IGNORE, data, READ_DEADLINE);
            if n != 1 || transfer.is_err() {
                // The card can still be streaming after a read abort. An aborted stop must be
                // retried before another read; resetting the host does not stop the card.
                for attempt in 0..=READ_ABORT_RETRIES {
                    match self.stop_transmission() {
                        Err(SemmcError::Aborted(_)) if attempt < READ_ABORT_RETRIES => {
                            defmt::debug!("sEMMC: read cleanup retry {=usize}", attempt + 1);
                        }
                        result => {
                            result?;
                            break;
                        }
                    }
                }
            }
            let transfer = transfer.map(|_| ()).and_then(|()| self.check_after_transfer());

            match transfer {
                Err(SemmcError::Aborted(_)) if retries_remaining != 0 => {
                    retries_remaining -= 1;
                }
                result => return result,
            }
        }
    }

    /// Start writing `buf.len() / 512` blocks at `lba`, leaving the data phase in flight.
    ///
    /// # Safety
    ///
    /// The FLPR DMA keeps reading `buf` after this function returns. The caller must keep that
    /// allocation alive, aligned and byte-for-byte unchanged until
    /// [`finish_write_blocks`](Self::finish_write_blocks) returns, and must serialize every other
    /// sEMMC command behind that finish. The USB map pipeline satisfies this with two disjoint
    /// arena halves and one store owner; generic block-device callers never use this entry point.
    pub unsafe fn start_write_blocks(&mut self, lba: u32, buf: &[u8]) -> Result<(), SemmcError> {
        if self.pending_write_blocks != 0 {
            return Err(SemmcError::Busy);
        }
        let n = self.check_request(buf.as_ptr() as usize, buf.len(), lba)?;
        self.clk_hz = self.write_clk_hz;
        if n > 1 && self.preerase_supported {
            let prepared = self.acmd(23, n, RESP_R1, CMD_DEADLINE).and_then(|r| check_r1(r[0]));
            if let Err(e) = prepared {
                // SET_WR_BLK_ERASE_COUNT is a performance hint. Older or unusual cards may reject
                // it; remember that answer and continue with the ordinary CMD25 path.
                self.preerase_supported = false;
                warn!("sEMMC: ACMD23 pre-erase hint unavailable ({}) — continuing without it", e);
            }
        }
        let data = Some((buf.as_ptr() as u32, BLOCK_BYTES as u32, n));
        let idx = if n == 1 { 24 } else { 25 };
        self.cmd_start(idx, self.block_arg(lba), RESP_R1, PROC_PROCESS, data)?;
        self.pending_write_blocks = n;
        Ok(())
    }

    /// Join the write started by [`start_write_blocks`](Self::start_write_blocks), stop a
    /// multi-block stream, and wait until the card has left `prg`.
    pub fn finish_write_blocks(&mut self) -> Result<(), SemmcError> {
        let n = core::mem::take(&mut self.pending_write_blocks);
        if n == 0 {
            return Ok(());
        }
        let transfer = self.wait_completion(WRITE_DEADLINE);
        if n == 1 {
            if let Err(e) = transfer {
                let _ = self.stop_transmission();
                return Err(e);
            }
        } else {
            // Even a failed CMD25 leaves the card waiting in `rcv`; stop it before surfacing the
            // original result.
            let stop = self.cmd(12, 0, RESP_R1B, PROC_PROCESS, None, CMD_DEADLINE);
            transfer?;
            stop?;
        }
        let deadline = Instant::now() + PROGRAM_DEADLINE;
        loop {
            let (r1, state) = self.card_status()?;
            if state == CARD_STATE_TRAN {
                return check_r1(r1);
            }
            if state != CARD_STATE_PRG && r1 & R1_ERROR_MASK != 0 {
                return Err(SemmcError::CardStatus(r1));
            }
            if Instant::now() >= deadline {
                return Err(SemmcError::CardBusy);
            }
        }
    }

    /// Write `buf.len() / 512` blocks starting at `lba`.
    ///
    /// CMD24 for one block, CMD25 and CMD12 for more, then CMD13 until the card leaves `prg`: the
    /// program cycle is the completion signal for a write. It runs at [`CLK_WRITE_MAX_HZ`]
    /// regardless of the read clock. Same buffer rules as [`read_blocks`](Self::read_blocks).
    pub fn write_blocks(&mut self, lba: u32, buf: &[u8]) -> Result<(), SemmcError> {
        // SAFETY: this synchronous wrapper retains `buf` unchanged until the immediately following
        // finish returns, and issues no intervening command.
        unsafe { self.start_write_blocks(lba, buf)? };
        self.finish_write_blocks()
    }

    /// The card's own verdict on the transfer that just ran (reads ignore the in-band response).
    fn check_after_transfer(&mut self) -> Result<(), SemmcError> {
        let (r1, _) = self.card_status()?;
        check_r1(r1)
    }

    /// Validate a caller's buffer against the firmware's DMA rules and the span against the card's
    /// capacity, returning the block count.
    ///
    /// The span check is ours rather than the card's `OUT_OF_RANGE`: a run that walks off the end
    /// should be refused before it is clocked onto the bus, not diagnosed from an error bit after a
    /// partial transfer has landed in the caller's buffer.
    fn check_request(&self, addr: usize, len: usize, lba: u32) -> Result<u32, SemmcError> {
        let card = self.card.ok_or(SemmcError::NotInitialised)?;
        if len == 0 || !len.is_multiple_of(BLOCK_BYTES) || !addr.is_multiple_of(4) {
            return Err(SemmcError::BadBuffer);
        }
        let n = (len / BLOCK_BYTES) as u32;
        if u64::from(lba) + u64::from(n) > u64::from(card.blocks) {
            return Err(SemmcError::OutOfRange);
        }
        Ok(n)
    }
}

fn check_r1(r1: u32) -> Result<(), SemmcError> {
    if r1 & R1_ERROR_MASK != 0 {
        Err(SemmcError::CardStatus(r1))
    } else {
        Ok(())
    }
}

/// Capacity in 512 B blocks from a CSD version 2 (SDHC or SDXC). Words arrive LSW-first (law 3), so
/// `csd[3]` holds bits 127:96 and `CSD_STRUCTURE` is its top two bits. `C_SIZE` (bits 69:48)
/// straddles `csd[1]`'s high half and `csd[2]`'s low six bits, and the capacity is
/// `(C_SIZE + 1) × 512 KiB`.
fn csd_v2_blocks(csd: &[u32; 4]) -> Result<u32, SemmcError> {
    if csd[3] >> 30 != 1 {
        return Err(SemmcError::UnsupportedCard);
    }
    let c_size = ((csd[2] & 0x3F) << 16) | (csd[1] >> 16);
    // 1024 blocks per 512 KiB unit. `c_size` is 22 bits, so the product reaches 2^32 exactly at the
    // all-ones value, which is one block past what a u32 block count can express and a capacity no
    // SD card has. `saturating_mul` clamps that unreachable case instead of wrapping to zero.
    Ok(c_size.saturating_add(1).saturating_mul(1024))
}
