#!/usr/bin/env python3
"""Generate CHANGELOG.md from merged pull requests: one line each, newest first.

This file exists so that a record has somewhere to go. Measurement notes, version
deltas and "what this change did to that number" kept landing inside gate files and
normative contracts because nothing else would hold them. They land here instead, and
the detail stays in the pull request.

It is generated, never written by hand. That is what stops it becoming the next place
prose accumulates: `--check` regenerates and compares, so an essay added by hand fails.

Usage: python3 tools/changelog.py [--check | --update]
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHANGELOG = ROOT / "CHANGELOG.md"
REPO = "https://github.com/timohueser/OpenBikeComputer"

MERGE = re.compile(r"Merge pull request #(\d+) from ")
LONG_TITLE = 120

HEADER = """# Changelog

One line for each merged pull request, newest first. The pull request holds the detail:
what was measured, what was rejected, and why. Nothing else in this repository needs to
carry that history.

This file is generated by `obc changelog --update`. Do not edit it by hand.
"""


def entries() -> list[tuple[str, int, str]]:
    """Every merged pull request, as (month, number, title), newest first."""
    log = subprocess.run(
        ["git", "-C", str(ROOT), "log", "--merges", "--date=short",
         "--format=%cd%x1f%s%x1f%b%x1e"],
        capture_output=True, text=True, check=True,
    ).stdout

    found = []
    for record in log.split("\x1e"):
        if not record.strip():
            continue
        date, subject, body = (record.strip().split("\x1f") + ["", ""])[:3]
        match = MERGE.match(subject)
        if not match:
            continue
        title = next((line.strip() for line in body.splitlines() if line.strip()), "")
        if not title:
            continue
        found.append((date[:7], int(match.group(1)), title))
    return found


def render(found: list[tuple[str, int, str]]) -> str:
    out = [HEADER]
    month = None
    for entry_month, number, title in found:
        if entry_month != month:
            month = entry_month
            out.append(f"\n## {month}\n")
        out.append(f"- {title} ([#{number}]({REPO}/pull/{number}))")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="fail when the file is not current")
    group.add_argument("--update", action="store_true", help="regenerate the file")
    args = parser.parse_args()

    found = entries()
    text = render(found)

    if args.check:
        # A stale file is fine: the merge that lands a pull request can never be in the file
        # it carries. A line the generator would not write is not.
        current = CHANGELOG.read_text() if CHANGELOG.exists() else ""
        generated = set(text.splitlines())
        foreign = [l for l in current.splitlines() if l.strip() and l not in generated]
        if foreign:
            print("changelog: hand-written lines; run `obc changelog --update` and keep the detail in the pull request")
            for line in foreign[:5]:
                print(f"  {line[:100]}")
            return 1
        print(f"changelog: {len(found)} pull requests, nothing hand-written")
        return 0

    CHANGELOG.write_text(text)
    longest = sorted(found, key=lambda e: -len(e[2]))[:3]
    print(f"changelog: wrote {len(found)} pull requests")
    over = [e for e in found if len(e[2]) > LONG_TITLE]
    if over:
        print(f"  {len(over)} title(s) over {LONG_TITLE} characters — a title is one line:")
        for _, number, title in longest:
            if len(title) > LONG_TITLE:
                print(f"    #{number}: {len(title)} chars")
    return 0


if __name__ == "__main__":
    sys.exit(main())
