//! Compile-time translation catalog.
//!
//! The UI is authored in English literals; this module swaps them for a `(Msg, Language)` lookup,
//! so a screen renders in `settings.language` with no ambient state. [`Msg`] and [`TABLE`] are
//! generated by `build.rs` from `i18n/{en,de,fr,es}.toml`, and the build fails if any of the four
//! is missing a key or carries an extra one. `TABLE` is `const`, so the whole catalog lives in
//! flash and nothing lands in the RAM budget.

use crate::screen::{Ctx, Render};
use crate::settings::Language;

// Pulls in `pub enum Msg { … }` and `pub const TABLE: [[&str; 4]; N] = [ … ];`.
include!(concat!(env!("OUT_DIR"), "/i18n_gen.rs"));

/// Backs the "index never panics" contract of [`t`]: `TABLE` ships exactly one column per
/// [`Language`] variant. Nothing else ties the generated column count to the enum, so a fifth
/// `Language` added without a fifth catalog column would index out of bounds.
const _: () = assert!(
    TABLE[0].len() == Language::COUNT,
    "i18n TABLE column count must equal Language::COUNT — add the missing per-language catalog file(s)"
);

/// The translation for `m` in `lang`. The `Language` discriminants match TABLE's column order and
/// every `Msg` maps to a populated row, so the index never panics.
#[inline]
pub const fn t(m: Msg, lang: Language) -> &'static str {
    TABLE[m as usize][lang as usize]
}

impl<'a> Render<'a> {
    /// The translation for `m` in the current UI language.
    #[inline]
    pub fn t(&self, m: Msg) -> &'static str {
        t(m, self.settings.language)
    }
}

impl Ctx<'_> {
    /// The translation for `m` in the current UI language, for `handle` as well as `draw`.
    #[inline]
    pub fn t(&self, m: Msg) -> &'static str {
        t(m, self.settings.language)
    }
}
